Repository anza-xyz/agave, pull requests merged in 2024-09, with the labels that each got.

#2252 chore: bump curve25519-dalek from 3.2.1 to 4.1.3
  .github/scripts/downstream-project-spl-common.sh
  Cargo.lock
  Cargo.toml
  curves/curve25519/src/edwards.rs
  curves/curve25519/src/ristretto.rs
  curves/curve25519/src/scalar.rs
  perf/src/sigverify.rs
  programs/sbf/Cargo.lock
  sdk/program/src/pubkey.rs
  zk-sdk/Cargo.toml
  zk-sdk/src/encryption/elgamal.rs
  zk-sdk/src/encryption/pedersen.rs
  zk-sdk/src/range_proof/generators.rs
  zk-sdk/src/range_proof/inner_product.rs
  zk-sdk/src/range_proof/mod.rs
  zk-sdk/src/range_proof/util.rs
  zk-sdk/src/sigma_proofs/ciphertext_ciphertext_equality.rs
  zk-sdk/src/sigma_proofs/ciphertext_commitment_equality.rs
  zk-sdk/src/sigma_proofs/grouped_ciphertext_validity/handles_2.rs
  zk-sdk/src/sigma_proofs/grouped_ciphertext_validity/handles_3.rs
  zk-sdk/src/sigma_proofs/mod.rs
  zk-sdk/src/sigma_proofs/percentage_with_cap.rs
  zk-sdk/src/sigma_proofs/pubkey_validity.rs
  zk-sdk/src/sigma_proofs/zero_ciphertext.rs
  zk-token-sdk/Cargo.toml
  zk-token-sdk/src/encryption/elgamal.rs
  zk-token-sdk/src/encryption/pedersen.rs
  zk-token-sdk/src/instruction/zero_balance.rs
  zk-token-sdk/src/range_proof/generators.rs
  zk-token-sdk/src/range_proof/inner_product.rs
  zk-token-sdk/src/range_proof/mod.rs
  zk-token-sdk/src/range_proof/util.rs
  zk-token-sdk/src/sigma_proofs/ciphertext_ciphertext_equality_proof.rs
  zk-token-sdk/src/sigma_proofs/ciphertext_commitment_equality_proof.rs
  zk-token-sdk/src/sigma_proofs/fee_proof.rs
  zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof/handles_2.rs
  zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof/handles_3.rs
  zk-token-sdk/src/sigma_proofs/mod.rs
  zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
  zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
Labels: v2.0

#2815 fix typo backwards-compatibility.md
  docs/src/backwards-compatibility.md
Labels: community, need:merge-assist

#2802 Simplify RPC partitioned_epoch_reward_enabled determination
  rpc/src/rpc.rs
Labels: v2.0

#1967 Extract clock crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/clock/Cargo.toml
  sdk/clock/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/account_info.rs
  sdk/program/src/address_lookup_table/instruction.rs
  sdk/program/src/address_lookup_table/state.rs
  sdk/program/src/epoch_schedule.rs
  sdk/program/src/example_mocks.rs
  sdk/program/src/feature.rs
  sdk/program/src/fee_calculator.rs
  sdk/program/src/last_restart_slot.rs
  sdk/program/src/lib.rs
  sdk/program/src/program.rs
  sdk/program/src/rent.rs
  sdk/program/src/slot_hashes.rs
  sdk/program/src/stake/instruction.rs
  sdk/program/src/stake/state.rs
  sdk/program/src/stake/tools.rs
  sdk/program/src/stake_history.rs
  sdk/program/src/sysvar/clock.rs
  sdk/program/src/sysvar/mod.rs
  sdk/program/src/sysvar/recent_blockhashes.rs
  sdk/program/src/sysvar/slot_hashes.rs
  sdk/program/src/sysvar/stake_history.rs
  sdk/program/src/vote/authorized_voters.rs
  sdk/program/src/vote/instruction.rs
  sdk/program/src/vote/state/mod.rs
Labels: need:merge-assist

#2828 add ancient.total_alive_bytes metric
  accounts-db/src/accounts_db.rs
  accounts-db/src/ancient_append_vecs.rs
Labels: automerge

#2053 Extract serde-varint crate
  Cargo.lock
  Cargo.toml
  gossip/Cargo.toml
  gossip/src/contact_info.rs
  gossip/src/restart_crds_values.rs
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/vote/state/mod.rs
  sdk/serde-varint/Cargo.toml
  sdk/serde-varint/src/lib.rs
  sdk/src/lib.rs
  version/Cargo.toml
  version/src/lib.rs
Labels: automerge, need:merge-assist

#2827 shrink can work on 'ancient' slots
  accounts-db/src/accounts_db.rs
Labels: automerge

#2831 accounts-db: silence false positive info in shrink
  accounts-db/src/accounts_db.rs
Labels: automerge

#2834 rename pubkeys_to_unref
  accounts-db/src/accounts_db.rs
  accounts-db/src/ancient_append_vecs.rs
Labels: automerge

#2015 sdk: Extract hash and hasher crates
  Cargo.lock
  Cargo.toml
  accounts-db/src/blockhash_queue.rs
  core/src/banking_trace.rs
  core/src/consensus.rs
  core/src/consensus/tower1_14_11.rs
  core/src/consensus/tower1_7_14.rs
  core/src/repair/serve_repair.rs
  frozen-abi/Cargo.toml
  gossip/src/cluster_info.rs
  merkle-tree/Cargo.toml
  merkle-tree/src/merkle_tree.rs
  programs/sbf/Cargo.lock
  programs/vote/src/vote_state/mod.rs
  rpc-client-api/Cargo.toml
  runtime/src/bank.rs
  runtime/src/bank/serde_snapshot.rs
  sdk/hash/Cargo.toml
  sdk/hash/build.rs
  sdk/hash/src/lib.rs
  sdk/macro/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/hash.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/message/versions/mod.rs
  sdk/program/src/syscalls/definitions.rs
  sdk/program/src/vote/state/mod.rs
  sdk/program/src/wasm/hash.rs
  sdk/program/src/wasm/mod.rs
  sdk/sha256-hasher/Cargo.toml
  sdk/sha256-hasher/src/lib.rs
  sdk/src/transaction/mod.rs
Labels: automerge, need:merge-assist

#2056 Extract derivation-path crate
  Cargo.lock
  Cargo.toml
  clap-utils/Cargo.toml
  clap-utils/src/keypair.rs
  clap-v3-utils/Cargo.toml
  clap-v3-utils/src/input_parsers/signer.rs
  clap-v3-utils/src/keygen/derivation_path.rs
  clap-v3-utils/src/keypair.rs
  keygen/Cargo.toml
  programs/sbf/Cargo.lock
  remote-wallet/Cargo.toml
  remote-wallet/src/ledger.rs
  remote-wallet/src/remote_keypair.rs
  remote-wallet/src/remote_wallet.rs
  sdk/Cargo.toml
  sdk/derivation-path/Cargo.toml
  sdk/derivation-path/src/lib.rs
  sdk/src/lib.rs
  sdk/src/signer/keypair.rs
  sdk/src/signer/mod.rs
  zk-sdk/Cargo.toml
  zk-sdk/src/encryption/auth_encryption.rs
  zk-sdk/src/encryption/elgamal.rs
  zk-token-sdk/Cargo.toml
  zk-token-sdk/src/encryption/auth_encryption.rs
  zk-token-sdk/src/encryption/elgamal.rs
Labels: automerge, need:merge-assist

#2832 Consistent TransactionPriorityId ordering/equality
  core/src/banking_stage/scheduler_messages.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
  core/src/banking_stage/transaction_scheduler/transaction_id_generator.rs
  core/src/banking_stage/transaction_scheduler/transaction_priority_id.rs
Labels: bug

#2054 Extract signature crate
  Cargo.lock
  Cargo.toml
  core/src/consensus/tower1_7_14.rs
  core/src/consensus/tower_storage.rs
  core/src/repair/serve_repair.rs
  gossip/src/cluster_info.rs
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/signature/Cargo.toml
  sdk/signature/build.rs
  sdk/signature/src/lib.rs
  sdk/src/signature.rs
  sdk/src/transaction/mod.rs
Labels: need:merge-assist

#2369 Extract program-option crate
  Cargo.lock
  Cargo.toml
  ci/nits.sh
  programs/sbf/Cargo.lock
  sdk/program-option/Cargo.toml
  sdk/program-option/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
Labels: automerge, need:merge-assist

#2863 [docs] removing an extra character
  docs/src/implemented-proposals/rpc-transaction-history.md
Labels: community, need:merge-assist

#2394 Extract pubkey crate
  Cargo.lock
  Cargo.toml
  ci/nits.sh
  core/src/consensus.rs
  core/src/consensus/tower1_14_11.rs
  core/src/consensus/tower1_7_14.rs
  core/src/repair/serve_repair.rs
  gossip/src/cluster_info.rs
  programs/sbf/Cargo.lock
  runtime/src/bank/serde_snapshot.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/message/versions/mod.rs
  sdk/program/src/syscalls/definitions.rs
  sdk/program/src/system_instruction.rs
  sdk/program/src/vote/state/mod.rs
  sdk/program/src/vote/state/vote_state_1_14_11.rs
  sdk/program/src/wasm/mod.rs
  sdk/program/src/wasm/pubkey.rs
  sdk/pubkey/Cargo.toml
  sdk/pubkey/build.rs
  sdk/pubkey/src/lib.rs
  sdk/pubkey/src/syscalls.rs
  sdk/src/account.rs
  sdk/src/genesis_config.rs
  sdk/src/transaction/mod.rs
Labels: automerge, need:merge-assist

#2888 banking_stage: do not insert legacy vote ixs, refactor & unstaked
  core/src/banking_stage.rs
  core/src/banking_stage/forwarder.rs
  core/src/banking_stage/latest_unprocessed_votes.rs
  core/src/banking_stage/unprocessed_transaction_storage.rs
Labels: v2.0

#2904 docs: fix tonic crates.io url
  docs/src/implemented-proposals/rpc-transaction-history.md
Labels: community, need:merge-assist

#2870 Extract transaction-status-client-types
  Cargo.lock
  Cargo.toml
  ledger-tool/src/main.rs
  programs/sbf/Cargo.lock
  rpc-client-api/Cargo.toml
  rpc-client-api/src/config.rs
  rpc-client-api/src/custom_error.rs
  rpc-client-api/src/response.rs
  rpc-client/Cargo.toml
  rpc-client/src/mock_sender.rs
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
  rpc/src/rpc.rs
  sdk/Cargo.toml
  transaction-status-client-types/Cargo.toml
  transaction-status-client-types/src/lib.rs
  transaction-status-client-types/src/option_serializer.rs
  transaction-status/Cargo.toml
  transaction-status/src/lib.rs
  transaction-status/src/parse_accounts.rs
  transaction-status/src/parse_instruction.rs
Labels: automerge, need:merge-assist

#2869 Replace async-mutex with async-lock
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  quic-client/Cargo.toml
  quic-client/src/nonblocking/quic_client.rs
Labels: community, need:merge-assist

#2917 revert dockerfile and only have shell script changes (apt to apt-get)
  .github/scripts/downstream-project-spl-install-deps.sh
  ci/docker/Dockerfile
  ci/setup-new-buildkite-agent/setup-new-machine.sh
Labels: community, need:merge-assist

#2405 Extract instruction crate
  Cargo.lock
  Cargo.toml
  frozen-abi/macro/src/lib.rs
  program-test/Cargo.toml
  program-test/src/lib.rs
  programs/sbf/Cargo.lock
  runtime/src/bank.rs
  sdk/instruction/Cargo.toml
  sdk/instruction/build.rs
  sdk/instruction/src/account_meta.rs
  sdk/instruction/src/error.rs
  sdk/instruction/src/lib.rs
  sdk/instruction/src/syscalls.rs
  sdk/program/Cargo.toml
  sdk/program/src/instruction.rs
  sdk/program/src/program_error.rs
  sdk/program/src/program_stubs.rs
  sdk/program/src/syscalls/definitions.rs
  sdk/src/transaction/mod.rs
Labels: automerge, need:merge-assist

#2913 resolve `cargo check` problems with tpu-client
  tpu-client/src/nonblocking/tpu_client.rs
Labels: automerge

#2908 docs: programs.md
  docs/src/runtime/programs.md
Labels: community, need:merge-assist

#2837 OwnedOrBorrowed for TransactionBatch
  ledger/benches/blockstore_processor.rs
  ledger/src/blockstore_processor.rs
  runtime/src/bank.rs
  runtime/src/transaction_batch.rs
Labels: automerge

#2413 Extract program-error crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program-error/Cargo.toml
  sdk/program-error/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/entrypoint.rs
  sdk/program/src/program_error.rs
Labels: automerge, need:merge-assist

#2959 bump blake3 1.5.1 -> 1.5.4
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
Labels: community, need:merge-assist

#2926 extract serialize-utils crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/serialize-utils/Cargo.toml
  sdk/serialize-utils/src/cursor.rs
  sdk/serialize-utils/src/lib.rs
Labels: automerge, need:merge-assist

#2429 Extract account-info crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/account-info/Cargo.toml
  sdk/account-info/src/debug_account_data.rs
  sdk/account-info/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/entrypoint.rs
  sdk/program/src/lib.rs
Labels: automerge, need:merge-assist

#2952 Fix: Corrected the derivation command format
  docs/src/cli/wallets/paper.md
Labels: community, need:merge-assist, v2.0

#3016 reworks max number of outgoing push messages
  gossip/src/crds_gossip_push.rs
Labels: v2.0
