Repository anza-xyz/agave, pull requests merged in 2024-06, with the labels that each got.

#1558 ci: patching spl project before anchor project uses it
  scripts/build-downstream-anchor-projects.sh
Labels: automerge

#1517 chore: remove unused clippy attributes, needless_collect
  accounts-db/src/accounts.rs
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_index.rs
  gossip/src/cluster_info.rs
  gossip/src/crds.rs
  perf/src/recycler.rs
  programs/sbf/tests/programs.rs
  runtime/src/bank/fee_distribution.rs
  runtime/src/bank_forks.rs
  runtime/src/snapshot_utils.rs
  tokens/src/commands.rs
Labels: automerge

#1571 Simplify signature of Bank::load_and_execute_transactions
  core/src/banking_stage/consumer.rs
  runtime/src/bank.rs
Labels: community, need:merge-assist

#1509 Runtime: Core BPF Migration: Explicit upgrade authority checks in migration
  runtime/src/bank/builtin_programs.rs
  runtime/src/bank/builtins/core_bpf_migration/error.rs
  runtime/src/bank/builtins/core_bpf_migration/mod.rs
  runtime/src/bank/builtins/mod.rs
Labels: automerge

#1429 fix: add timeouts for bigtable connect to prevent hanging connections
  storage-bigtable/src/bigtable.rs
Labels: community, need:merge-assist

#1557 chore: bump sccache to 0.8.1
  .github/workflows/cargo.yml
  .github/workflows/downstream-project-anchor.yml
  .github/workflows/downstream-project-spl.yml
  ci/docker/Dockerfile
Labels: automerge

#1229 Update SECURITY.md
  SECURITY.md
Labels: community, need:merge-assist

#1553 ci: improve version update script
  scripts/increment-cargo-version.sh
Labels: v1.18

#1576 Make borsh optional in sdk and program crates
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/blake3.rs
  sdk/program/src/hash.rs
  sdk/program/src/instruction.rs
  sdk/program/src/keccak.rs
  sdk/program/src/lib.rs
  sdk/program/src/program_error.rs
  sdk/program/src/pubkey.rs
  sdk/program/src/secp256k1_recover.rs
  sdk/program/src/serialize_utils/cursor.rs
  sdk/program/src/stake/stake_flags.rs
  sdk/program/src/stake/state.rs
  sdk/src/compute_budget.rs
  sdk/src/lib.rs
Labels: need:merge-assist

#1633 sdk: Remove borsh usage from Pubkey test
  sdk/program/src/pubkey.rs
Labels: automerge

#1232 Update requirements.md
  docs/src/operations/requirements.md
Labels: community, need:merge-assist

#1657 Re-export curve25519-dalek from solana-zk-token-sdk
  zk-token-sdk/src/lib.rs
Labels: community, need:merge-assist

#1681 Update patch paths for tokio, crossbeam, and curve25519-dalek
  Cargo.lock
  Cargo.toml
Labels: automerge

#1680 Prepare unlocked batch from single tx - reduce alloc
  runtime/src/bank.rs
Labels: automerge

#1622 SDK: Slot Hashes: Add queries using `sol_get_sysvar`
  sdk/program/src/sysvar/mod.rs
  sdk/program/src/sysvar/slot_hashes.rs
Labels: automerge

#1391 SVM: change modified programs result to hash map
  Cargo.lock
  accounts-db/Cargo.toml
  accounts-db/src/accounts.rs
  program-runtime/src/loaded_programs.rs
  programs/sbf/Cargo.lock
  runtime/src/bank/builtins/core_bpf_migration/mod.rs
  runtime/src/bank/tests.rs
  svm/src/transaction_processor.rs
  svm/src/transaction_results.rs
Labels: automerge

#1718 ci: print spl commit hash for downstream tests
  .github/scripts/downstream-project-spl-common.sh
  .github/workflows/downstream-project-spl.yml
Labels: automerge

#1669 remove superfluous usage of allow(dead_code)
  cargo-registry/src/crate_handler.rs
  core/src/banking_stage/transaction_scheduler/in_flight_tracker.rs
  ledger/src/blockstore.rs
  metrics/src/metrics.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/sbf/tests/programs.rs
  remote-wallet/src/remote_wallet.rs
  rpc/src/rpc_service.rs
  sdk/macro/src/lib.rs
  sdk/program/src/log.rs
Labels: need:merge-assist

#1637 rpc: add more services to getClusterNodes
  rpc-client-api/src/response.rs
  rpc-client/src/mock_sender.rs
  rpc/src/rpc.rs
Labels: need:merge-assist

#1659 remove unused build dep `cc` from solana-program
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
Labels: need:merge-assist

#1570 refactor: clean up geyser-plugin-manager
  geyser-plugin-manager/src/accounts_update_notifier.rs
Labels: community, need:merge-assist

#1765 ci: upgrade client-traget macos version
  .github/workflows/client-targets.yml
Labels: automerge

#1768 Simd-118: [HAL-02] add lamports burned to error log
  runtime/src/bank/partitioned_epoch_rewards/distribution.rs
Labels: automerge

#1767 Simd-118: [HAL-01] add log to unreachable macro
  runtime/src/bank/partitioned_epoch_rewards/distribution.rs
Labels: automerge

#1753 run full gossip node when running `solana-gossip rpc-url`
  gossip/src/main.rs
Labels: automerge

#951 Extract curve25519 crate from zk-token-sdk
  Cargo.lock
  Cargo.toml
  curves/curve25519/.gitignore
  curves/curve25519/Cargo.toml
  curves/curve25519/src/curve_syscall_traits.rs
  curves/curve25519/src/edwards.rs
  curves/curve25519/src/errors.rs
  curves/curve25519/src/lib.rs
  curves/curve25519/src/ristretto.rs
  curves/curve25519/src/scalar.rs
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/syscalls/mod.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/rust/curve25519/Cargo.toml
  programs/sbf/rust/curve25519/src/lib.rs
  zk-token-sdk/Cargo.toml
  zk-token-sdk/src/curve25519/errors.rs
  zk-token-sdk/src/curve25519/mod.rs
  zk-token-sdk/src/encryption/elgamal.rs
  zk-token-sdk/src/errors.rs
  zk-token-sdk/src/lib.rs
  zk-token-sdk/src/zk_token_elgamal/convert.rs
  zk-token-sdk/src/zk_token_elgamal/ops.rs
  zk-token-sdk/src/zk_token_elgamal/pod/elgamal.rs
  zk-token-sdk/src/zk_token_elgamal/pod/grouped_elgamal.rs
  zk-token-sdk/src/zk_token_elgamal/pod/instruction.rs
  zk-token-sdk/src/zk_token_elgamal/pod/pedersen.rs
Labels: community, need:merge-assist

#1658 Only compile wasm-bindgen when target_arch = "wasm32"
  sdk/Cargo.toml
  sdk/macro/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/hash.rs
  sdk/program/src/instruction.rs
  sdk/program/src/lib.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/pubkey.rs
  sdk/src/lib.rs
  sdk/src/signer/keypair.rs
  sdk/src/transaction/mod.rs
Labels: need:merge-assist

#1748 remove double-counted metric
  accounts-db/src/ancient_append_vecs.rs
Labels: automerge

#1750 add ancient pack metrics
  accounts-db/src/accounts_db.rs
  accounts-db/src/ancient_append_vecs.rs
Labels: automerge

#1782 program: move itertools to dev-dependencies
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
  sdk/program/src/program_stubs.rs
Labels: need:merge-assist

#1793 use bytemuck_derive 1.7.0 explicitly in sdk and program
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/alt_bn128/mod.rs
  sdk/program/src/hash.rs
  sdk/program/src/pubkey.rs
  sdk/program/src/sysvar/slot_hashes.rs
  sdk/src/ed25519_instruction.rs
  zk-sdk/Cargo.toml
Labels: need:merge-assist

#1795 typo fixes
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_db/geyser_plugin_utils.rs
  accounts-db/src/ancient_append_vecs.rs
  accounts-db/src/bucket_map_holder.rs
  accounts-db/src/buffered_reader.rs
Labels: community, need:merge-assist

#1805 Fix SyscallLogPubkey doc comment
  programs/bpf_loader/src/syscalls/logging.rs
Labels: community, need:merge-assist

#1700 Reuse compute budget processing
  Cargo.lock
  accounts-db/Cargo.toml
  accounts-db/src/accounts.rs
  compute-budget/src/compute_budget.rs
  compute-budget/src/compute_budget_processor.rs
  core/src/banking_stage/consume_worker.rs
  program-runtime/src/timings.rs
  svm/src/account_loader.rs
  svm/src/transaction_error_metrics.rs
  svm/src/transaction_processor.rs
Labels: automerge

#1802 add stats for ancient bytes_from_newest_storages
  accounts-db/src/accounts_db.rs
  accounts-db/src/ancient_append_vecs.rs
Labels: automerge

#1828 chore: remove publish=false from transaction-metrics-tracker/Cargo.toml
  transaction-metrics-tracker/Cargo.toml
Labels: v2.0

#1845 chore: publish solana-tps-client
  tps-client/Cargo.toml
Labels: v2.0

#1864 Add partitioned epoch rewards to changelog for v2.0
  CHANGELOG.md
Labels: v2.0

#1668 Make unified scheduler opt-in for block verification
  ledger-tool/src/main.rs
  unified-scheduler-pool/src/lib.rs
  validator/src/cli.rs
Labels: v2.0

#1667 remove respan macro
  CHANGELOG.md
  sdk/macro/src/lib.rs
  sdk/src/lib.rs
Labels: automerge, need:merge-assist

#1872 spl: Upgrade all crates to v2-only versions
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
Labels: v2.0

#1677 Use num_partitions to find specific stake rewards in partitions
  rpc-client-api/src/custom_error.rs
  rpc/src/rpc.rs
  validator/src/bin/solana-test-validator.rs
Labels: v2.0

#1809 Remove support for deprecated rpc endpoints
  CHANGELOG.md
  rpc-test/tests/rpc.rs
  rpc/src/rpc.rs
  rpc/src/rpc_service.rs
  validator/src/cli.rs
  validator/src/main.rs
Labels: v2.0

#1887 accounts-db/add counter for reopen append vec as file-io
  accounts-db/src/accounts_db.rs
  accounts-db/src/append_vec.rs
Labels: automerge

#1888 Refactor and additional metrics for cost tracking
  Cargo.lock
  core/benches/consumer.rs
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/qos_service.rs
  cost-model/src/cost_model.rs
  ledger/src/blockstore_processor.rs
  local-cluster/tests/local_cluster.rs
  program-runtime/Cargo.toml
  program-runtime/src/timings.rs
  programs/sbf/Cargo.lock
  svm/src/transaction_processor.rs
Labels: automerge, v2.0

#1902 Remove deprecated SyncClient methods
  CHANGELOG.md
  client/src/thin_client.rs
  runtime/src/bank_client.rs
  sdk/src/client.rs
  thin-client/src/thin_client.rs
Labels: v2.0

#1905 Add since field to deprecation note
  rpc-client-api/src/filter.rs
Labels: v2.0

#1906 vote: remove deprecated ixs
  sdk/program/src/vote/instruction.rs
Labels: v2.0

#1920 hash-cache-tool: Refactors file scanning
  accounts-db/accounts-hash-cache-tool/src/main.rs
Labels: automerge

#1899 Remove deprecated RpcClient methods
  CHANGELOG.md
  cli/src/cli.rs
  cli/src/cluster_query.rs
  rpc-client-api/src/request.rs
  rpc-client-nonce-utils/src/blockhash_query.rs
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
  test-validator/src/lib.rs
Labels: v2.0

#1895 Deprecate RpcClient::get_stake_activation
  cli/tests/stake.rs
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
Labels: v1.18, v2.0

#1707 Pull sanitize crate out of solana-program
  Cargo.lock
  Cargo.toml
  bloom/Cargo.toml
  bloom/src/bloom.rs
  core/Cargo.toml
  core/src/banking_stage/immutable_deserialized_packet.rs
  gossip/Cargo.toml
  gossip/src/cluster_info.rs
  gossip/src/contact_info.rs
  gossip/src/crds_gossip_pull.rs
  gossip/src/crds_value.rs
  gossip/src/duplicate_shred.rs
  gossip/src/epoch_slots.rs
  gossip/src/legacy_contact_info.rs
  gossip/src/ping_pong.rs
  gossip/src/restart_crds_values.rs
  programs/sbf/Cargo.lock
  sanitize/Cargo.toml
  sanitize/src/lib.rs
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/blake3.rs
  sdk/program/src/hash.rs
  sdk/program/src/instruction.rs
  sdk/program/src/keccak.rs
  sdk/program/src/lib.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/message/sanitized.rs
  sdk/program/src/message/versions/mod.rs
  sdk/program/src/message/versions/sanitized.rs
  sdk/program/src/message/versions/v0/mod.rs
  sdk/program/src/pubkey.rs
  sdk/program/src/serialize_utils/mod.rs
  sdk/program/src/sysvar/instructions.rs
  sdk/src/lib.rs
  sdk/src/offchain_message.rs
  sdk/src/signature.rs
  sdk/src/transaction/error.rs
  sdk/src/transaction/mod.rs
  sdk/src/transaction/sanitized.rs
  sdk/src/transaction/versioned/mod.rs
  sdk/src/transaction/versioned/sanitized.rs
  version/Cargo.toml
  version/src/legacy.rs
  version/src/lib.rs
Labels: automerge, need:merge-assist

#1415 stake-program: `MoveStake` and `MoveLamports`
  Cargo.lock
  Cargo.toml
  programs/stake-tests/Cargo.toml
  programs/stake-tests/tests/test_move_stake_and_lamports.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  sdk/program/src/stake/instruction.rs
  sdk/src/feature_set.rs
  transaction-status/src/parse_stake.rs
Labels: feature-gate, v2.0

#1755 docs: Update that the Tour De Sun 22 is now closed
  docs/src/operations/validator-initiatives.md
Labels: community, need:merge-assist
