Repository anza-xyz/agave, pull requests merged in 2024-12, with the labels that each got.

#3847 chore: remove redundant words in comment
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_db/geyser_plugin_utils.rs
  docs/static/katex/katex.js
  docs/static/katex/katex.mjs
  dos/src/main.rs
  ledger/src/blockstore_meta.rs
  sdk/src/transaction/mod.rs
  streamer/src/nonblocking/quic.rs
Labels: community, need:merge-assist

#3794 Add set_identity tests
  validator/src/admin_rpc_service.rs
Labels: automerge

#3852 Update deploy-a-program.md
  docs/src/cli/examples/deploy-a-program.md
Labels: community, need:merge-assist

#3704 Extract message crate
  Cargo.lock
  Cargo.toml
  gossip/src/protocol.rs
  programs/sbf/Cargo.lock
  sdk/message/Cargo.toml
  sdk/message/src/account_keys.rs
  sdk/message/src/address_loader.rs
  sdk/message/src/compiled_instruction.rs
  sdk/message/src/compiled_keys.rs
  sdk/message/src/legacy.rs
  sdk/message/src/lib.rs
  sdk/message/src/sanitized.rs
  sdk/message/src/versions/mod.rs
  sdk/message/src/versions/sanitized.rs
  sdk/message/src/versions/v0/loaded.rs
  sdk/message/src/versions/v0/mod.rs
  sdk/program/Cargo.toml
  sdk/program/src/address_lookup_table/mod.rs
  sdk/program/src/instruction.rs
  sdk/program/src/lib.rs
  sdk/src/transaction/mod.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3698 README: Link to `docs/src/cli/install.md` to build and install for production
  README.md
Labels: community, need:merge-assist

#3515 use tpu-client-next in send_transaction_service
  Cargo.lock
  banks-server/src/banks_server.rs
  programs/sbf/Cargo.lock
  rpc/src/cluster_tpu_info.rs
  rpc/src/rpc.rs
  rpc/src/rpc_service.rs
  send-transaction-service/Cargo.toml
  send-transaction-service/src/lib.rs
  send-transaction-service/src/send_transaction_service.rs
  send-transaction-service/src/test_utils.rs
  send-transaction-service/src/tpu_info.rs
  send-transaction-service/src/transaction_client.rs
  svm/examples/Cargo.lock
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/quic_networking.rs
  tpu-client-next/src/quic_networking/quic_client_certificate.rs
  tpu-client-next/tests/connection_workers_scheduler_test.rs
Labels: v2.1

#3843 remove solana-sdk from solana-net-utils
  Cargo.lock
  net-utils/Cargo.toml
  net-utils/src/ip_echo_server.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3836 [streamer] Fix musl build
  streamer/src/recvmmsg.rs
  streamer/src/sendmmsg.rs
Labels: community, need:merge-assist

#3874 move program::wasm::instructions to instruction crate
  sdk/instruction/src/lib.rs
  sdk/instruction/src/wasm.rs
  sdk/program/src/wasm/mod.rs
Labels: automerge, need:merge-assist

#3783 Adding additional logging when overflow occurs in calculate_stake_rew…
  programs/stake/src/rewards.rs
Labels: automerge, community, need:merge-assist

#3886 Update CHANGELOG.md
  CHANGELOG.md
Labels: community, need:merge-assist

#3901 sdk: Add wasm target for docs
  sdk/Cargo.toml
  sdk/hash/Cargo.toml
  sdk/instruction/Cargo.toml
  sdk/keypair/Cargo.toml
  sdk/message/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/pubkey/Cargo.toml
  sdk/src/lib.rs
Labels: automerge

#3854 remove solana-sdk from svm-transaction
  Cargo.lock
  programs/sbf/Cargo.lock
  svm-transaction/Cargo.toml
  svm-transaction/src/instruction.rs
  svm-transaction/src/message_address_table_lookup.rs
  svm-transaction/src/svm_message.rs
  svm-transaction/src/svm_message/sanitized_message.rs
  svm-transaction/src/svm_message/sanitized_transaction.rs
  svm-transaction/src/svm_transaction.rs
  svm-transaction/src/svm_transaction/sanitized_transaction.rs
  svm-transaction/src/tests.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#2808 Add support for Ledger Flex
  remote-wallet/src/ledger.rs
Labels: community, need:merge-assist

#3799 Fix reserve minimal compute units for builtins
  builtins-default-costs/src/lib.rs
  compute-budget/src/compute_budget_limits.rs
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/immutable_deserialized_packet.rs
  core/src/banking_stage/transaction_scheduler/receive_and_buffer.rs
  cost-model/src/cost_model.rs
  cost-model/src/transaction_cost.rs
  programs/compute-budget-bench/benches/compute_budget.rs
  programs/sbf/tests/programs.rs
  runtime-transaction/benches/process_compute_budget_instructions.rs
  runtime-transaction/src/builtin_programs_filter.rs
  runtime-transaction/src/compute_budget_instruction_details.rs
  runtime-transaction/src/compute_budget_program_id_filter.rs
  runtime-transaction/src/instructions_processor.rs
  runtime-transaction/src/lib.rs
  runtime-transaction/src/runtime_transaction.rs
  runtime-transaction/src/runtime_transaction/sdk_transactions.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  runtime/src/prioritization_fee_cache.rs
  sdk/feature-set/src/lib.rs
  sdk/message/src/sanitized.rs
  sdk/message/src/versions/sanitized.rs
  svm-transaction/src/svm_message.rs
  svm-transaction/src/svm_message/sanitized_message.rs
  svm-transaction/src/svm_message/sanitized_transaction.rs
  svm/src/transaction_processor.rs
  transaction-view/src/resolved_transaction_view.rs
  transaction-view/src/transaction_view.rs
Labels: feature-gate

#3831 remove solana-sdk from transaction-status-client-types
  Cargo.lock
  programs/sbf/Cargo.lock
  rpc-client-api/Cargo.toml
  svm/examples/Cargo.lock
  transaction-status-client-types/Cargo.toml
  transaction-status-client-types/src/lib.rs
Labels: automerge, need:merge-assist

#3904 remove solana-program from solana-precompiles
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/precompiles/Cargo.toml
  sdk/precompiles/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3905 remove solana-program from solana-fee-structure
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/fee-structure/Cargo.toml
  sdk/fee-structure/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3907 remove solana-program from solana-reserved-account-keys dev deps
  Cargo.lock
  sdk/reserved-account-keys/Cargo.toml
  sdk/reserved-account-keys/src/lib.rs
Labels: need:merge-assist

#3942 remove solana-program from solana-signature dev deps
  Cargo.lock
  sdk/signature/Cargo.toml
  sdk/signature/src/lib.rs
Labels: automerge, need:merge-assist

#3829 Extract client-traits crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/client-traits/Cargo.toml
  sdk/client-traits/src/lib.rs
  sdk/src/lib.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3855 extract poh-config crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/poh-config/Cargo.toml
  sdk/poh-config/src/lib.rs
  sdk/src/genesis_config.rs
  sdk/src/lib.rs
  sdk/src/poh_config.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3941 ed25519_verify_cpu: remove allocation in hot path
  perf/src/sigverify.rs
Labels: v2.1

#3120 Extract solana-feature crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/feature-gate-interface/Cargo.toml
  sdk/feature-gate-interface/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3892 remove unused direct deps from solana-program
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3842 remove solana-sdk from tpu-client
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  tpu-client/Cargo.toml
  tpu-client/src/nonblocking/tpu_client.rs
  tpu-client/src/tpu_client.rs
Labels: need:merge-assist

#3841 remove solana-sdk from thin-client
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  thin-client/Cargo.toml
  thin-client/src/thin_client.rs
Labels: need:merge-assist

#3751 feat: deplete compute meter for vm errors
  programs/bpf_loader/src/lib.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/rust/divide_by_zero/Cargo.toml
  programs/sbf/rust/divide_by_zero/src/lib.rs
  programs/sbf/tests/programs.rs
  sdk/feature-set/src/lib.rs
Labels: feature-gate

#3963 update number of return values for `process_transaction_and_record_inner`
  programs/sbf/tests/programs.rs
Labels: automerge

#3440 remove solana-sdk from rpc-client-nonce-utils
  Cargo.lock
  programs/sbf/Cargo.lock
  rpc-client-nonce-utils/Cargo.toml
  rpc-client-nonce-utils/src/blockhash_query.rs
  rpc-client-nonce-utils/src/lib.rs
  rpc-client-nonce-utils/src/nonblocking/blockhash_query.rs
  rpc-client-nonce-utils/src/nonblocking/mod.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3923 use create_and_canonicalize_directory for snapshots dir
  validator/src/main.rs
Labels: v2.1

#31 send-transactions: optimize retry pool
  send-transaction-service/src/send_transaction_service.rs
Labels: community, need:merge-assist

#3977 bump solana docker image's based image to bookworm
  sdk/docker-solana/Dockerfile
Labels: v2.1

#3833 remove solana-sdk from rpc-client
  Cargo.lock
  programs/sbf/Cargo.lock
  rpc-client-nonce-utils/Cargo.toml
  rpc-client/Cargo.toml
  rpc-client/src/mock_sender.rs
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3731 remove solana-sdk from solana-timings
  Cargo.lock
  core/src/banking_stage/consumer.rs
  ledger/src/blockstore_processor.rs
  program-runtime/src/invoke_context.rs
  program-runtime/src/loaded_programs.rs
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/loader-v4/src/lib.rs
  programs/sbf/Cargo.lock
  runtime/src/bank.rs
  svm/examples/Cargo.lock
  svm/src/message_processor.rs
  svm/src/transaction_processor.rs
  svm/tests/integration_test.rs
  timings/Cargo.toml
  timings/src/lib.rs
  unified-scheduler-pool/src/lib.rs
Labels: automerge, need:merge-assist

#3973 remove solana-program and solana-sdk from solana-perf
  Cargo.lock
  perf/Cargo.toml
  perf/src/packet.rs
  perf/src/sigverify.rs
  perf/src/test_tx.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3924 remove solana-sdk from program-runtime
  Cargo.lock
  program-runtime/Cargo.toml
  program-runtime/src/invoke_context.rs
  program-runtime/src/lib.rs
  program-runtime/src/loaded_programs.rs
  program-runtime/src/stable_log.rs
  program-runtime/src/sysvar_cache.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3954 ledger: Replace saturating_add_assign with Saturating<T>
  ledger/src/blockstore_processor.rs
Labels: community, need:merge-assist

#3443 Extract offchain-message crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/offchain-message/Cargo.toml
  sdk/offchain-message/src/lib.rs
  sdk/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3999 remove solana-sdk from builtins-default-costs
  Cargo.lock
  builtins-default-costs/Cargo.toml
  builtins-default-costs/benches/builtin_instruction_costs.rs
  builtins-default-costs/src/lib.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3844 remove solana-sdk from solana-client
  Cargo.lock
  client/Cargo.toml
  client/src/connection_cache.rs
  client/src/nonblocking/tpu_client.rs
  client/src/send_and_confirm_transactions_in_parallel.rs
  client/src/thin_client.rs
  client/src/tpu_client.rs
  client/src/transaction_executor.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3998 remove solana-sdk from solana-entry
  Cargo.lock
  entry/Cargo.toml
  entry/benches/entry_sigverify.rs
  entry/src/entry.rs
  entry/src/poh.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4000 remove solana-sdk from solana-keygen
  Cargo.lock
  keygen/Cargo.toml
  keygen/src/keygen.rs
Labels: need:merge-assist

#4002 remove solana-sdk from zk-keygen
  Cargo.lock
  zk-keygen/Cargo.toml
  zk-keygen/src/main.rs
Labels: need:merge-assist

#3991 remove solana-sdk from transaction-metrics-tracker dev deps
  Cargo.lock
  transaction-metrics-tracker/Cargo.toml
  transaction-metrics-tracker/src/lib.rs
Labels: need:merge-assist

#4001 remove solana-sdk from solana-faucet
  Cargo.lock
  faucet/Cargo.toml
  faucet/src/bin/faucet.rs
  faucet/src/faucet.rs
  faucet/src/faucet_mock.rs
  faucet/tests/local-faucet.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4003 remove solana-sdk from quic-client dev deps
  Cargo.lock
  quic-client/Cargo.toml
  quic-client/tests/quic_client.rs
Labels: need:merge-assist

#4014 fix audit
  ci/do-audit.sh
Labels: v2.0, v2.1

#4009 remove solana-sdk from tpu-client-next
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  tpu-client-next/Cargo.toml
  tpu-client-next/src/connection_worker.rs
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/leader_updater.rs
  tpu-client-next/src/quic_networking.rs
  tpu-client-next/src/transaction_batch.rs
  tpu-client-next/tests/connection_workers_scheduler_test.rs
Labels: need:merge-assist

#4037 remove solana-sdk from solana-system-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/system/Cargo.toml
  programs/system/benches/system.rs
  programs/system/src/lib.rs
  programs/system/src/system_instruction.rs
  programs/system/src/system_processor.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3629 remove solana-sdk from solana-remote-wallet
  Cargo.lock
  clap-v3-utils/Cargo.toml
  faucet/Cargo.toml
  programs/sbf/Cargo.lock
  remote-wallet/Cargo.toml
  remote-wallet/src/ledger.rs
  remote-wallet/src/locator.rs
  remote-wallet/src/remote_keypair.rs
  remote-wallet/src/remote_wallet.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4036 extract nonce-account crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/nonce-account/Cargo.toml
  sdk/nonce-account/src/lib.rs
  sdk/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4054 remove solana-sdk from solana-zk-elgamal-proof-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/zk-elgamal-proof/Cargo.toml
  programs/zk-elgamal-proof/src/lib.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4055 remove solana-sdk from zk-token-proof
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/zk-token-proof/Cargo.toml
  programs/zk-token-proof/src/lib.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4057 remove solana-sdk from compute-budget-bench
  Cargo.lock
  programs/compute-budget-bench/Cargo.toml
  programs/compute-budget-bench/benches/compute_budget.rs
Labels: need:merge-assist

#4056 remove solana-sdk from zk-token-proof-tests
  Cargo.lock
  programs/zk-token-proof-tests/Cargo.toml
  programs/zk-token-proof-tests/tests/process_transaction.rs
Labels: need:merge-assist

#4059 local-cluster: ignore flaky OC tests
  local-cluster/tests/local_cluster.rs
Labels: automerge

#4029 Removing saturating_add_assign and replacing with Saturating struct
  core/src/banking_stage/consume_worker.rs
  core/src/banking_stage/leader_slot_metrics.rs
  runtime/src/bank.rs
  svm/examples/json-rpc/server/src/rpc_process.rs
  svm/src/account_loader.rs
  svm/src/transaction_error_metrics.rs
  svm/src/transaction_processor.rs
Labels: community, need:merge-assist

#3994 use new feature gate for cu depletion
  programs/bpf_loader/src/lib.rs
  programs/sbf/tests/programs.rs
  sdk/feature-set/src/lib.rs
Labels: feature-gate, v2.0, v2.1

#4026 SIMD-0207: Raise block limit to 50M
  cost-model/src/block_cost_limits.rs
  cost-model/src/cost_tracker.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  sdk/feature-set/src/lib.rs
Labels: v2.0, v2.1

#4071 Correct a typo: mistmatch -> mismatch
  core/src/validator.rs
Labels: community, need:merge-assist

#4080 Apply misc small cleanups to unified scheduler
  core/src/banking_simulation.rs
  runtime/src/bank_forks.rs
  unified-scheduler-pool/src/lib.rs
Labels: automerge

#3975 Accounting migrating builtin programs default Compute Unit Limit with feature status
  Cargo.lock
  builtins-default-costs/Cargo.toml
  builtins-default-costs/src/lib.rs
  compute-budget-instruction/Cargo.toml
  compute-budget-instruction/src/builtin_programs_filter.rs
  compute-budget-instruction/src/compute_budget_instruction_details.rs
Labels: automerge

#4070 Removing all uses of saturating_add_assign from leader_slot_timing_met…
  core/src/banking_stage/leader_slot_metrics.rs
  core/src/banking_stage/leader_slot_timing_metrics.rs
Labels: automerge, community, need:merge-assist

#4110 Revert "SIMD-0207: Raise block limit to 50M (#4026)"
  cost-model/src/block_cost_limits.rs
  cost-model/src/cost_tracker.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  sdk/feature-set/src/lib.rs
Labels: automerge

#4147 Fixes clean_old_storages_with_reclaims tests
  accounts-db/src/accounts_db/tests.rs
Labels: automerge

#4061 chore(cargo-build-sbf): allow building from nix store
  sdk/cargo-build-sbf/src/main.rs
Labels: community, need:merge-assist

#3895 extract validator-exit crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/src/lib.rs
  sdk/validator-exit/Cargo.toml
  sdk/validator-exit/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3927 Only permit X25519 based QUIC-TLS key exchanges
  Cargo.toml
  core/src/repair/quic_endpoint.rs
  quic-client/src/nonblocking/quic_client.rs
  streamer/src/nonblocking/testing_utilities.rs
  streamer/src/quic.rs
  tls-utils/src/config.rs
  tls-utils/src/crypto_provider.rs
  tls-utils/src/lib.rs
  tls-utils/src/skip_client_verification.rs
  tls-utils/src/skip_server_verification.rs
  tpu-client-next/src/quic_networking.rs
  turbine/src/quic_endpoint.rs
Labels: community, need:merge-assist

#4103 geyser: add flag `geyser-plugin-snapshot-disabled`
  accounts-db/src/accounts_db/geyser_plugin_utils.rs
  accounts-db/src/accounts_update_notifier_interface.rs
  geyser-plugin-interface/src/geyser_plugin_interface.rs
  geyser-plugin-manager/src/accounts_update_notifier.rs
  geyser-plugin-manager/src/geyser_plugin_manager.rs
  geyser-plugin-manager/src/geyser_plugin_service.rs
Labels: need:merge-assist

#4172 minimize solana-sdk usage in svm/src
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/Cargo.toml
  svm/examples/Cargo.lock
  svm/src/account_loader.rs
  svm/src/account_overrides.rs
  svm/src/message_processor.rs
  svm/src/nonce_info.rs
  svm/src/program_loader.rs
  svm/src/rollback_accounts.rs
  svm/src/transaction_account_state_info.rs
  svm/src/transaction_commit_result.rs
  svm/src/transaction_execution_result.rs
  svm/src/transaction_processing_callback.rs
  svm/src/transaction_processing_result.rs
  svm/src/transaction_processor.rs
Labels: automerge, need:merge-assist

#4193 Removes unnecessary casts in datapoints
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_db/stats.rs
Labels: automerge

#4173 remove solana-sdk from tps-client
  Cargo.lock
  tps-client/Cargo.toml
  tps-client/src/bank_client.rs
  tps-client/src/lib.rs
  tps-client/src/rpc_client.rs
  tps-client/src/tpu_client.rs
  tps-client/src/utils.rs
Labels: automerge, need:merge-assist

#4140 fix: typos in documentation files
  docs/src/operations/best-practices/security.md
Labels: community, need:merge-assist

#4221 ci: Exclude `avm` from Anchor downstream project tests
  scripts/build-downstream-anchor-projects.sh
Labels: community, need:merge-assist

#4207 update doc
  svm/doc/spec.md
Labels: community, need:merge-assist

#4163 feat(ledger): add support for Ledger Stax
  remote-wallet/src/ledger.rs
Labels: community, need:merge-assist

#4174 remove solana-sdk from transaction-view
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  transaction-view/Cargo.toml
  transaction-view/benches/bytes.rs
  transaction-view/benches/transaction_view.rs
  transaction-view/src/address_table_lookup_frame.rs
  transaction-view/src/bytes.rs
  transaction-view/src/instructions_frame.rs
  transaction-view/src/message_header_frame.rs
  transaction-view/src/resolved_transaction_view.rs
  transaction-view/src/sanitize.rs
  transaction-view/src/signature_frame.rs
  transaction-view/src/static_account_keys_frame.rs
  transaction-view/src/transaction_frame.rs
  transaction-view/src/transaction_view.rs
Labels: automerge, need:merge-assist
