Repository anza-xyz/agave, pull requests merged in 2024-04, with the labels that each got.

#506 rework account load with check_and_get_loaded_account_shared_data
  accounts-db/src/accounts_db.rs
Labels: automerge

#447 Rename append vec to accounts file for CurrentAncientAppendVec
  accounts-db/src/accounts_db.rs
  runtime/src/serde_snapshot/tests.rs
Labels: community, need:merge-assist

#457 [TieredStorage] enum-based AccountsFileProvider
  accounts-db/src/account_storage.rs
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_file.rs
  accounts-db/src/sorted_storages.rs
Labels: automerge, community, need:merge-assist

#74 [TieredStorage] Make TieredStorage's Offset compatible with AccountsDB's offset
  accounts-db/src/account_info.rs
  accounts-db/src/accounts_file.rs
Labels: community, need:merge-assist

#520 Move sysvar submodule; reorg partitioned epoch rewards runtime code, 2 of 5
  runtime/src/bank.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
  runtime/src/bank/partitioned_epoch_rewards/sysvar.rs
  runtime/src/bank/tests.rs
Labels: automerge

#534 Support running miri in ci
  ci/buildkite-pipeline.sh
  ci/docker/Dockerfile
  ci/test-miri.sh
Labels: automerge

#526 cli: Customize max sign attempts for deploy and write-buffer
  CHANGELOG.md
  cli/src/program.rs
  cli/tests/program.rs
  transaction-dos/src/main.rs
Labels: v1.18

#344 Enable accountsdb_scan_account_storage_no_bank tests for hot storage
  accounts-db/src/accounts_db.rs
Labels: community, need:merge-assist

#519 Recompute hash on load if default hash is stored for the account
  accounts-db/src/accounts_db.rs
Labels: v1.18

#503 Archives storages directly
  accounts-db/src/accounts_file.rs
  accounts-db/src/append_vec.rs
  accounts-db/src/tiered_storage/hot.rs
  accounts-db/src/tiered_storage/readable.rs
  runtime/src/snapshot_utils.rs
Labels: automerge

#294 Simd 129: alt_bn128 syscalls - simplified error code
  programs/bpf_loader/src/syscalls/mod.rs
  sdk/program/src/alt_bn128/compression.rs
  sdk/program/src/alt_bn128/mod.rs
  sdk/program/src/poseidon.rs
Labels: community, need:merge-assist

#208 add serialization to AeKey
  zk-token-sdk/src/encryption/auth_encryption.rs
Labels: community, need:merge-assist

#570 Bump h2
  Cargo.lock
  programs/sbf/Cargo.lock
Labels: automerge

#553 Move remaining bits; partitioned epoch-rewards reorg, 5 of 5
  runtime/src/bank.rs
  runtime/src/bank/partitioned_epoch_rewards/calculation.rs
  runtime/src/bank/partitioned_epoch_rewards/compare.rs
  runtime/src/bank/partitioned_epoch_rewards/distribution.rs
  runtime/src/bank/partitioned_epoch_rewards/epoch_rewards_hasher.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
  runtime/src/bank/tests.rs
  runtime/src/lib.rs
Labels: automerge

#470 ff cleanup: reduce_stake_warmup_cooldown
  programs/stake/src/stake_instruction.rs
  sdk/program/src/stake/instruction.rs
Labels: automerge

#246 ElGamal: add From impls; deprecate from/to_bytes
  zk-token-sdk/src/encryption/elgamal.rs
  zk-token-sdk/src/instruction/batched_grouped_ciphertext_validity.rs
  zk-token-sdk/src/instruction/ciphertext_ciphertext_equality.rs
  zk-token-sdk/src/instruction/ciphertext_commitment_equality.rs
  zk-token-sdk/src/instruction/grouped_ciphertext_validity.rs
  zk-token-sdk/src/instruction/pubkey_validity.rs
  zk-token-sdk/src/instruction/withdraw.rs
  zk-token-sdk/src/instruction/zero_balance.rs
  zk-token-sdk/src/sigma_proofs/ciphertext_commitment_equality_proof.rs
  zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof.rs
  zk-token-sdk/src/sigma_proofs/zero_balance_proof.rs
  zk-token-sdk/src/zk_token_elgamal/pod/elgamal.rs
Labels: community, need:merge-assist

#419 Fix - `FailedVerification` and `Closed` tombstones
  ledger-tool/src/program.rs
  program-runtime/src/loaded_programs.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  svm/src/transaction_processor.rs
Labels: v1.18

#600 Show staked vs nonstaked packets sent down/throttled
  streamer/src/nonblocking/quic.rs
  streamer/src/quic.rs
Labels: v1.17, v1.18

#380 feat: include replaced blockhash in RPC simulation response
  rpc-client-api/src/response.rs
  rpc-client/src/mock_sender.rs
  rpc-test/tests/rpc.rs
  rpc/src/rpc.rs
Labels: community, need:merge-assist

#623 changelog: add entry for new simulate tx replacement blockhash
  CHANGELOG.md
Labels: changelog

#680 Fixes typo in validator requirements
  docs/src/operations/requirements.md
Labels: automerge, community, need:merge-assist

#685 BankingStage Forwarding Filter
  bench-streamer/src/main.rs
  core/src/banking_stage/forwarder.rs
  core/src/fetch_stage.rs
  core/src/repair/ancestor_hashes_service.rs
  core/src/repair/serve_repair_service.rs
  core/src/shred_fetch_stage.rs
  gossip/src/gossip_service.rs
  local-cluster/tests/local_cluster.rs
  sdk/src/packet.rs
  streamer/src/nonblocking/quic.rs
  streamer/src/streamer.rs
Labels: automerge, v1.17, v1.18

#710 program-test: move test-case to dev-dependencies
  program-test/Cargo.toml
  programs/sbf/Cargo.lock
Labels: automerge, community, need:merge-assist

#711 svm: move bpf-loader-program to dev-dependencies
  programs/sbf/Cargo.lock
  svm/Cargo.toml
Labels: automerge, community, need:merge-assist

#715 Fix crash if vote state is malformed
  sdk/program/src/vote/state/mod.rs
Labels: community, need:merge-assist

#719 blockstore: scaffolding for chained merkle root conflict detection
  core/src/window_service.rs
  ledger/src/blockstore.rs
  ledger/src/blockstore_db.rs
  ledger/src/blockstore_meta.rs
  ledger/src/shred.rs
  sdk/src/feature_set.rs
Labels: automerge, v1.18

#736 quic: do ordered reads, save 1 BTreeMap allocation per packet
  streamer/src/nonblocking/quic.rs
Labels: v1.17, v1.18

#735 quic: use smallvec to aggregate chunks, save 1 alloc per packet
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  streamer/Cargo.toml
  streamer/src/nonblocking/quic.rs
Labels: v1.17, v1.18

#730 Don't panic vote program if epoch number overflows
  programs/vote/src/vote_state/mod.rs
Labels: automerge, community, need:merge-assist

#690 move ThreadExecuteTimings to solana-ledger
  Cargo.lock
  core/Cargo.toml
  core/src/consensus/progress_map.rs
  core/src/lib.rs
  core/src/replay_stage.rs
  ledger/Cargo.toml
  ledger/src/blockstore_processor.rs
  ledger/src/lib.rs
  program-runtime/src/lib.rs
  program-runtime/src/timings.rs
  programs/sbf/Cargo.lock
Labels: community, need:merge-assist

#700 Remove stale poh recorder validator id
  core/src/banking_stage.rs
  core/src/banking_stage/consume_worker.rs
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/forward_worker.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
  core/src/replay_stage.rs
  core/src/validator.rs
  poh/src/poh_recorder.rs
  poh/src/poh_service.rs
  rpc/src/cluster_tpu_info.rs
Labels: v1.17, v1.18

#775 patches flaky Merkle shreds test
  ledger/src/shred/merkle.rs
Labels: automerge

#769 Track reserved account keys in bank
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  sdk/src/reserved_account_keys.rs
Labels: feature-gate

#800 program: remove unused serde_json dep
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
Labels: community, need:merge-assist

#811 [anza migration]: update repo path
  README.md
Labels: community, need:merge-assist

#801 sdk: move assert_matches and solana-logger to dev deps
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
Labels: community, need:merge-assist

#812 excludes more Merkle shreds tests from coverage CI
  scripts/coverage.sh
Labels: automerge

#707 Parameterize max streams per ms
  client/src/connection_cache.rs
  core/src/tpu.rs
  quic-client/tests/quic_client.rs
  streamer/src/nonblocking/quic.rs
  streamer/src/nonblocking/stream_throttle.rs
  streamer/src/quic.rs
Labels: v1.18

#827 Move Bank::calculate_stake_vote_rewards to sub-submodule
  runtime/src/bank.rs
  runtime/src/bank/partitioned_epoch_rewards/calculation.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
Labels: automerge

#582 cli: adding prio fee support to validator-info
  cli/src/cli.rs
  cli/src/validator_info.rs
Labels: community, need:merge-assist

#583 add feature gate to collect and reward priority fee fully
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
  runtime/src/bank.rs
  runtime/src/bank/fee_distribution.rs
  runtime/src/bank/tests.rs
  sdk/src/feature_set.rs
Labels: feature-gate

#854 Add --log-messages-bytes-limit arg to ledger-tool
  ledger-tool/src/args.rs
  ledger-tool/src/main.rs
Labels: community, need:merge-assist

#859 Replaces StorableAccountsWithHashes in TieredStorage
  accounts-db/benches/bench_accounts_file.rs
  accounts-db/src/accounts_file.rs
  accounts-db/src/tiered_storage.rs
  accounts-db/src/tiered_storage/hot.rs
Labels: automerge

#860 Replaces StorableAccountsWithHashes in AccountsFile
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_file.rs
Labels: automerge

#861 Replaces StorableAccountsWithHashes in AccountsDb
  accounts-db/src/accounts_db.rs
Labels: automerge

#686 Move Stats::submit to solana-runtime
  program-runtime/src/loaded_programs.rs
  runtime/src/bank.rs
  runtime/src/bank/metrics.rs
Labels: automerge, community, need:merge-assist

#862 Removes StorableAccountsWithHashes
  accounts-db/benches/bench_accounts_file.rs
  accounts-db/src/account_storage/meta.rs
  accounts-db/src/append_vec.rs
Labels: automerge

#794 Use poh grace ticks when new reset bank is pending
  core/src/replay_stage.rs
  core/src/validator.rs
  local-cluster/src/validator_configs.rs
  poh/src/poh_recorder.rs
  validator/src/cli.rs
  validator/src/main.rs
Labels: automerge, v1.18

#846 fix: validator command in the doc and add some context
  docs/src/operations/setup-a-validator.md
Labels: community, need:merge-assist

#891 Removes check_hash from ScanState
  accounts-db/src/accounts_db.rs
Labels: automerge

#893 Removes tests that use check_hash
  accounts-db/src/accounts_db.rs
Labels: automerge

#892 Removes check_hash from scan_snapshot_stores_with_cache()
  accounts-db/src/accounts_db.rs
Labels: automerge

#913 Removes check_hash from CalcAccountsHashConfig
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_hash.rs
  core/src/accounts_hash_verifier.rs
  core/tests/epoch_accounts_hash.rs
  runtime/src/accounts_background_service.rs
  runtime/src/bank.rs
  runtime/src/snapshot_bank_utils.rs
Labels: automerge

#851 Limit max concurrent connections
  quic-client/tests/quic_client.rs
  streamer/src/nonblocking/quic.rs
  streamer/src/quic.rs
Labels: v1.17, v1.18

#918 chore: bump rustls to 0.21.11
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
Labels: automerge, v1.17, v1.18

#914 Removes returned Result from infallible fns
  accounts-db/src/accounts_db.rs
  core/src/accounts_hash_verifier.rs
  core/tests/epoch_accounts_hash.rs
  runtime/src/accounts_background_service.rs
  runtime/src/bank.rs
  runtime/src/snapshot_bank_utils.rs
Labels: automerge

#922 cli: Warn on sizes above 10MB during `solana rent`
  cli/src/cluster_query.rs
Labels: community, need:merge-assist

#911 [anza migration]: docs: Update repo links in cli/install
  docs/src/cli/install.md
Labels: automerge, community, need:merge-assist

#945 [anza migration]: update repo url
  docs/docusaurus.config.js
Labels: community, need:merge-assist

#962 share the stream counter for unstaked connections as well
  streamer/src/nonblocking/quic.rs
Labels: v1.17, v1.18

#904 quic: delay calling set_max_concurrent_uni_streams/set_receive_window
  streamer/src/nonblocking/quic.rs
Labels: v1.17, v1.18

#940 chore: fix typos
  core/src/banking_stage/unprocessed_transaction_storage.rs
  core/src/repair/quic_endpoint.rs
  core/src/repair/serve_repair.rs
Labels: automerge, community, need:merge-assist

#961 blockstore: store first received coding shred index in ErasureMeta
  ledger/src/blockstore_meta.rs
Labels: v1.18

#939 sleep instead of drop when stream rate exceeded limit;
  streamer/src/nonblocking/quic.rs
  streamer/src/nonblocking/stream_throttle.rs
Labels: v1.17, v1.18

#928 cli: Add `--use-rpc` flag to program deploy and write-buffer
  CHANGELOG.md
  cli/src/program.rs
  cli/tests/program.rs
  transaction-dos/src/main.rs
Labels: v1.18

#1001 cli: Update help text for deploy's `--use-rpc`
  cli/src/program.rs
Labels: v1.18

#835 blockstore: send duplicate proofs for chained merkle root conflicts
  ledger/src/blockstore.rs
  ledger/src/blockstore_meta.rs
  sdk/src/feature_set.rs
Labels: automerge, v1.18, feature-gate

#1008 cli: Use --use-rpc flag correctly during program deployments
  cli/src/program.rs
Labels: v1.18

#1012 Add StakeError index comments
  sdk/program/src/stake/instruction.rs
Labels: automerge

#980 Transaction Status: Add support for `token-group` and `token-metadata` interface instructions
  Cargo.lock
  programs/sbf/Cargo.lock
  transaction-status/Cargo.toml
  transaction-status/src/parse_token.rs
  transaction-status/src/parse_token/extension/mod.rs
  transaction-status/src/parse_token/extension/token_group.rs
  transaction-status/src/parse_token/extension/token_metadata.rs
Labels: automerge

#791 CLI: Auto-extend program accounts by default
  cli/src/program.rs
  cli/tests/program.rs
  transaction-dos/src/main.rs
Labels: automerge, community, need:merge-assist

#1015 Do not start cache warmer if no rpc service uses the tpu cache
  core/src/tvu.rs
  core/src/validator.rs
Labels: v1.17, v1.18

#1063 simplify warm_quic_cache_service instantiation
  core/src/tvu.rs
Labels: v1.17, v1.18

#915 client: Resend transactions using same mechanism as initial send
  client/src/send_and_confirm_transactions_in_parallel.rs
Labels: v1.18

#1070 cli: use newer blockhashes when deploying large programs
  client/src/send_and_confirm_transactions_in_parallel.rs
Labels: v1.18

#1076 Reward distribution clean-up
  runtime/src/bank/partitioned_epoch_rewards/distribution.rs
Labels: automerge

#1075 make the LogCollector fields public
  program-runtime/src/log_collector.rs
Labels: automerge, community, need:merge-assist

#1048 Add --enable-bigtable-ledger-upload Support to solana-test-validator
  validator/src/bin/solana-test-validator.rs
  validator/src/cli.rs
Labels: automerge, community, need:merge-assist

#1088 sdk: make qualifier_attr dep optional
  sdk/Cargo.toml
Labels: automerge, community, need:merge-assist

#1119 Cli: flip no_extend to auto_extend internally
  cli/src/program.rs
  cli/tests/program.rs
  transaction-dos/src/main.rs
Labels: automerge

#1104 frozen-abi: remove unused deps
  Cargo.lock
  frozen-abi/Cargo.toml
  programs/sbf/Cargo.lock
Labels: community, need:merge-assist

#1130 ignore flaky test: test_hard_fork_with_gap_in_roots
  local-cluster/tests/local_cluster.rs
Labels: automerge
