Repository anza-xyz/agave, pull requests merged in 2024-11, with the labels that each got.

#3416 CI: Re-enable downstream SPL jobs
  .github/scripts/downstream-project-spl-common.sh
  .github/workflows/downstream-project-spl.yml
Labels: v2.1

#3365 streamline status cache insert
  runtime/src/status_cache.rs
Labels: v2.1

#3442 streamer: put testing_utilities.rs behind dev-context-only-utils
  Cargo.lock
  core/Cargo.toml
  streamer/Cargo.toml
  streamer/src/nonblocking/mod.rs
  tpu-client-next/Cargo.toml
Labels: automerge, need:merge-assist

#3438 perf: put test_tx.rs behind dev-context-only-utils
  Cargo.lock
  core/Cargo.toml
  entry/Cargo.toml
  gossip/Cargo.toml
  perf/Cargo.toml
  perf/src/lib.rs
  poh/Cargo.toml
  programs/sbf/Cargo.lock
Labels: automerge, need:merge-assist

#3457 remove solana-sdk from solana-perf
  Cargo.lock
  perf/Cargo.toml
  perf/src/data_budget.rs
  perf/src/deduper.rs
  perf/src/packet.rs
  perf/src/recycler.rs
  perf/src/sigverify.rs
  programs/sbf/Cargo.lock
Labels: automerge, need:merge-assist

#3451 Disallow --rocksdb-shred-compaction fifo in the validator
  CHANGELOG.md
  validator/src/cli.rs
Labels: v2.1

#2182 Feature - Remove accounts executable flag checks
  program-runtime/src/invoke_context.rs
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/serialization.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/loader-v4/src/lib.rs
  programs/sbf/tests/programs.rs
  runtime/src/bank/tests.rs
  sdk/feature-set/src/lib.rs
  sdk/src/transaction_context.rs
  svm/src/account_loader.rs
  svm/src/transaction_processor.rs
Labels: v2.1

#2971 extract reward-info crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/reward-info/Cargo.toml
  sdk/reward-info/src/lib.rs
  sdk/src/lib.rs
  sdk/src/reward_info.rs
  sdk/src/reward_type.rs
Labels: automerge, need:merge-assist

#3423 Extract client code in send_transaction_service into a new structure
  Cargo.lock
  banks-server/src/banks_server.rs
  programs/sbf/Cargo.lock
  rpc/src/rpc.rs
  rpc/src/rpc_service.rs
  send-transaction-service/Cargo.toml
  send-transaction-service/src/lib.rs
  send-transaction-service/src/send_transaction_service.rs
  send-transaction-service/src/send_transaction_service_stats.rs
  send-transaction-service/src/transaction_client.rs
Labels: v2.1

#3481 program-runtime: double program cache size
  program-runtime/src/loaded_programs.rs
Labels: v2.1

#2202 Feature - Lift CPI Caller Restriction
  program-runtime/src/invoke_context.rs
  programs/sbf/tests/programs.rs
  runtime/src/bank/tests.rs
  sdk/feature-set/src/lib.rs
Labels: v2.1

#3339 Add skip preflight to CLI
  CHANGELOG.md
  cargo-registry/src/client.rs
  cli/src/clap_app.rs
  cli/src/feature.rs
  cli/src/main.rs
  cli/src/nonce.rs
  cli/src/program.rs
  cli/src/program_v4.rs
  cli/src/stake.rs
  cli/src/validator_info.rs
  cli/src/vote.rs
  cli/src/wallet.rs
  cli/tests/program.rs
  cli/tests/transfer.rs
  client-test/tests/send_and_confirm_transactions_in_parallel.rs
  client/src/send_and_confirm_transactions_in_parallel.rs
Labels: automerge, community, need:merge-assist

#3087 Extract signer crates
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/keypair/Cargo.toml
  sdk/keypair/src/lib.rs
  sdk/keypair/src/seed_derivable.rs
  sdk/presigner/Cargo.toml
  sdk/presigner/src/lib.rs
  sdk/seed-derivable/Cargo.toml
  sdk/seed-derivable/src/lib.rs
  sdk/seed-phrase/Cargo.toml
  sdk/seed-phrase/src/lib.rs
  sdk/signer/Cargo.toml
  sdk/signer/src/lib.rs
  sdk/signer/src/null_signer.rs
  sdk/signer/src/signers.rs
  sdk/src/lib.rs
  sdk/src/signer/keypair.rs
  sdk/src/signer/mod.rs
  sdk/src/wasm/keypair.rs
Labels: automerge, need:merge-assist

#3498 move sdk crates to sdk dir
  .github/workflows/downstream-project-spl.yml
  Cargo.toml
  programs/sbf/Cargo.toml
  sdk/define-syscall/Cargo.toml
  sdk/define-syscall/src/lib.rs
  sdk/frozen-abi/Cargo.toml
  sdk/frozen-abi/macro/Cargo.toml
  sdk/frozen-abi/macro/src/lib.rs
  sdk/frozen-abi/src/abi_digester.rs
  sdk/frozen-abi/src/abi_example.rs
  sdk/frozen-abi/src/hash.rs
  sdk/frozen-abi/src/lib.rs
  sdk/logger/.gitignore
  sdk/logger/Cargo.toml
  sdk/logger/src/lib.rs
  sdk/short-vec/Cargo.toml
  sdk/short-vec/src/lib.rs
Labels: automerge, need:merge-assist

#3460 extract file-download crate to remove solana-runtime dep from cargo-build-sbf
  Cargo.lock
  Cargo.toml
  download-utils/Cargo.toml
  download-utils/src/lib.rs
  programs/sbf/Cargo.lock
  sdk/cargo-build-sbf/Cargo.toml
  sdk/cargo-build-sbf/src/main.rs
  sdk/file-download/Cargo.toml
  sdk/file-download/src/lib.rs
Labels: automerge, need:merge-assist

#3437 Remove solana-sdk from solana-udp-client
  Cargo.lock
  programs/sbf/Cargo.lock
  udp-client/Cargo.toml
  udp-client/src/lib.rs
  udp-client/src/nonblocking/udp_client.rs
  udp-client/src/udp_client.rs
Labels: need:merge-assist

#3512 remove solana-sdk from cargo-build-sbf
  Cargo.lock
  sdk/cargo-build-sbf/Cargo.toml
  sdk/cargo-build-sbf/src/main.rs
Labels: automerge, need:merge-assist

#3478 add fanout to tpu-client-next
  Cargo.toml
  tpu-client-next/src/connection_worker.rs
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/leader_updater.rs
  tpu-client-next/src/send_transaction_stats.rs
  tpu-client-next/src/workers_cache.rs
  tpu-client-next/tests/connection_workers_scheduler_test.rs
Labels: automerge, v2.1

#3532 v2.1: Disable downstream SPL jobs
  .github/workflows/downstream-project-spl.yml
Labels: automerge

#3521 Revert - #879 and #768
  svm/src/account_loader.rs
  svm/src/transaction_processor.rs
  svm/tests/concurrent_tests.rs
Labels: v2.1

#3548 Feature - disable account loader special case
  sdk/feature-set/src/lib.rs
  svm/src/account_loader.rs
Labels: automerge, v2.1

#3579 Fix typos
  accounts-db/src/tiered_storage/hot.rs
  bench-tps/src/log_transaction_service.rs
  core/src/consensus/fork_choice.rs
  core/src/consensus/heaviest_subtree_fork_choice.rs
  curves/secp256k1-recover/src/lib.rs
  docs/src/backwards-compatibility.md
  docs/src/validator/tpu.md
  dos/src/main.rs
  local-cluster/tests/local_cluster.rs
  sdk/file-download/src/lib.rs
  sdk/src/client.rs
  sdk/src/secp256k1_instruction.rs
  send-transaction-service/src/tpu_info.rs
  tpu-client-next/src/connection_workers_scheduler.rs
  wen-restart/src/wen_restart.rs
Labels: community, need:merge-assist

#3119 Extract quic-definitions crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/quic-definitions/Cargo.toml
  sdk/quic-definitions/src/lib.rs
  sdk/src/lib.rs
Labels: automerge, need:merge-assist

#3405 Move remaining syscall definitions out of solana-program
  curves/secp256k1-recover/src/lib.rs
  poseidon/src/lib.rs
  sdk/cpi/src/syscalls.rs
  sdk/define-syscall/src/definitions.rs
  sdk/define-syscall/src/lib.rs
  sdk/instruction/src/syscalls.rs
  sdk/msg/src/syscalls.rs
  sdk/program-memory/src/lib.rs
  sdk/program/src/syscalls/definitions.rs
  sdk/pubkey/src/syscalls.rs
  sdk/sha256-hasher/src/lib.rs
Labels: need:merge-assist

#3597 fix: `build-sbf` Home Directory Error on Windows
  sdk/cargo-build-sbf/src/main.rs
Labels: community, need:merge-assist

#3606 instruction: Derive everything for wasm build
  sdk/instruction/src/lib.rs
Labels: automerge, v2.1

#3615 Logs lt hash checksums if the feature is off but the cli arg is on
  runtime/src/bank/accounts_lt_hash.rs
Labels: automerge

#3330 Extract ed25519-instructions crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/ed25519-instructions/Cargo.toml
  sdk/ed25519-instructions/src/lib.rs
  sdk/src/lib.rs
Labels: need:merge-assist

#3441 remove solana-sdk from solana-quic-client
  Cargo.lock
  programs/sbf/Cargo.lock
  quic-client/Cargo.toml
  quic-client/src/lib.rs
  quic-client/src/nonblocking/quic_client.rs
  quic-client/src/quic_client.rs
Labels: need:merge-assist

#3587 remove solana-program from solana-bn254 and solana-curve25519
  Cargo.lock
  curves/bn254/Cargo.toml
  curves/bn254/src/compression.rs
  curves/bn254/src/lib.rs
  curves/curve25519/Cargo.toml
  curves/curve25519/src/edwards.rs
  curves/curve25519/src/ristretto.rs
  programs/sbf/Cargo.lock
Labels: automerge, need:merge-assist

#3387 extract deserialize-utils crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/serde/Cargo.toml
  sdk/serde/src/lib.rs
  sdk/src/lib.rs
Labels: automerge, need:merge-assist

#3601 [zk-sdk] Expose ElGamal decryption and proof program to wasm target
  zk-sdk/Cargo.toml
  zk-sdk/src/encryption/discrete_log.rs
  zk-sdk/src/encryption/elgamal.rs
  zk-sdk/src/encryption/mod.rs
  zk-sdk/src/lib.rs
Labels: v2.1

#3616 Refactor: reorder C-style syscall CPI check order
  programs/bpf_loader/src/syscalls/cpi.rs
Labels: community, need:merge-assist

#3572 geyser: fix always enabled flag
  core/src/validator.rs
  geyser-plugin-manager/src/geyser_plugin_service.rs
  ledger-tool/src/ledger_utils.rs
  local-cluster/src/validator_configs.rs
  validator/src/cli.rs
  validator/src/main.rs
Labels: need:merge-assist

#3642 simplify forward packet batches
  core/src/banking_stage/forward_packet_batches_by_accounts.rs
Labels: automerge, v2.0, v2.1

#3647 adjust pubkey bins for tests
  accounts-db/src/accounts_db.rs
Labels: automerge

#3626 remove solana-sdk from solana-clap-utils
  Cargo.lock
  clap-utils/Cargo.toml
  clap-utils/src/input_parsers.rs
  clap-utils/src/input_validators.rs
  clap-utils/src/keypair.rs
  programs/sbf/Cargo.lock
Labels: need:merge-assist

#3445 remove solana-sdk from solana-streamer
  Cargo.lock
  programs/sbf/Cargo.lock
  streamer/Cargo.toml
  streamer/src/nonblocking/quic.rs
  streamer/src/nonblocking/sendmmsg.rs
  streamer/src/nonblocking/testing_utilities.rs
  streamer/src/packet.rs
  streamer/src/quic.rs
  streamer/src/sendmmsg.rs
  streamer/src/streamer.rs
  streamer/src/tls_certificates.rs
Labels: automerge, need:merge-assist

#3628 remove solana-sdk from clap-v3-utils
  Cargo.lock
  clap-v3-utils/Cargo.toml
  clap-v3-utils/src/input_parsers/mod.rs
  clap-v3-utils/src/input_parsers/signer.rs
  clap-v3-utils/src/input_validators.rs
  clap-v3-utils/src/keypair.rs
  clap-v3-utils/src/offline.rs
Labels: need:merge-assist

#3152 SIMD-0075: Precompile for Secp256r1
  .github/workflows/client-targets.yml
  Cargo.lock
  Cargo.toml
  client/Cargo.toml
  docs/src/runtime/programs.md
  ledger-tool/Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/feature-set/src/lib.rs
  sdk/reserved-account-keys/Cargo.toml
  sdk/reserved-account-keys/src/lib.rs
  sdk/secp256r1-program/Cargo.toml
  sdk/secp256r1-program/src/lib.rs
  sdk/src/precompiles.rs
  test-validator/Cargo.toml
  validator/Cargo.toml
Labels: community, need:merge-assist

#3584 remove ntapi patch
  scripts/cargo-install-all.sh
Labels: v2.0, v2.1

#3439 remove solana-sdk from transaction-metrics-tracker
  Cargo.lock
  programs/sbf/Cargo.lock
  transaction-metrics-tracker/Cargo.toml
  transaction-metrics-tracker/src/lib.rs
Labels: need:merge-assist

#3663 fix secp256r1-program id location
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/reserved-account-keys/Cargo.toml
  sdk/reserved-account-keys/src/lib.rs
  sdk/sdk-ids/src/lib.rs
  sdk/secp256r1-program/Cargo.toml
  sdk/secp256r1-program/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3673 Logs accounts lt hash checksum on initial calculation
  runtime/src/bank.rs
Labels: automerge

#3692 test-validator: Fix upgradeable programs at genesis
  test-validator/src/lib.rs
Labels: automerge, v2.1

#3693 move BorrowedAccountMeta and BorrowedInstruction to instruction crate
  sdk/instruction/src/lib.rs
  sdk/program/src/sysvar/instructions.rs
Labels: automerge, need:merge-assist

#3627 rekey feature enable_get_epoch_stake_syscall
  sdk/feature-set/src/lib.rs
Labels: v2.1

#3132 Extract transaction-context crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/src/lib.rs
  sdk/transaction-context/Cargo.toml
  sdk/transaction-context/src/lib.rs
Labels: need:merge-assist

#3028 extract epoch-info crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/epoch-info/Cargo.toml
  sdk/epoch-info/src/lib.rs
  sdk/src/lib.rs
Labels: need:merge-assist

#3680 Extract sysvar crate, including program_stubs.rs
  Cargo.lock
  Cargo.toml
  ci/nits.sh
  programs/sbf/Cargo.lock
  runtime/src/bank/serde_snapshot.rs
  sdk/Cargo.toml
  sdk/benches/serialize_instructions.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/message/sanitized.rs
  sdk/program/src/stake_history.rs
  sdk/program/src/sysvar.rs
  sdk/sysvar/Cargo.toml
  sdk/sysvar/src/clock.rs
  sdk/sysvar/src/epoch_rewards.rs
  sdk/sysvar/src/epoch_schedule.rs
  sdk/sysvar/src/fees.rs
  sdk/sysvar/src/instructions.rs
  sdk/sysvar/src/last_restart_slot.rs
  sdk/sysvar/src/lib.rs
  sdk/sysvar/src/program_stubs.rs
  sdk/sysvar/src/recent_blockhashes.rs
  sdk/sysvar/src/rent.rs
  sdk/sysvar/src/rewards.rs
  sdk/sysvar/src/slot_hashes.rs
  sdk/sysvar/src/slot_history.rs
  sdk/sysvar/src/stake_history.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3655 runtime: migrate stake program to core bpf
  runtime/src/bank/builtins/mod.rs
  sdk/feature-set/src/lib.rs
Labels: feature-gate, v2.1

#3652 move solana_sdk::transaction::Result to solana_transaction_error
  sdk/src/transaction/mod.rs
  sdk/transaction-error/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3408 Extract keccak-hasher crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/keccak-hasher/Cargo.toml
  sdk/keccak-hasher/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3715 remove solana-sdk from solana-bloom
  Cargo.lock
  bloom/Cargo.toml
  bloom/benches/bloom.rs
  bloom/src/bloom.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3718 remove solana-sdk from solana-pubsub-client
  Cargo.lock
  programs/sbf/Cargo.lock
  pubsub-client/Cargo.toml
  pubsub-client/src/nonblocking/pubsub_client.rs
  pubsub-client/src/pubsub_client.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3331 Extract secp256k1-program
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/secp256k1-program/Cargo.toml
  sdk/secp256k1-program/src/lib.rs
  sdk/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3681 remove solana-program from solana-account
  Cargo.lock
  account-decoder-client-types/Cargo.toml
  programs/sbf/Cargo.lock
  sdk/account/Cargo.toml
  sdk/account/src/lib.rs
  sdk/pubkey/Cargo.toml
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3393 Extract compute-budget-interface crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/compute-budget-interface/Cargo.toml
  sdk/compute-budget-interface/src/lib.rs
  sdk/src/lib.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3622 Extract precompiles crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/precompiles/Cargo.toml
  sdk/precompiles/src/lib.rs
  sdk/src/precompiles.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3733 Avoid processing compute-budget instructions by accessing static meta
  core/src/banking_stage/consumer.rs
Labels: automerge

#3736 read compute-budget limits directly from RuntimeTransaction static meta
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: automerge

#3729 Changed prerequisites doc to be distro-independent
  docs/src/operations/prerequisites.md
Labels: community, need:merge-assist

#3743 Fixes whitespace in feature-set
  sdk/feature-set/src/lib.rs
Labels: automerge

#3717 remove solana-sdk from solana-notifier
  Cargo.lock
  notifier/Cargo.toml
  notifier/src/lib.rs
Labels: need:merge-assist

#3740 remove solana-sdk from solana-cli-config
  Cargo.lock
  cli-config/Cargo.toml
  cli-config/src/config.rs
  cli-config/src/config_input.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#3461 remove unnecessary reqwest features from rpc-client-api
  rpc-client-api/Cargo.toml
Labels: need:merge-assist

#3700 [rpc] Fatal `getSignaturesForAddress()` when Bigtable errors
  rpc-client-api/src/custom_error.rs
  rpc/src/rpc.rs
  storage-bigtable/src/lib.rs
Labels: rust

#3774 ci: introduce ci/docker/env.sh
  ci/docker-run-default-image.sh
  ci/docker/Dockerfile
  ci/docker/build.sh
  ci/docker/env.sh
  ci/rust-version.sh
  net/net.sh
Labels: v2.1

#2433 Use system libc jemalloc instead of tikv-jemallocator on FreeBSD
  ledger-tool/Cargo.toml
  ledger-tool/src/main.rs
  validator/Cargo.toml
  validator/src/main.rs
Labels: community, need:merge-assist

#3462 remove vote-program dep from rpc-client
  Cargo.lock
  programs/sbf/Cargo.lock
  rpc-client/Cargo.toml
  rpc-client/src/nonblocking/rpc_client.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#3776 cli: show max vote credits in vote-account based on TVC activation epoch
  cli-output/src/cli_output.rs
  cli/src/vote.rs
Labels: automerge, v2.0, v2.1

#3768 Fix builtin default cost dependents on migration
  Cargo.lock
  builtins-default-costs/benches/builtin_instruction_costs.rs
  builtins-default-costs/src/lib.rs
  core/src/banking_stage/packet_filter.rs
  cost-model/Cargo.toml
  cost-model/src/cost_model.rs
  runtime/src/bank/builtins/mod.rs
Labels: automerge

#3766 test validator: make feature accounts additive
  runtime/src/genesis_utils.rs
  test-validator/src/lib.rs
Labels: automerge

#3806 Revert "build(deps): bump libc from 0.2.164 to 0.2.165 (#3793)"
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge

#3762 chore(cargo-build-sbf): allow using it from nix store
  sdk/cargo-build-sbf/src/main.rs
Labels: community, need:merge-assist

#3813 PrioritizationFeeCache: make update() never sleep on the sender channel
  runtime/src/prioritization_fee_cache.rs
Labels: v2.1

#3822 Update svm codeowners to avoid Cargo.lock reviews
  .github/CODEOWNERS
Labels: automerge
