Repository anza-xyz/agave, pull requests merged in 2024-08, with the labels that each got.

#2372 condition check outside of iterator
  core/src/verified_vote_packets.rs
Labels: community, need:merge-assist

#2375 Fix setting an account override for fee payer
  svm/src/transaction_processor.rs
Labels: community, need:merge-assist, v2.0

#2462 hash-cache-tool: Prints capitalization and num accounts when diffing files
  accounts-db/accounts-hash-cache-tool/src/main.rs
Labels: automerge

#2457 update test for shrink removing zero lamports
  accounts-db/src/accounts_db.rs
Labels: automerge

#2475 refactor: Optimize `instruction_accounts` creation in `invoke_context`
  program-runtime/src/invoke_context.rs
Labels: community, need:merge-assist

#2455 fix: borrow stakes delegation during snapshot serialization
  runtime/src/bank.rs
  runtime/src/bank/partitioned_epoch_rewards/calculation.rs
  runtime/src/bank/serde_snapshot.rs
  runtime/src/stake_account.rs
  runtime/src/stakes.rs
  runtime/src/stakes/serde_stakes.rs
  sdk/program/src/stake/state.rs
Labels: v2.0

#2443 Only run frozen-abi build script when needed
  Cargo.lock
  accounts-db/Cargo.toml
  bloom/Cargo.toml
  builtins-default-costs/Cargo.toml
  cargo-registry/Cargo.toml
  compute-budget/Cargo.toml
  core/Cargo.toml
  cost-model/Cargo.toml
  curves/secp256k1-recover/Cargo.toml
  frozen-abi/Cargo.toml
  frozen-abi/build.rs
  frozen-abi/macro/Cargo.toml
  gossip/Cargo.toml
  ledger/Cargo.toml
  perf/Cargo.toml
  perf/build.rs
  program-runtime/Cargo.toml
  programs/address-lookup-table/Cargo.toml
  programs/sbf/Cargo.lock
  programs/stake-tests/Cargo.toml
  programs/stake/Cargo.toml
  programs/vote/Cargo.toml
  runtime-transaction/Cargo.toml
  runtime/Cargo.toml
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  short-vec/Cargo.toml
  svm/Cargo.toml
  svm/build.rs
  version/Cargo.toml
  vote/Cargo.toml
  wen-restart/Cargo.toml
  wen-restart/build.rs
Labels: automerge, need:merge-assist

#2501 EpochRewards: decode points and rewards fields as Strings
  account-decoder/src/parse_sysvar.rs
Labels: v2.0

#2483 Runtime: Core BPF Migration: Add checks for executable program account
  runtime/src/bank/builtins/core_bpf_migration/error.rs
  runtime/src/bank/builtins/core_bpf_migration/mod.rs
  runtime/src/bank/builtins/core_bpf_migration/target_core_bpf.rs
Labels: v2.0

#2514 Bump rbpf version to 0.8.4 (backport of #2515)
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
Labels: automerge

#2513 Bump rbpf version to 0.8.3 (backport of #2515)
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
Labels: automerge

#2515 Bump rbpf version to 0.8.5
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
Labels: automerge

#2482 Improve type safety in stake state module
  sdk/program/src/stake/state.rs
Labels: automerge

#2583 test-validator: Improve `expect` messages
  validator/src/bin/solana-test-validator.rs
Labels: automerge

#2605 fix: ensure vote packets can be retried
  core/src/banking_stage/latest_unprocessed_votes.rs
  core/src/banking_stage/unprocessed_transaction_storage.rs
Labels: v1.18, v2.0

#587 vote: deprecate legacy vote instructions
  core/src/banking_stage/latest_unprocessed_votes.rs
  core/src/banking_stage/qos_service.rs
  core/src/banking_stage/unprocessed_packet_batches.rs
  core/src/cluster_info_vote_listener.rs
  core/src/commitment_service.rs
  core/src/replay_stage.rs
  core/src/vote_simulator.rs
  cost-model/src/cost_tracker.rs
  cost-model/src/transaction_cost.rs
  ledger/src/blockstore_processor.rs
  local-cluster/src/cluster_tests.rs
  local-cluster/tests/local_cluster.rs
  perf/src/test_tx.rs
  programs/vote/src/vote_processor.rs
  rpc/src/rpc.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
  runtime/tests/stake.rs
  sdk/program/src/vote/state/mod.rs
  sdk/src/feature_set.rs
Labels: feature-gate

#2598 Update security email to security@anza.xyz
  SECURITY.md
Labels: v2.0

#2607 fix: send votes to the immediate next leader
  core/src/next_leader.rs
  core/src/voting_service.rs
Labels: v1.18, v2.0

#2578 ignore path dev deps in circular deps check (attempt 2)
  ci/order-crates-for-publishing.py
Labels: automerge, need:merge-assist

#2591 refactor: use less &mut self and more async-await in BanksClient
  banks-client/src/lib.rs
  program-test/tests/bpf.rs
  program-test/tests/builtins.rs
  program-test/tests/compute_units.rs
  program-test/tests/core_bpf.rs
  program-test/tests/cpi.rs
  program-test/tests/genesis_accounts.rs
  program-test/tests/lamports.rs
  program-test/tests/realloc.rs
  program-test/tests/return_data.rs
  program-test/tests/spl.rs
  tpu-client/src/nonblocking/tpu_client.rs
Labels: community, need:merge-assist

#2657 Fix Turbine metric task names
  turbine/src/quic_endpoint.rs
Labels: community, need:merge-assist

#2622 ci: use actions/upload-artifact@v4
  .github/workflows/release-artifacts.yml
Labels: automerge

#2531 Runtime: Core BPF: Add test for CPI post-migration
  runtime/src/bank/builtin_programs.rs
Labels: v2.0

#2676 Check poh_recorder.start_slot() hasn't been dumped previously before checking it in ProgressMap.
  core/src/replay_stage.rs
Labels: v2.0

#2673 gossip: ignore retransmitter signatures when comparing duplicate shreds
  gossip/src/duplicate_shred.rs
  ledger/src/shred.rs
  ledger/src/shred/merkle.rs
Labels: automerge, v2.0

#2635 sdk: refactor: clean up entrypoint
  sdk/program/src/entrypoint.rs
Labels: community, need:merge-assist

#2700 replay: do not early return when marking slots duplicate confirmed
  core/src/replay_stage.rs
Labels: automerge, v2.0

#2694 Program Test: clean up invoke_builtin_function
  program-test/src/lib.rs
Labels: community, need:merge-assist

#2723 adds test coverage for Shred::is_shred_duplicate
  ledger/src/shred.rs
Labels: automerge

#2632 Program Test: Fix invoke_builtin_function unwinding
  program-test/src/lib.rs
  program-test/tests/panic.rs
Labels: community, need:merge-assist

#2278 feat: Allow skip preflight health check
  rpc/src/rpc.rs
  validator/src/cli.rs
  validator/src/main.rs
Labels: automerge, community, need:merge-assist

#2744 Tweaks for transaction-level fuzzing
  ledger/src/blockstore_processor.rs
  program-test/src/lib.rs
  runtime/src/bank.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
  runtime/src/bank/tests.rs
Labels: community, need:merge-assist

#2441 feat: move precompile verification to SVM
  Cargo.lock
  banks-server/src/banks_server.rs
  core/src/banking_stage/consumer.rs
  program-runtime/src/invoke_context.rs
  programs/ed25519-tests/tests/process_transaction.rs
  programs/sbf/Cargo.lock
  rpc/src/rpc.rs
  runtime/src/bank.rs
  sdk/Cargo.toml
  sdk/src/feature_set.rs
  sdk/src/precompiles.rs
  svm/src/message_processor.rs
Labels: feature-gate

#2754 gossip: demote invalid duplicate proof errors to info
  gossip/src/duplicate_shred.rs
  gossip/src/duplicate_shred_handler.rs
Labels: automerge, v2.0

#2760 Remove explicit stream finish
  quic-client/src/nonblocking/quic_client.rs
Labels: v2.0

#2758 RPC: rewards, return error if epoch_boundary_block is a lie
  rpc-client-api/src/custom_error.rs
  rpc/src/rpc.rs
Labels: v2.0

#2539 Support SSLKEYLOGFILE
  core/src/repair/quic_endpoint.rs
  streamer/src/quic.rs
  turbine/src/quic_endpoint.rs
Labels: community, need:merge-assist

#2780 SIMD-0118: fix `total_rewards` for recalculation
  programs/bpf_loader/src/syscalls/mod.rs
  programs/stake/src/stake_instruction.rs
  rpc/src/rpc.rs
  runtime/src/bank/partitioned_epoch_rewards/calculation.rs
  runtime/src/bank/partitioned_epoch_rewards/distribution.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
  runtime/src/bank/partitioned_epoch_rewards/sysvar.rs
  runtime/src/bank/sysvar_cache.rs
  sdk/program/src/epoch_rewards.rs
  sdk/src/feature_set.rs
Labels: v2.0
