Repository anza-xyz/agave, pull requests merged in 2024-05, with the labels that each got.

#941 remove token-2022 dep from rpc-client-api
  Cargo.lock
  programs/sbf/Cargo.lock
  rpc-client-api/Cargo.toml
  rpc-client-api/src/filter.rs
  rpc/src/filter.rs
  rpc/src/lib.rs
  rpc/src/rpc.rs
  rpc/src/rpc_subscriptions.rs
Labels: automerge, community, need:merge-assist

#1176 clippy: cloned()
  bucket_map/src/restart.rs
Labels: automerge

#1177 clippy: clone_from()
  bucket_map/src/bucket.rs
  cargo-registry/src/crate_handler.rs
  cli/src/cluster_query.rs
  cli/src/program.rs
  cli/tests/nonce.rs
  ledger/src/rooted_slot_iterator.rs
  local-cluster/tests/local_cluster.rs
  sdk/program/src/program_option.rs
  turbine/src/broadcast_stage/broadcast_metrics.rs
Labels: automerge

#1162 typo fix: due_to_to_to -> due_to
  core/src/consensus.rs
Labels: community, need:merge-assist

#1191 Fix dupe account handling in 'ledger-tool program run' command
  ledger-tool/src/program.rs
Labels: community, need:merge-assist

#1123 Extend HTTP client to use reqwest with middleware
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  rpc-client-api/Cargo.toml
  rpc-client-api/src/client_error.rs
  rpc-client/Cargo.toml
  rpc-client/src/http_sender.rs
Labels: community, need:merge-assist

#1203 refactor: update stake_state.rs
  programs/stake/src/stake_state.rs
Labels: community, need:merge-assist

#797 Fix: solana stakes <pubkey> clean handling
  cli/src/cluster_query.rs
Labels: automerge, community, need:merge-assist

#1189 RPC: fix numNonVoteTransactions in getPerformanceSamples
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
Labels: v1.18

#1209 ci: don't self-update rustup when using the rust-version script
  ci/rust-version.sh
Labels: v1.17, v1.18

#1087 program: remove unused tiny_bip39 dep
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/program/Cargo.toml
Labels: community, need:merge-assist

#1231 Tidy up accounts read cache stats
  accounts-db/src/accounts_db.rs
  accounts-db/src/read_only_accounts_cache.rs
Labels: automerge

#1235 ff cleanup: consume_blockstore_duplicate_proofs
  core/src/replay_stage.rs
Labels: automerge

#1092 frozen-abi: move serde_bytes to dev-dependencies
  frozen-abi/Cargo.toml
  programs/sbf/Cargo.lock
Labels: automerge, community, need:merge-assist

#1248 Don't panic the vote program
  programs/vote/src/vote_state/mod.rs
  sdk/program/src/vote/error.rs
Labels: community, need:merge-assist

#1213 Add Option's commonly used methods to OptionSerializer
  transaction-status/src/option_serializer.rs
Labels: community, need:merge-assist

#1222 Make frozen-abi optional in solana-program
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/address_lookup_table/state.rs
  sdk/program/src/blake3.rs
  sdk/program/src/bpf_loader_upgradeable.rs
  sdk/program/src/epoch_rewards.rs
  sdk/program/src/epoch_schedule.rs
  sdk/program/src/fee_calculator.rs
  sdk/program/src/hash.rs
  sdk/program/src/instruction.rs
  sdk/program/src/keccak.rs
  sdk/program/src/lib.rs
  sdk/program/src/loader_v4.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/message/mod.rs
  sdk/program/src/message/versions/mod.rs
  sdk/program/src/message/versions/v0/mod.rs
  sdk/program/src/pubkey.rs
  sdk/program/src/rent.rs
  sdk/program/src/secp256k1_recover.rs
  sdk/program/src/short_vec.rs
  sdk/program/src/stake/stake_flags.rs
  sdk/program/src/stake/state.rs
  sdk/program/src/stake_history.rs
  sdk/program/src/system_instruction.rs
  sdk/program/src/vote/authorized_voters.rs
  sdk/program/src/vote/state/mod.rs
  sdk/program/src/vote/state/vote_state_1_14_11.rs
Labels: community, need:merge-assist

#1226 Do not purge old snapshot archives in bank_to_snapshot_archive()
  core/src/validator.rs
  ledger-tool/src/main.rs
  local-cluster/tests/local_cluster.rs
  runtime/src/bank/serde_snapshot.rs
  runtime/src/bank/tests.rs
  runtime/src/snapshot_bank_utils.rs
Labels: automerge

#1199 Fix - Reloading of unload entries after finishing the recompilation phase
  program-runtime/src/loaded_programs.rs
  runtime/src/bank/tests.rs
  svm/src/program_loader.rs
Labels: v1.18

#1259 blockstore: account for blockstore cleanup during shred insertion
  ledger/src/blockstore.rs
Labels: v1.18

#1280 chore: fix typos
  core/src/banking_stage/leader_slot_metrics.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: community, need:merge-assist

#1284 fix multinode-demo stake script
  multinode-demo/delegate-stake.sh
Labels: automerge

#1261 ci: add llvm-tools-preview
  ci/docker/Dockerfile
Labels: automerge

#1294 Bugfix: clean_queue pushes valid transactions back into queue
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: automerge, v1.18

#1302 fix typos
  unified-scheduler-pool/src/lib.rs
  validator/src/bootstrap.rs
Labels: community, need:merge-assist

#1308 accounts-db: fix 8G+ memory spike during hash calculation
  accounts-db/src/accounts_hash.rs
Labels: v1.18

#1288 deactivate serde feature of bitflags where not needed
  Cargo.toml
  frozen-abi/Cargo.toml
  ledger/Cargo.toml
  sdk/Cargo.toml
Labels: community, need:merge-assist

#560 Rework SysvarCache implementation
  program-runtime/Cargo.toml
  program-runtime/src/sysvar_cache.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/bpf_loader/src/syscalls/sysvar.rs
  programs/sbf/Cargo.lock
Labels: need:merge-assist

#1286 deactivate hmac feature of libsecp256k1 where not needed
  Cargo.toml
  sdk/Cargo.toml
Labels: community, need:merge-assist

#1337 sdk: remove unused base64 dep
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
Labels: need:merge-assist

#1327 program: remove unnecessary activation of serde feature of curve25519-dalek
  sdk/program/Cargo.toml
Labels: need:merge-assist

#1331 program: remove unused libc dep
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
Labels: need:merge-assist

#1325 remove unused syn features
  frozen-abi/macro/Cargo.toml
  sdk/macro/Cargo.toml
Labels: need:merge-assist

#1340 sdk: remove unused num-derive and num-traits deps
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
Labels: need:merge-assist

#1345 clippy: allow dead_code for ParsedFilename
  accounts-db/src/cache_hash_data.rs
Labels: automerge

#1344 ledger-tool: Add --enable-extended-tx-metadata-storage arg
  ledger-tool/src/ledger_utils.rs
  ledger-tool/src/main.rs
Labels: community, need:merge-assist

#1329 Prefer explicitly using serde_derive instead of the "derive" feature of serde
  Cargo.lock
  Cargo.toml
  banks-interface/Cargo.toml
  banks-interface/src/lib.rs
  cargo-registry/Cargo.toml
  cargo-registry/src/crate_handler.rs
  cargo-registry/src/sparse_index.rs
  frozen-abi/Cargo.toml
  frozen-abi/src/abi_digester.rs
  frozen-abi/src/lib.rs
  install/Cargo.toml
  install/src/command.rs
  install/src/config.rs
  install/src/update_manifest.rs
  ledger-tool/Cargo.toml
  ledger-tool/src/main.rs
  ledger-tool/src/output.rs
  ledger-tool/src/program.rs
  net-shaper/Cargo.toml
  net-shaper/src/main.rs
  programs/address-lookup-table/Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/rust/big_mod_exp/Cargo.toml
  programs/sbf/rust/big_mod_exp/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/address_lookup_table/instruction.rs
  sdk/program/src/address_lookup_table/state.rs
  sdk/program/src/alt_bn128/compression.rs
  sdk/program/src/alt_bn128/mod.rs
  sdk/program/src/big_mod_exp.rs
  sdk/program/src/example_mocks.rs
  sdk/program/src/message/versions/mod.rs
  sdk/program/src/vote/state/mod.rs
  svm/Cargo.toml
  svm/src/message_processor.rs
  tokens/Cargo.toml
  zk-sdk/Cargo.toml
  zk-token-sdk/Cargo.toml
Labels: need:merge-assist

#1359 Allow `cargo-test-sbf` accept `--tools-version`
  Cargo.lock
  sdk/cargo-test-sbf/Cargo.toml
  sdk/cargo-test-sbf/src/main.rs
Labels: community, need:merge-assist

#1374 Deprecate `is_key_passed_to_program` in favor of `is_instruction_account`
  accounts-db/src/accounts.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/message/sanitized.rs
  sdk/program/src/message/versions/mod.rs
Labels: automerge

#1377 Fix typos
  validator/src/main.rs
  zk-sdk/src/elgamal_program/instruction.rs
  zk-sdk/src/encryption/auth_encryption.rs
  zk-sdk/src/sigma_proofs/pubkey.rs
Labels: community, need:merge-assist

#1336 clippy: readonly_write_lock
  ledger/src/blockstore.rs
Labels: automerge

#1077 SVM: Hoist program cache recompilation up from Bank
  program-runtime/src/loaded_programs.rs
  programs/sbf/Cargo.lock
  runtime/src/bank.rs
  runtime/src/bank/metrics.rs
  runtime/src/bank/tests.rs
  svm/Cargo.toml
  svm/src/transaction_processor.rs
Labels: automerge

#1307 implement SyscallGetSysvar
  program-runtime/src/sysvar_cache.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/bpf_loader/src/syscalls/sysvar.rs
  sdk/program/src/program_stubs.rs
  sdk/program/src/syscalls/definitions.rs
  sdk/src/feature_set.rs
Labels: feature-gate

#1387 rpc-client: Print transaction logs in preflight error
  cli/tests/program.rs
  rpc-client-api/src/request.rs
Labels: automerge

#1002 replay: only vote on blocks with >= 32 data shreds in last fec set
  core/src/replay_stage.rs
  ledger/src/blockstore.rs
  ledger/src/blockstore_db.rs
  ledger/src/blockstore_processor.rs
  sdk/src/feature_set.rs
Labels: automerge, v1.18, feature-gate

#1409 sdk: Fix --no-default-features build in transaction_context.rs
  sdk/src/transaction_context.rs
Labels: automerge

#1379 Feature-Gate: Migrate Config program to Core BPF
  runtime/src/bank/builtins/mod.rs
  sdk/src/feature_set.rs
Labels: automerge

#1423 v1.18 - Add detailed metrics reporting for packet filtering
  core/src/banking_stage.rs
  core/src/banking_stage/immutable_deserialized_packet.rs
  core/src/banking_stage/leader_slot_metrics.rs
  core/src/banking_stage/packet_deserializer.rs
  core/src/banking_stage/packet_filter.rs
  core/src/banking_stage/packet_receiver.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: automerge

#1421 Add detailed metrics reporting for packet filtering
  core/src/banking_stage.rs
  core/src/banking_stage/immutable_deserialized_packet.rs
  core/src/banking_stage/leader_slot_metrics.rs
  core/src/banking_stage/packet_deserializer.rs
  core/src/banking_stage/packet_filter.rs
  core/src/banking_stage/packet_receiver.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: automerge

#1443 add ca-certificates to docker image
  sdk/docker-solana/Dockerfile
Labels: v1.17, v1.18, community, need:merge-assist

#1451 bump socket2 from 0.5.6 to 0.5.7
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
Labels: automerge

#1450 bump anyhow from 1.0.82 to 1.0.86
  Cargo.lock
  programs/sbf/Cargo.lock
Labels: automerge

#1469 Invoke Context: Dedupe compute budgets
  program-runtime/src/invoke_context.rs
Labels: automerge

#1464 sdk: Add macro to get Cargo.toml package metadata
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/macro/Cargo.toml
  sdk/macro/src/lib.rs
Labels: automerge

#1449 remove superfluous conditional
  core/src/consensus.rs
Labels: community, need:merge-assist

#1477 chore: remove log-analyzer from gitignore
  .gitignore
Labels: automerge

#1504 [banks-server] fix: Enable CPI tracking by default
  banks-server/src/banks_server.rs
Labels: community, need:merge-assist

#1500 replay: add metrics for threshold failures
  core/src/replay_stage.rs
Labels: v1.18

#1513 chore: remove unused clippy attributes, redundant_closure
  cli/src/nonce.rs
  cli/tests/nonce.rs
  cli/tests/stake.rs
  cli/tests/transfer.rs
  rpc-client-nonce-utils/src/blockhash_query.rs
  rpc-client-nonce-utils/src/nonblocking/blockhash_query.rs
  sdk/src/precompiles.rs
Labels: automerge

#1514 chore: remove unused clippy attributes, unnecessary_wraps
  cli/src/wallet.rs
  frozen-abi/src/abi_digester.rs
  program-test/tests/cpi.rs
  program-test/tests/fuzz.rs
  program-test/tests/return_data.rs
  programs/sbf/rust/custom_heap/src/lib.rs
  programs/sbf/rust/deprecated_loader/src/lib.rs
  programs/sbf/rust/external_spend/src/lib.rs
  programs/sbf/rust/get_minimum_delegation/src/lib.rs
  programs/sbf/rust/inner_instruction_alignment_check/src/lib.rs
  programs/sbf/rust/invoke_and_ok/src/lib.rs
  programs/sbf/rust/invoke_and_return/src/lib.rs
  programs/sbf/rust/mem/src/entrypoint.rs
  programs/sbf/rust/noop/src/lib.rs
  programs/sbf/rust/panic/src/lib.rs
  programs/sbf/rust/rand/src/lib.rs
  programs/sbf/rust/realloc/src/processor.rs
  programs/sbf/rust/realloc_invoke/src/processor.rs
  programs/sbf/rust/sanity/src/lib.rs
  programs/sbf/rust/spoof1_system/src/lib.rs
  programs/sbf/rust/sysvar/src/lib.rs
Labels: automerge

#1516 chore: remove unused clippy attributes, derive_partial_eq_without_eq
  storage-bigtable/proto/google.api.rs
  storage-bigtable/proto/google.bigtable.v2.rs
  storage-bigtable/proto/google.rpc.rs
  storage-bigtable/src/bigtable.rs
  storage-proto/src/convert.rs
Labels: automerge

#1515 chore: remove unused clippy attributes, float_cmp
  genesis/src/unlocks.rs
  gossip/src/crds_gossip_pull.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  sdk/src/inflation.rs
  sdk/src/timing.rs
Labels: automerge

#1462 refactor: reuse calculated fees
  accounts-db/src/accounts.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
  programs/sbf/tests/programs.rs
  rpc/src/transaction_status_service.rs
  runtime/src/bank.rs
  runtime/src/bank/fee_distribution.rs
  runtime/src/bank/tests.rs
  sdk/src/fee.rs
  svm/src/account_loader.rs
  svm/src/transaction_processor.rs
  svm/src/transaction_results.rs
Labels: automerge

#1521 chore: bump aes-gcm-siv from 0.10.3 to 0.11.1
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  zk-sdk/src/encryption/auth_encryption.rs
  zk-token-sdk/src/encryption/auth_encryption.rs
Labels: automerge

#1534 chore: remove some unused deps
  Cargo.toml
  programs/sbf/Cargo.toml
Labels: automerge

#1545 chore: bump subtle from 2.4.1 to 2.5.0
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
Labels: automerge
