Repository anza-xyz/agave, pull requests merged in 2024-10, with the labels that each got.

#3023 add #![no_std] to solana-clock
  sdk/clock/src/lib.rs
  sdk/macro/src/lib.rs
Labels: need:merge-assist

#3024 remove unused deps from solana-measure
  Cargo.lock
  measure/Cargo.toml
  programs/sbf/Cargo.lock
Labels: need:merge-assist

#2526 Fix broken parallelism in quic-client
  quic-client/src/lib.rs
  quic-client/src/nonblocking/quic_client.rs
Labels: community, need:merge-assist

#3025 remove unused deps from solana-version
  Cargo.lock
  programs/sbf/Cargo.lock
  version/Cargo.toml
Labels: automerge, need:merge-assist

#2930 Extract program-pack crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program-pack/Cargo.toml
  sdk/program-pack/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
Labels: automerge, need:merge-assist

#3070 ci: run Github Actions only in anza-xyz/agave
  .github/workflows/add-team-to-ghsa.yml
  .github/workflows/benchmark.yml
  .github/workflows/cargo.yml
  .github/workflows/client-targets.yml
  .github/workflows/crate-check.yml
  .github/workflows/docs.yml
  .github/workflows/downstream-project-spl-nightly.yml
  .github/workflows/downstream-project-spl.yml
  .github/workflows/release.yml
Labels: automerge

#2294 Extract solana-account crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/account/Cargo.toml
  sdk/account/src/lib.rs
  sdk/src/account_utils.rs
  sdk/src/client.rs
  sdk/src/feature.rs
  sdk/src/genesis_config.rs
  sdk/src/lib.rs
  sdk/src/native_loader.rs
  sdk/src/nonce_account.rs
  sdk/src/rent_collector.rs
  sdk/src/transaction_context.rs
Labels: need:merge-assist

#2914 cargo-build-sbf: Use `metadata.solana.tools-version` in Cargo.toml
  CHANGELOG.md
  ci/platform-tools-info.sh
  sdk/cargo-build-sbf/src/main.rs
  sdk/cargo-build-sbf/tests/crates.rs
  sdk/cargo-build-sbf/tests/crates/package-metadata/Cargo.toml
  sdk/cargo-build-sbf/tests/crates/package-metadata/src/lib.rs
  sdk/cargo-build-sbf/tests/crates/workspace-metadata/Cargo.toml
  sdk/cargo-build-sbf/tests/crates/workspace-metadata/src/lib.rs
  sdk/cargo-test-sbf/src/main.rs
Labels: automerge

#3098 Consistent ImmutableDeserializedPacket::PartialEq
  core/src/banking_stage/immutable_deserialized_packet.rs
Labels: bug

#2801 fix: reduce max packet receive time during leader window
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: automerge, community, need:merge-assist

#3064 docs: setup-a-validator.md Add cluster specific note
  docs/src/operations/setup-a-validator.md
Labels: community, need:merge-assist

#3081 move LamportsError to solana-instruction
  sdk/instruction/src/error.rs
  sdk/program/src/lamports.rs
Labels: automerge, need:merge-assist

#3010 extract slot-hashes crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
  sdk/program/src/slot_hashes.rs
  sdk/slot-hashes/Cargo.toml
  sdk/slot-hashes/src/lib.rs
Labels: need:merge-assist

#3021 Extract epoch-schedule crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  runtime/src/bank/serde_snapshot.rs
  sdk/epoch-schedule/Cargo.toml
  sdk/epoch-schedule/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/epoch_schedule.rs
  sdk/src/genesis_config.rs
Labels: need:merge-assist

#3113 Deprecate Legacy BlockProductionMethod
  CHANGELOG.md
  core/src/validator.rs
Labels: changelog

#3086 remove thiserror from solana-derivation-path
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/derivation-path/Cargo.toml
  sdk/derivation-path/src/lib.rs
Labels: need:merge-assist

#3133 SDK doc fixes
  sdk/decode-error/src/lib.rs
  sdk/program-option/src/lib.rs
  sdk/src/signer/signers.rs
Labels: automerge, need:merge-assist

#3121 add doc_auto_cfg to relevant sdk crates
  sdk/account-info/Cargo.toml
  sdk/account-info/src/lib.rs
  sdk/account/Cargo.toml
  sdk/account/src/lib.rs
  sdk/hash/Cargo.toml
  sdk/hash/src/lib.rs
  sdk/instruction/Cargo.toml
  sdk/instruction/src/lib.rs
  sdk/program-error/Cargo.toml
  sdk/program-error/src/lib.rs
  sdk/pubkey/Cargo.toml
  sdk/pubkey/src/lib.rs
  sdk/signature/Cargo.toml
  sdk/signature/src/lib.rs
Labels: automerge, need:merge-assist

#3165 token-2022: Use mainnet-beta binary in all tools
  fetch-spl.sh
  program-test/src/programs.rs
  program-test/src/programs/spl_token_2022-1.0.0.so
  program-test/src/programs/spl_token_2022-5.0.2.so
Labels: v2.0

#3073 move sanitize crate to sdk dir
  Cargo.toml
  sdk/sanitize/Cargo.toml
  sdk/sanitize/src/lib.rs
Labels: automerge, need:merge-assist

#3140 remove solana-program from solana-feature-set
  Cargo.lock
  log-analyzer/Cargo.toml
  log-analyzer/src/main.rs
  programs/sbf/Cargo.lock
  sdk/feature-set/Cargo.toml
  sdk/feature-set/src/lib.rs
Labels: automerge, need:merge-assist

#2980 Move `solana_sdk::pubkey` functions to solana-pubkey
  Cargo.lock
  keygen/Cargo.toml
  keygen/src/keygen.rs
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/pubkey/Cargo.toml
  sdk/pubkey/src/lib.rs
  sdk/src/pubkey.rs
Labels: automerge, need:merge-assist

#3157 svm: clear read-only non-signers for test txns
  svm/tests/transaction_builder.rs
Labels: automerge

#3161 Scheduler: Improve TTL
  accounts-db/src/accounts.rs
  core/src/banking_stage/consume_worker.rs
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/immutable_deserialized_packet.rs
  core/src/banking_stage/latest_unprocessed_votes.rs
  core/src/banking_stage/scheduler_messages.rs
  core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
  core/src/banking_stage/transaction_scheduler/transaction_state.rs
  core/src/banking_stage/transaction_scheduler/transaction_state_container.rs
  core/src/banking_stage/unprocessed_packet_batches.rs
  core/src/banking_stage/unprocessed_transaction_storage.rs
  runtime/src/bank/address_lookup_table.rs
  sdk/program/src/address_lookup_table/state.rs
Labels: v2.0

#3178 avoid solana-program in inline-spl
  Cargo.lock
  inline-spl/Cargo.toml
  inline-spl/src/associated_token_account.rs
  inline-spl/src/token.rs
  inline-spl/src/token_2022.rs
  programs/sbf/Cargo.lock
Labels: automerge, need:merge-assist

#2430 Extract entrypoint crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program-entrypoint/Cargo.toml
  sdk/program-entrypoint/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
Labels: need:merge-assist

#3174 move account_utils to account crate
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/account/Cargo.toml
  sdk/account/src/lib.rs
  sdk/account/src/state_traits.rs
  sdk/src/lib.rs
Labels: need:merge-assist

#3175 fix doc link in solana-epoch-schedule
  sdk/epoch-schedule/src/lib.rs
Labels: need:merge-assist

#2300 Extract precompile-error crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/precompile-error/Cargo.toml
  sdk/precompile-error/src/lib.rs
  sdk/src/ed25519_instruction.rs
  sdk/src/precompiles.rs
  sdk/src/secp256k1_instruction.rs
Labels: automerge, need:merge-assist

#3194 rolls back chained Merkle shreds for testnet downgrade
  turbine/src/broadcast_stage/standard_broadcast_run.rs
Labels: automerge, v2.0

#3218 clippy: #[warn(clippy::single_match)]
  accounts-db/src/accounts_db.rs
  accounts-db/src/hardened_unpack.rs
  core/src/cluster_info_vote_listener.rs
  runtime/src/bank.rs
Labels: automerge

#3193 fix solana-instruction when std feature is not activated
  sdk/instruction/src/error.rs
Labels: need:merge-assist

#3229 don't ignore doc examples in secp256k1-recover
  Cargo.lock
  curves/secp256k1-recover/Cargo.toml
  curves/secp256k1-recover/src/lib.rs
Labels: automerge, need:merge-assist

#3248 consensus: move increase_lockouts test fn to dcou
  core/src/consensus.rs
Labels: automerge

#3247 banking_stage: fix test not sending vote txs
  core/src/banking_stage.rs
  programs/vote/src/vote_transaction.rs
Labels: automerge

#2924 extract stable-layout crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/stable-layout/Cargo.toml
  sdk/stable-layout/src/lib.rs
  sdk/stable-layout/src/stable_instruction.rs
  sdk/stable-layout/src/stable_rc.rs
  sdk/stable-layout/src/stable_ref_cell.rs
  sdk/stable-layout/src/stable_slice.rs
  sdk/stable-layout/src/stable_vec.rs
Labels: need:merge-assist

#2969 extract fee-calculator crate
  Cargo.lock
  Cargo.toml
  accounts-db/src/blockhash_queue.rs
  programs/sbf/Cargo.lock
  runtime/src/bank/serde_snapshot.rs
  sdk/fee-calculator/Cargo.toml
  sdk/fee-calculator/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/src/genesis_config.rs
Labels: need:merge-assist

#2295 extract transaction-error crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  runtime/src/bank.rs
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/message/address_loader.rs
  sdk/program/src/message/sanitized.rs
  sdk/src/signer/mod.rs
  sdk/src/transaction/error.rs
  sdk/src/transaction/mod.rs
  sdk/src/transaction/sanitized.rs
  sdk/src/transaction/versioned/mod.rs
  sdk/src/transport.rs
  sdk/transaction-error/Cargo.toml
  sdk/transaction-error/src/lib.rs
Labels: need:merge-assist

#2955 remove outdated solana-ledger-udev binary
  remote-wallet/Cargo.toml
  remote-wallet/README.md
  remote-wallet/src/bin/ledger-udev.rs
Labels: community, need:merge-assist

#3265 Refactor index generation startup stat
  accounts-db/src/accounts_db.rs
Labels: automerge

#3276 Fix account data_len
  accounts-db/src/accounts_db.rs
Labels: automerge

#3233 Adds --accounts-db-hash-threads to validator and ledger-tool
  accounts-db/src/accounts_db.rs
  ledger-tool/src/args.rs
  validator/src/cli/thread_args.rs
  validator/src/main.rs
Labels: automerge

#3302 Add slot metric to clean stat
  accounts-db/src/accounts_db.rs
Labels: automerge

#2981 extract solana-cpi crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/cpi/Cargo.toml
  sdk/cpi/src/lib.rs
  sdk/cpi/src/syscalls.rs
  sdk/program/Cargo.toml
  sdk/program/src/program.rs
  sdk/program/src/syscalls/definitions.rs
Labels: automerge, need:merge-assist

#2934 fix: fix shell generation panic due to unnecessary 'conflicts_with'
  cli/src/cli.rs
  cli/src/program_v4.rs
Labels: community, need:merge-assist

#3029 extract packet crate
  Cargo.lock
  Cargo.toml
  core/src/banking_trace.rs
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/packet/Cargo.toml
  sdk/packet/src/lib.rs
  sdk/src/lib.rs
Labels: automerge, need:merge-assist

#2970 extract inflation crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  runtime/src/bank/serde_snapshot.rs
  sdk/Cargo.toml
  sdk/inflation/Cargo.toml
  sdk/inflation/src/lib.rs
  sdk/src/genesis_config.rs
  sdk/src/lib.rs
Labels: automerge, need:merge-assist

#3309 sdk: Extract `solana-sysvar-id` crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/clock/Cargo.toml
  sdk/clock/src/lib.rs
  sdk/clock/src/sysvar.rs
  sdk/epoch-schedule/Cargo.toml
  sdk/epoch-schedule/src/lib.rs
  sdk/epoch-schedule/src/sysvar.rs
  sdk/last-restart-slot/Cargo.toml
  sdk/last-restart-slot/src/lib.rs
  sdk/last-restart-slot/src/sysvar.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/sysvar/clock.rs
  sdk/program/src/sysvar/epoch_rewards.rs
  sdk/program/src/sysvar/epoch_schedule.rs
  sdk/program/src/sysvar/fees.rs
  sdk/program/src/sysvar/instructions.rs
  sdk/program/src/sysvar/last_restart_slot.rs
  sdk/program/src/sysvar/mod.rs
  sdk/program/src/sysvar/recent_blockhashes.rs
  sdk/program/src/sysvar/rent.rs
  sdk/program/src/sysvar/rewards.rs
  sdk/program/src/sysvar/slot_hashes.rs
  sdk/program/src/sysvar/slot_history.rs
  sdk/program/src/sysvar/stake_history.rs
  sdk/rent/Cargo.toml
  sdk/rent/src/lib.rs
  sdk/rent/src/sysvar.rs
  sdk/slot-hashes/Cargo.toml
  sdk/slot-hashes/src/lib.rs
  sdk/slot-hashes/src/sysvar.rs
  sdk/slot-history/Cargo.toml
  sdk/slot-history/src/lib.rs
  sdk/slot-history/src/sysvar.rs
  sdk/sysvar-id/Cargo.toml
  sdk/sysvar-id/src/lib.rs
Labels: v2.1

#3359 publish solana-svm-conformance
  svm-conformance/Cargo.toml
Labels: v2.1

#3358 add missing description for solana-lattice-hash
  lattice-hash/Cargo.toml
Labels: v2.1

#3347 [geyser] `s/shread/shred/` in `SlotStatus`
  geyser-plugin-interface/src/geyser_plugin_interface.rs
Labels: bug

#3188 track zero lamport accounts
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_db/stats.rs
  accounts-db/src/accounts_file.rs
  accounts-db/src/append_vec.rs
  accounts-db/src/tiered_storage.rs
Labels: automerge

#3082 Extract solana-nonce crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/nonce/Cargo.toml
  sdk/nonce/src/lib.rs
  sdk/nonce/src/state.rs
  sdk/nonce/src/versions.rs
  sdk/program/Cargo.toml
  sdk/program/src/nonce.rs
Labels: automerge, need:merge-assist, v2.1

#3327 extract timing-utils crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/src/lib.rs
  sdk/time-utils/Cargo.toml
  sdk/time-utils/src/lib.rs
Labels: need:merge-assist

#3367 Revert "remove test-only bool arg from calculate_fee (#3211)"
  cli/tests/address_lookup_table.rs
  cli/tests/nonce.rs
  cli/tests/program.rs
  cli/tests/request_airdrop.rs
  cli/tests/stake.rs
  cli/tests/validator_info.rs
  cli/tests/vote.rs
  client-test/tests/client.rs
  client-test/tests/send_and_confirm_transactions_in_parallel.rs
  core/src/banking_stage/consumer.rs
  fee/src/lib.rs
  programs/sbf/tests/programs.rs
  rpc-test/tests/rpc.rs
  runtime/src/bank.rs
  runtime/src/bank/fee_distribution.rs
  runtime/src/bank/tests.rs
  sdk/src/fee.rs
  svm/src/transaction_processor.rs
  test-validator/src/lib.rs
  tokens/src/commands.rs
  tokens/tests/commands.rs
Labels: automerge, v2.1

#3369 clarify error when getting cluster shred version.
  validator/src/main.rs
Labels: automerge

#3328 Use parameter struct for configuring QUIC streamer
  client/src/connection_cache.rs
  core/src/tpu.rs
  quic-client/tests/quic_client.rs
  streamer/src/nonblocking/quic.rs
  streamer/src/nonblocking/testing_utilities.rs
  streamer/src/quic.rs
  tpu-client-next/tests/connection_workers_scheduler_test.rs
Labels: v2.1

#3371 Fix incorrect default for num AccountsIndex flush threads
  validator/src/cli/thread_args.rs
Labels: v2.1

#3311 Extract fee-structure crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/fee-structure/Cargo.toml
  sdk/fee-structure/src/lib.rs
  sdk/src/lib.rs
Labels: need:merge-assist

#3375 remove solana-sdk from solana-compute-budget
  Cargo.lock
  compute-budget/Cargo.toml
  compute-budget/src/compute_budget.rs
  compute-budget/src/compute_budget_limits.rs
  programs/sbf/Cargo.lock
Labels: automerge, need:merge-assist

#3384 CI: Pin downstream SPL job to v2.0 branch
  .github/scripts/downstream-project-spl-common.sh
Labels: automerge

#3409 remove solana-program from zk-sdk
  Cargo.lock
  programs/sbf/Cargo.lock
  zk-sdk/Cargo.toml
  zk-sdk/src/zk_elgamal_proof_program/instruction.rs
  zk-sdk/src/zk_elgamal_proof_program/mod.rs
  zk-sdk/src/zk_elgamal_proof_program/state.rs
Labels: automerge, need:merge-assist

#3410 remove solana-program from zk-token-sdk
  Cargo.lock
  programs/sbf/Cargo.lock
  zk-token-sdk/Cargo.toml
  zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
  zk-token-sdk/src/zk_token_proof_instruction.rs
  zk-token-sdk/src/zk_token_proof_program.rs
  zk-token-sdk/src/zk_token_proof_state.rs
Labels: automerge, need:merge-assist
