Repository anza-xyz/agave, pull requests merged in 2024-07, with the labels that each got.

#1931 gossip: do not allow duplicate proofs for incorrect shred versions
  core/src/tvu.rs
  gossip/src/cluster_info.rs
  gossip/src/crds_gossip.rs
  gossip/src/duplicate_shred.rs
  gossip/src/duplicate_shred_handler.rs
Labels: v1.18, v2.0

#1951 Remove deprecated_config module
  client/src/lib.rs
  rpc-client-api/src/deprecated_config.rs
  rpc-client-api/src/lib.rs
Labels: automerge, v2.0

#1930 remove qualifer_attr from svm
  Cargo.lock
  programs/sbf/Cargo.lock
  runtime/Cargo.toml
  svm/Cargo.toml
  svm/src/transaction_processor.rs
Labels: need:merge-assist

#1945 ci: skip spl test when version is too high
  .github/scripts/downstream-project-spl-common.sh
  .github/workflows/downstream-project-spl.yml
Labels: automerge, v1.18, v2.0

#1953 Remove deprecated symbols from solana-sdk
  sdk/src/account.rs
  sdk/src/entrypoint.rs
  sdk/src/entrypoint_deprecated.rs
  sdk/src/lib.rs
  sdk/src/log.rs
  sdk/src/native_loader.rs
  sdk/src/signature.rs
  sdk/src/transaction/mod.rs
Labels: v2.0

#1956 Remove deprecated BanksClient methods and dependent ProgramTest methods
  banks-client/src/lib.rs
  banks-interface/src/lib.rs
  banks-server/src/banks_server.rs
  program-test/src/lib.rs
Labels: v2.0

#1969 accounts-db-tools/add option of file_diff to hash cache tool diff directory
  accounts-db/accounts-hash-cache-tool/src/main.rs
Labels: automerge

#1954 Refactor cost tracking
  core/benches/consumer.rs
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/qos_service.rs
  cost-model/src/cost_model.rs
  ledger/src/blockstore_processor.rs
  program-runtime/src/timings.rs
Labels: v2.0

#1827 Extract define-syscall crate
  Cargo.lock
  Cargo.toml
  define-syscall/Cargo.toml
  define-syscall/src/lib.rs
  poseidon/Cargo.toml
  poseidon/src/lib.rs
  programs/sbf/Cargo.lock
  sdk/program/Cargo.toml
  sdk/program/src/syscalls/definitions.rs
Labels: automerge, need:merge-assist

#1958 Remove deprecated symbols from solana-program
  sdk/program/src/borsh0_9.rs
  sdk/program/src/bpf_loader_upgradeable.rs
  sdk/program/src/clock.rs
  sdk/program/src/fee_calculator.rs
  sdk/program/src/instruction.rs
  sdk/program/src/log.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/pubkey.rs
Labels: v2.0

#1955 Remove deprecated spl-token conversion methods
  account-decoder/src/parse_token.rs
  transaction-status/src/parse_token.rs
Labels: v2.0

#1980 Remove deprecated, unused methods from Bank
  runtime/src/bank.rs
Labels: v2.0

#1972 Remove deprecated address_lookup_table_account re-export
  programs/address-lookup-table/src/lib.rs
  sdk/program/src/example_mocks.rs
  sdk/program/src/lib.rs
  sdk/program/src/message/compiled_keys.rs
  sdk/program/src/message/versions/v0/mod.rs
  sdk/src/lib.rs
Labels: v2.0

#1903 Remove deprecated CommitmentLevel variants
  rpc-client/src/nonblocking/rpc_client.rs
  rpc/src/rpc.rs
  runtime/src/commitment.rs
  sdk/src/commitment_config.rs
Labels: v2.0

#1993 Add suggestion to deprecation message
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
Labels: v1.18, v2.0

#1991 Bump ThinClient since version
  thin-client/README.md
  thin-client/src/thin_client.rs
Labels: v2.0

#1995 Remove assorted deprecated symbols
  gossip/src/cluster_info.rs
  program-test/src/lib.rs
  test-validator/src/lib.rs
Labels: v2.0

#1996 Remove rpc methods from mock sender
  rpc-client/src/mock_sender.rs
Labels: automerge, v2.0

#1824 Extract atomic-u64 crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/atomic-u64/Cargo.toml
  sdk/atomic-u64/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/blake3.rs
  sdk/program/src/hash.rs
  sdk/program/src/keccak.rs
  sdk/program/src/lib.rs
  sdk/program/src/pubkey.rs
Labels: automerge, need:merge-assist

#2004 Remove deprecated symbols from recent_blockhashes_account
  programs/system/src/system_processor.rs
  runtime/src/bank.rs
  runtime/src/bank/recent_blockhashes_account.rs
  sdk/src/lib.rs
Labels: v2.0

#2005 Deprecate RpcRequest::GetStakeActivation
  rpc-client-api/src/request.rs
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
Labels: automerge, v1.18, v2.0

#2011 [zk-token-sdk] Specify version in deprecations in `zk-token-sdk`
  zk-token-sdk/src/encryption/elgamal.rs
Labels: v2.0

#1992 Remove deprecated symbols from solana-client (mostly re-exports)
  Cargo.lock
  client/src/connection_cache.rs
  client/src/lib.rs
  client/src/nonblocking/mod.rs
  client/src/nonblocking/quic_client.rs
  client/src/nonblocking/tpu_connection.rs
  client/src/nonblocking/udp_client.rs
  client/src/quic_client.rs
  client/src/tpu_connection.rs
  client/src/udp_client.rs
  core/Cargo.toml
  core/src/banking_stage/forwarder.rs
  core/src/warm_quic_cache_service.rs
  dos/Cargo.toml
  dos/src/main.rs
  programs/sbf/Cargo.lock
  send-transaction-service/Cargo.toml
  send-transaction-service/src/send_transaction_service.rs
Labels: v2.0

#2006 Update changlog re: removal of deprecated symbols
  CHANGELOG.md
Labels: v2.0

#2003 Clean up disable_fees_sysvar feature
  programs/sbf/rust/sysvar/src/lib.rs
  programs/sbf/tests/sysvar.rs
  rpc-client-api/src/response.rs
  runtime/src/bank.rs
  runtime/src/bank/sysvar_cache.rs
  runtime/src/bank/tests.rs
  runtime/src/genesis_utils.rs
Labels: v2.0

#2036 Remove get_stake_activation methods from RpcClient
  rpc-client-api/src/request.rs
  rpc-client-api/src/response.rs
  rpc-client/src/mock_sender.rs
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
  rpc/src/rpc.rs
Labels: v2.0

#2025 Extract log collector crate
  .gitignore
  Cargo.lock
  Cargo.toml
  ledger-tool/Cargo.toml
  log-collector/Cargo.toml
  log-collector/src/lib.rs
  program-runtime/Cargo.toml
  program-runtime/src/invoke_context.rs
  program-runtime/src/lib.rs
  program-runtime/src/stable_log.rs
  program-test/Cargo.toml
  program-test/src/lib.rs
  programs/address-lookup-table/Cargo.toml
  programs/address-lookup-table/src/processor.rs
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/config/Cargo.toml
  programs/config/src/config_processor.rs
  programs/loader-v4/Cargo.toml
  programs/loader-v4/src/lib.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/stake/Cargo.toml
  programs/stake/src/stake_state.rs
  programs/system/Cargo.toml
  programs/system/src/system_instruction.rs
  programs/system/src/system_processor.rs
  programs/zk-elgamal-proof/Cargo.toml
  programs/zk-elgamal-proof/src/lib.rs
  programs/zk-token-proof/Cargo.toml
  programs/zk-token-proof/src/lib.rs
  svm/Cargo.toml
  svm/src/transaction_processor.rs
  svm/tests/conformance.rs
Labels: need:merge-assist

#2048 [zk-sdk] Keep ProofType consistent with ProofInstruction
  zk-sdk/src/zk_elgamal_proof_program/proof_data/mod.rs
Labels: community, need:merge-assist

#2060 Update install docs to agave
  docs/src/cli/install.md
Labels: v2.0

#1893 Fix BankForks::new_rw_arc memory leak
  bench-tps/src/bench.rs
  core/benches/banking_stage.rs
  core/benches/consumer.rs
  core/src/banking_stage.rs
  core/src/banking_stage/consume_worker.rs
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/decision_maker.rs
  core/src/banking_stage/read_write_account_set.rs
  core/src/banking_stage/unprocessed_transaction_storage.rs
  core/tests/unified_scheduler.rs
  ledger/benches/blockstore_processor.rs
  ledger/src/blockstore_processor.rs
  poh/src/poh_service.rs
  program-runtime/src/loaded_programs.rs
  programs/sbf/tests/programs.rs
  rpc/src/transaction_status_service.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  runtime/src/bank_client.rs
  runtime/src/bank_forks.rs
  runtime/tests/stake.rs
  stake-accounts/src/stake_accounts.rs
  svm/src/transaction_processor.rs
  svm/tests/conformance.rs
  svm/tests/integration_test.rs
  unified-scheduler-pool/src/lib.rs
Labels: v1.18, community, need:merge-assist, v2.0

#2050 Remove deprecated Memcmp filter symbols
  Cargo.lock
  rpc-client-api/Cargo.toml
  rpc-client-api/src/filter.rs
  rpc/src/rpc.rs
Labels: automerge, v2.0

#1756 docs: Move node hardware requirements to markdown table
  docs/src/operations/requirements.md
Labels: community, need:merge-assist

#1929 Remove some unused deps
  Cargo.lock
  accounts-cluster-bench/Cargo.toml
  bloom/Cargo.toml
  cli/Cargo.toml
  curves/curve25519/Cargo.toml
  net-utils/Cargo.toml
  programs/sbf/Cargo.lock
  transaction-dos/Cargo.toml
  transaction-metrics-tracker/Cargo.toml
  wen-restart/Cargo.toml
  zk-keygen/Cargo.toml
Labels: need:merge-assist

#2026 Extract timings crate
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/leader_slot_timing_metrics.rs
  core/src/replay_stage.rs
  core/tests/unified_scheduler.rs
  ledger/Cargo.toml
  ledger/benches/blockstore_processor.rs
  ledger/src/blockstore_processor.rs
  program-runtime/Cargo.toml
  program-runtime/src/invoke_context.rs
  program-runtime/src/lib.rs
  program-runtime/src/loaded_programs.rs
  program-test/Cargo.toml
  program-test/src/lib.rs
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/syscalls/mod.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/tests/programs.rs
  runtime/Cargo.toml
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  runtime/src/installed_scheduler_pool.rs
  svm/Cargo.toml
  svm/src/message_processor.rs
  svm/src/program_loader.rs
  svm/src/transaction_processor.rs
  svm/tests/conformance.rs
  timings/Cargo.toml
  timings/src/lib.rs
  unified-scheduler-pool/Cargo.toml
  unified-scheduler-pool/src/lib.rs
  wen-restart/Cargo.toml
  wen-restart/src/wen_restart.rs
Labels: automerge, need:merge-assist

#1971 blockstore: only consume duplicate proofs from root_slot + 1 on startup
  Cargo.lock
  core/Cargo.toml
  core/src/replay_stage.rs
  ledger/Cargo.toml
  ledger/src/blockstore_processor.rs
  programs/sbf/Cargo.lock
Labels: v1.18, v2.0

#1818 fix(geyser-plugin-manager): avoid SIGSEGV when plugin returns on_load…
  geyser-plugin-manager/src/geyser_plugin_manager.rs
Labels: community, need:merge-assist

#2121 Adds test for AppendVec::scan_index()
  accounts-db/src/append_vec.rs
Labels: automerge

#2093 accounts-db: throw error explicitly for next_account_offset calculation when overflows
  accounts-db/src/append_vec.rs
Labels: automerge

#2137 cli: enable geyser without specified configs
  validator/src/cli.rs
  validator/src/main.rs
Labels: need:merge-assist

#2086 replace solana-client with its constituent parts where possible
  Cargo.lock
  accounts-cluster-bench/Cargo.toml
  accounts-cluster-bench/src/main.rs
  bench-tps/src/bench.rs
  bench-tps/src/log_transaction_service.rs
  cli/Cargo.toml
  cli/src/compute_budget.rs
  cli/tests/program.rs
  gossip/Cargo.toml
  gossip/src/gossip_service.rs
  local-cluster/src/local_cluster.rs
  programs/sbf/Cargo.lock
  rpc-test/Cargo.toml
  rpc-test/tests/nonblocking.rs
  rpc-test/tests/rpc.rs
  send-transaction-service/src/tpu_info.rs
  test-validator/Cargo.toml
  test-validator/src/lib.rs
Labels: need:merge-assist

#2102 Update EpochRewards in sysvars doc
  docs/src/runtime/sysvars.md
Labels: v2.0

#1656 Move secp256k1_recover to its own crate
  Cargo.lock
  Cargo.toml
  curves/secp256k1-recover/Cargo.toml
  curves/secp256k1-recover/build.rs
  curves/secp256k1-recover/src/lib.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/rust/secp256k1_recover/Cargo.toml
  programs/sbf/rust/secp256k1_recover/src/lib.rs
  sdk/Cargo.toml
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/syscalls/definitions.rs
  sdk/src/lib.rs
Labels: need:merge-assist

#1796 Move short_vec to its own crate
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/banking_stage/immutable_deserialized_packet.rs
  core/src/consensus.rs
  core/src/consensus/tower1_14_11.rs
  gossip/Cargo.toml
  gossip/src/cluster_info.rs
  gossip/src/contact_info.rs
  perf/Cargo.toml
  perf/src/sigverify.rs
  programs/config/Cargo.toml
  programs/config/src/lib.rs
  programs/sbf/Cargo.lock
  programs/vote/src/vote_state/mod.rs
  sdk/Cargo.toml
  sdk/benches/short_vec.rs
  sdk/program/Cargo.toml
  sdk/program/src/instruction.rs
  sdk/program/src/lib.rs
  sdk/program/src/message/legacy.rs
  sdk/program/src/message/versions/mod.rs
  sdk/program/src/message/versions/v0/mod.rs
  sdk/program/src/serde_varint.rs
  sdk/program/src/vote/state/mod.rs
  sdk/src/lib.rs
  sdk/src/transaction/mod.rs
  sdk/src/transaction/versioned/mod.rs
  short-vec/Cargo.toml
  short-vec/build.rs
  short-vec/src/lib.rs
  transaction-metrics-tracker/Cargo.toml
  transaction-metrics-tracker/src/lib.rs
Labels: automerge, need:merge-assist

#1813 Extract decode-error from solana-program
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/cli.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/rust/error_handling/Cargo.toml
  programs/sbf/rust/error_handling/src/lib.rs
  sdk/Cargo.toml
  sdk/decode-error/Cargo.toml
  sdk/decode-error/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/program_error.rs
  sdk/program/src/pubkey.rs
  sdk/program/src/stake/instruction.rs
  sdk/program/src/system_instruction.rs
  sdk/program/src/vote/error.rs
  sdk/src/lib.rs
  sdk/src/precompiles.rs
Labels: automerge, need:merge-assist

#2162 ci: update docs pipeline
  .github/workflows/docs.yml
  docs/build.sh
  docs/src/operations/requirements.md
Labels: automerge, v2.0

#1505 [runtime] Fix build with musl
  runtime/src/serde_snapshot.rs
Labels: community, need:merge-assist

#2158 geyser: add num_partitions to block info
  core/src/replay_stage.rs
  geyser-plugin-interface/src/geyser_plugin_interface.rs
  geyser-plugin-manager/src/block_metadata_notifier.rs
  geyser-plugin-manager/src/block_metadata_notifier_interface.rs
  transaction-status/src/lib.rs
Labels: need:merge-assist, v2.0

#2035 Make quic endpoints count configurable
  gossip/src/cluster_info.rs
  streamer/src/nonblocking/quic.rs
  streamer/src/quic.rs
  validator/src/cli.rs
  validator/src/main.rs
Labels: v2.0

#2186 fix inline-spl deps
  Cargo.lock
  Cargo.toml
  inline-spl/Cargo.toml
  inline-spl/src/associated_token_account.rs
  inline-spl/src/token.rs
  inline-spl/src/token_2022.rs
  programs/sbf/Cargo.lock
Labels: automerge, need:merge-assist

#2161 geyser: build block info struct once
  geyser-plugin-manager/src/block_metadata_notifier.rs
Labels: need:merge-assist

#2101 replay: extend last fec set check for 32+ retransmitter signed shreds
  core/src/replay_stage.rs
  ledger/src/blockstore.rs
  ledger/src/blockstore_db.rs
  ledger/src/blockstore_processor.rs
  ledger/src/shred.rs
  sdk/src/feature_set.rs
Labels: v2.0

#2221 fix conditional borsh usage in compute_budget.rs
  sdk/src/compute_budget.rs
Labels: need:merge-assist

#2242 Update index.md
  docs/src/cli/index.md
Labels: need:merge-assist, v2.0

#2191 Add retries to `TpuLeaderService::new()`
  tpu-client/src/nonblocking/tpu_client.rs
Labels: automerge

#2105 AccountLocks use ahash
  Cargo.lock
  accounts-db/Cargo.toml
  accounts-db/src/accounts.rs
  programs/sbf/Cargo.lock
Labels: enhancement, automerge

#2090 Make clap optional for libraries
  banking-bench/Cargo.toml
  cli/Cargo.toml
  net-utils/Cargo.toml
  programs/sbf/Cargo.lock
  rpc-client-nonce-utils/Cargo.toml
  rpc-client-nonce-utils/src/blockhash_query.rs
  rpc-client-nonce-utils/src/nonblocking/blockhash_query.rs
Labels: community, need:merge-assist

#2016 extract solana-program-memory crate
  Cargo.lock
  Cargo.toml
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/syscalls/mod.rs
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/program-memory/Cargo.toml
  sdk/program-memory/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/account_info.rs
  sdk/program/src/lib.rs
  sdk/program/src/program_stubs.rs
  sdk/program/src/syscalls/definitions.rs
  sdk/src/lib.rs
Labels: need:merge-assist

#2177 refactor: new `ExecutedTransaction` struct to merge load and execution details
  banks-server/src/banks_server.rs
  core/src/banking_stage/committer.rs
  core/src/banking_stage/consumer.rs
  ledger-tool/src/main.rs
  ledger/src/blockstore_processor.rs
  programs/sbf/tests/programs.rs
  rpc/src/transaction_status_service.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  svm/doc/spec.md
  svm/src/account_loader.rs
  svm/src/account_saver.rs
  svm/src/transaction_processor.rs
  svm/src/transaction_results.rs
  svm/tests/conformance.rs
  svm/tests/integration_test.rs
Labels: automerge

#2185 refactor: remove redundant Rc<RefCell<T>> wrapper
  svm/src/transaction_processor.rs
Labels: community, need:merge-assist

#2301 Update Dockerfile with apt-get
  sdk/docker-solana/Dockerfile
Labels: community, need:merge-assist

#2288 Add lamports per signature field for registering recent blockhash for tests
  runtime/src/bank.rs
Labels: community, need:merge-assist

#2306 Add tx signature to ledger-tool verify --record-slots-config=tx
  ledger-tool/src/main.rs
  runtime/src/bank/bank_hash_details.rs
Labels: automerge

#2249 Add removed line from PR1192
  svm/src/transaction_processor.rs
Labels: need:merge-assist, v2.0

#2239 Update what-is-a-validator.md
  docs/src/what-is-a-validator.md
Labels: need:merge-assist

#2238 Update index.mdx
  docs/src/index.mdx
Labels: need:merge-assist, v2.0

#2241 Update backwards-compatibility.md
  docs/src/backwards-compatibility.md
Labels: need:merge-assist

#2240 Update faq.md
  docs/src/faq.md
Labels: need:merge-assist

#2345 Revert "Bump platform tools version to v1.42 (#2310)"
  sdk/cargo-build-sbf/src/main.rs
  sdk/sbf/scripts/install.sh
Labels: automerge

#2357 Refactor match and add test cases
  rpc-client-api/src/filter.rs
Labels: automerge, v2.0

#2358 Refactor match
  rpc-client-api/src/filter.rs
Labels: automerge

#1983 extract solana-msg crate
  Cargo.lock
  Cargo.toml
  ci/nits.sh
  programs/sbf/Cargo.lock
  sdk/msg/Cargo.toml
  sdk/msg/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/log.rs
  sdk/program/src/syscalls/definitions.rs
Labels: need:merge-assist
