Repository anza-xyz/agave, pull requests merged in 2024-03, with the labels that each got.

#66 blockstore_purge: fix inspect -> inspect_err
  ledger/src/blockstore/blockstore_purge.rs
Labels: automerge, community, need:merge-assist

#69 Rpc: deprecate `getStakeActivation` and make inactive_stake consistent
  rpc/src/rpc.rs
  rpc/src/rpc_service.rs
Labels: v1.18

#73 windows: Use vcpkg for openssl dep
  .github/workflows/release-artifacts.yml
Labels: v1.18

#95 Cli: improve vote-account vote-authority display
  cli-output/src/cli_output.rs
Labels: automerge

#110 Add support for partial tx batch unlocking
  runtime/src/transaction_batch.rs
Labels: automerge

#127 Update maximum credits awarded per vote from 8 to 16
  programs/vote/src/vote_state/mod.rs
  sdk/program/src/vote/state/mod.rs
  sdk/src/feature_set.rs
Labels: automerge, v1.18, community, need:merge-assist, feature-gate

#133 add precompile signature metrics to cost tracker
  cost-model/src/block_cost_limits.rs
  cost-model/src/cost_model.rs
  cost-model/src/cost_tracker.rs
  cost-model/src/transaction_cost.rs
  sdk/program/src/message/sanitized.rs
Labels: automerge, v1.17, v1.18

#155 Use agave prefix in scripts for pre-installed binaries
  multinode-demo/common.sh
Labels: automerge

#165 ci: fix Windows gh release pipeline
  .github/workflows/release-artifacts.yml
Labels: v1.17, v1.18

#204 [anza migration]: fix download path for cluster test
  net/net.sh
  scripts/agave-install-deploy.sh
Labels: automerge

#220 support Pubkey::to_bytes as constexpr
  sdk/program/src/pubkey.rs
Labels: community, need:merge-assist

#209 bench-tps: allow option to not set account data size on every transaction
  bench-tps/src/bench.rs
  bench-tps/src/cli.rs
  bench-tps/src/keypairs.rs
  bench-tps/src/main.rs
  bench-tps/src/send_batch.rs
  bench-tps/tests/bench_tps.rs
  dos/src/main.rs
Labels: community, need:merge-assist

#226 rpc: disable BigTable with header
  rpc/src/rpc.rs
  rpc/src/rpc_service.rs
Labels: community, need:merge-assist

#84 Add `reserved_account_keys` module to sdk
  sdk/src/feature_set.rs
  sdk/src/lib.rs
  sdk/src/reserved_account_keys.rs
Labels: feature-gate

#223 [anza migration]: add 'agave=info' to default log level
  accounts-db/store-tool/src/main.rs
  bench-tps/src/main.rs
  cargo-registry/src/main.rs
  dos/src/main.rs
  faucet/src/bin/faucet.rs
  gossip/src/main.rs
  ledger-tool/src/main.rs
  logger/src/lib.rs
  scripts/run.sh
  transaction-dos/src/main.rs
  validator/src/lib.rs
  watchtower/src/main.rs
Labels: v1.17, v1.18

#162 relax stake split destination check
  cli/src/stake.rs
Labels: community, need:merge-assist

#130 [zk-token-sdk] Implement `FromStr` for `ElGamalPubkey`, `ElGamalCiphertext`, and `AeCiphertext`
  zk-token-sdk/Cargo.toml
  zk-token-sdk/src/zk_token_elgamal/pod/auth_encryption.rs
  zk-token-sdk/src/zk_token_elgamal/pod/elgamal.rs
  zk-token-sdk/src/zk_token_elgamal/pod/mod.rs
Labels: need:merge-assist

#255 remove raptor coding experiments
  Cargo.lock
  core/Cargo.toml
  core/benches/shredder.rs
Labels: automerge

#253 Clean up require_rent_exempt_split_destination feature
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
Labels: feature-gate

#249 Use static memory layout for all sysvars
  sdk/program/src/epoch_rewards.rs
  sdk/program/src/fee_calculator.rs
  sdk/program/src/stake_history.rs
Labels: community, need:merge-assist

#264 fix typo
  local-cluster/tests/local_cluster.rs
Labels: automerge, community, need:merge-assist

#274 vote: deprecate unused legacy vote tx plumbing
  programs/vote/benches/process_vote.rs
  programs/vote/src/vote_state/mod.rs
  sdk/program/src/vote/state/mod.rs
  sdk/src/feature_set.rs
Labels: automerge, v1.17, v1.18

#234 [solana-install-init] Optimize error message for Windows user permission installation
  install/src/command.rs
Labels: community, need:merge-assist

#293 Make the quic server connection table use an async lock, reducing thrashing
  streamer/src/nonblocking/quic.rs
Labels: v1.17, v1.18

#277 cli: skip no-op program buffer writes
  cli/src/program.rs
Labels: v1.18

#322 vote: reuse ff to gate tvc constant update from 8 -> 16
  programs/vote/src/vote_state/mod.rs
  sdk/program/src/vote/state/mod.rs
Labels: automerge

#328 qos service should also accumulate executed but errored units
  core/src/banking_stage/consumer.rs
Labels: automerge

#309 Revert deprecate executable feature
  cli/src/program.rs
  cli/tests/program.rs
  ledger-tool/src/program.rs
  program-runtime/src/invoke_context.rs
  program-runtime/src/message_processor.rs
  program-test/src/lib.rs
  programs/address-lookup-table/src/processor.rs
  programs/bpf_loader/benches/serialization.rs
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/serialization.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/config/src/config_processor.rs
  programs/loader-v4/src/lib.rs
  programs/sbf/benches/bpf_loader.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  programs/system/src/system_instruction.rs
  programs/system/src/system_processor.rs
  programs/vote/src/vote_state/mod.rs
  programs/zk-token-proof/src/lib.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  sdk/src/account.rs
  sdk/src/feature_set.rs
  sdk/src/transaction_context.rs
  svm/src/account_loader.rs
Labels: v1.18

#197 rpc-sts: add config options for stake-weighted qos
  send-transaction-service/src/send_transaction_service.rs
  validator/src/cli.rs
  validator/src/main.rs
Labels: v1.17, v1.18

#178 Add functions to collect executed transactions fee in details;
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  sdk/src/fee.rs
Labels: automerge

#348 client: Start resending sooner during `send_and_confirm_transactions_in_parallel`
  client/src/send_and_confirm_transactions_in_parallel.rs
Labels: v1.18

#67 v1.17: blockstore: relax parent slot meta check for clear_unconfirmed_slot
  ledger/src/blockstore.rs
Labels: community, need:merge-assist

#266 Cli stake-split: adjust transfer amount if recipient has lamports
  cli/src/cli.rs
  cli/src/stake.rs
Labels: v1.18

#370 Discard packets statically known to fail
  core/src/banking_stage/immutable_deserialized_packet.rs
  core/src/banking_stage/packet_deserializer.rs
  core/src/banking_stage/packet_receiver.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: automerge, v1.17, v1.18

#335 Health check slot distance
  CHANGELOG.md
  validator/src/cli.rs
Labels: community, need:merge-assist

#358 client: Timeout resends during `send_and_confirm_in_parallel`
  client/src/send_and_confirm_transactions_in_parallel.rs
Labels: v1.18

#101 Fix: deploy program on last slot of epoch during environment change
  ledger-tool/src/program.rs
  program-runtime/src/invoke_context.rs
  program-runtime/src/loaded_programs.rs
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/loader-v4/src/lib.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
  svm/src/transaction_processor.rs
Labels: v1.18

#364 Add `--with-compute-unit-price` to cli program deploy commands
  Cargo.lock
  cli/Cargo.toml
  cli/src/program.rs
  cli/tests/program.rs
  transaction-dos/src/main.rs
Labels: automerge, v1.18

#403 Clarify TargetProgramBuiltin code docs
  runtime/src/bank/builtins/core_bpf_migration/target_builtin.rs
Labels: automerge

#153 frozen-abi-macro: use `log` from `solana_frozen_abi`
  frozen-abi/macro/src/lib.rs
  frozen-abi/src/lib.rs
Labels: do-not-close

#407 Update version to v1.17.29
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
  sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml
Labels: automerge

#406 Update version to v1.18.9
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
  sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml
Labels: automerge

#427 Simd 118: rekey partitioned epoch rewards feature
  sdk/src/feature_set.rs
Labels: feature-gate

#413 replace Vec::new() with Vec::with_capacity(2)
  svm/src/account_loader.rs
Labels: community, need:merge-assist

#272 prioritization fee cache: remove not required locks
  runtime/src/prioritization_fee.rs
  runtime/src/prioritization_fee_cache.rs
Labels: need:merge-assist

#30 prioritization fee cache: remove lru crate
  Cargo.lock
  programs/sbf/Cargo.lock
  runtime/Cargo.toml
  runtime/src/prioritization_fee.rs
  runtime/src/prioritization_fee_cache.rs
Labels: community, need:merge-assist

#466 ci: add release pipeline
  .github/workflows/release.yml
Labels: v1.17, v1.18

#493 ci: fix some issues for the release pipeline
  .github/workflows/release.yml
Labels: v1.17, v1.18
