Repository anza-xyz/agave, pull requests merged in 2025-09, with the labels that each got.

#7816 fix typos in .rs files
  perf/src/sigverify.rs
  turbine/src/cluster_nodes.rs
  turbine/src/retransmit_stage.rs
Labels: automerge, community, need:merge-assist

#7769 program-test: format error for core bpf
  program-test/src/lib.rs
Labels: automerge

#7807 program-runtime: drop metrics
  Cargo.lock
  program-runtime/Cargo.toml
  program-runtime/src/lib.rs
  program-runtime/src/loaded_programs.rs
  programs/sbf/Cargo.lock
Labels: v3.0

#7780 fix all2all catchup
  core/src/mock_alpenglow_consensus.rs
Labels: v3.0

#7758 optimize visit_zero_lamports at startup
  accounts-db/src/accounts_db.rs
Labels: v3.0

#7782 Subtract overflow in sort_shrink_indexes_by_bytes_saved
  accounts-db/src/ancient_append_vecs.rs
Labels: v2.3, v3.0

#7864 Fix test_skip_leader_slot_for_existing_slot
  core/src/replay_stage.rs
Labels: automerge

#7874 Rekey `reenable_zk_elgamal_proof_program` feature gate
  feature-set/src/lib.rs
Labels: v3.0

#7902 clean: remove broken bank benches
  runtime/benches/bank.rs
Labels: automerge

#7878 ledger: blockstore prepare for removing unchained
  ledger/src/blockstore.rs
Labels: community, need:merge-assist

#7920 CostTracker: Add a getter to expose cost by writable accounts
  cost-model/src/cost_tracker.rs
  cost-model/src/cost_tracker_post_analysis.rs
  cost-model/src/lib.rs
Labels: automerge, community, need:merge-assist

#7489 introduce cluster slots constructor / new default_for_tests api #7349
  core/src/cluster_slots_service/cluster_slots.rs
  core/src/repair/ancestor_hashes_service.rs
  core/src/repair/repair_service.rs
  core/src/repair/serve_repair.rs
  core/src/replay_stage.rs
  core/src/tvu.rs
  core/src/validator.rs
  core/src/vote_simulator.rs
  validator/Cargo.toml
  validator/src/admin_rpc_service.rs
Labels: community, need:merge-assist

#7976 Revert "move forwarding stage backed up warning to send-side (#7915)"
  core/src/forwarding_stage.rs
  core/src/sigverify.rs
Labels: v2.3, v3.0

#7909 resolve issue with local faucet overlapping ports in tests / new api
  Cargo.lock
  accounts-cluster-bench/Cargo.toml
  accounts-cluster-bench/src/main.rs
  bench-tps/Cargo.toml
  bench-tps/tests/bench_tps.rs
  cli/Cargo.toml
  cli/tests/address_lookup_table.rs
  cli/tests/cluster_query.rs
  cli/tests/nonce.rs
  cli/tests/program.rs
  cli/tests/request_airdrop.rs
  cli/tests/stake.rs
  cli/tests/transfer.rs
  cli/tests/validator_info.rs
  cli/tests/vote.rs
  dos/Cargo.toml
  dos/src/main.rs
  faucet/Cargo.toml
  faucet/src/faucet.rs
  faucet/tests/local-faucet.rs
  programs/sbf/Cargo.lock
Labels: community, need:merge-assist

#7940 tpu-client-next: Encapsulate WorkersCache implementation details
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/workers_cache.rs
Labels: community, need:merge-assist

#7845 Implement set_top_level_instruction_index
  transaction-context/src/lib.rs
Labels: community, need:merge-assist

#8068 validator: ditch call to old faucet test api in solana test validator
  validator/src/bin/solana-test-validator.rs
Labels: community, need:merge-assist

#7912 faucet: deprecate run_local_faucet and run_local_faucet_with_port
  faucet/src/faucet.rs
Labels: community, need:merge-assist

#8184 Update comment for write zero condition
  accounts-db/src/io_uring/file_creator.rs
Labels: v3.0
