Repository anza-xyz/agave, pull requests merged in 2025-02, with the labels that each got.

#4427 Reapply changes from reverted PR 3423: move structures to new modules
  send-transaction-service/src/lib.rs
  send-transaction-service/src/send_transaction_service.rs
  send-transaction-service/src/send_transaction_service_stats.rs
  send-transaction-service/src/transaction_client.rs
Labels: automerge

#4740 bench: update vote bench ixs currently being deprecated
  programs/vote/benches/process_vote.rs
Labels: automerge

#4570 add buffer pubkey to deployment error message
  cli/src/program.rs
Labels: community, need:merge-assist

#4753 Reapply 3515: rename `get_leader_tpus` and remove `get_leader_tpus_with_slots`
  rpc/src/cluster_tpu_info.rs
  send-transaction-service/src/tpu_info.rs
Labels: automerge

#4719 remove solana-program and solana-sdk from solana-stake-program
  Cargo.lock
  compute-budget-instruction/Cargo.toml
  cost-model/Cargo.toml
  entry/Cargo.toml
  programs/sbf/Cargo.lock
  programs/stake/Cargo.toml
  programs/stake/benches/stake.rs
  programs/stake/src/config.rs
  programs/stake/src/lib.rs
  programs/stake/src/points.rs
  programs/stake/src/rewards.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  runtime-transaction/Cargo.toml
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4790 prevent check-crates from crashing on PRs which do not touch any cargo.toml files
  sdk/scripts/check-crates.sh
Labels: automerge

#4788 Upgrades Rust to 1.84.1
  rust-toolchain.toml
Labels: automerge

#4754 Reapply 3515: Add new_with_client constructor to SendTransactionService
  Cargo.lock
  programs/sbf/Cargo.lock
  send-transaction-service/Cargo.toml
  send-transaction-service/src/lib.rs
  send-transaction-service/src/send_transaction_service.rs
  send-transaction-service/src/test_utils.rs
  send-transaction-service/src/transaction_client.rs
  svm/examples/Cargo.lock
Labels: automerge

#4756 chore: bump hermit-abi to 0.3.9
  Cargo.lock
  programs/sbf/Cargo.lock
Labels: automerge

#4757 chore: bump spin to 0.9.8
  Cargo.lock
  programs/sbf/Cargo.lock
Labels: automerge

#4766 move solana-program to dev deps of solana-bpf-loader-program
  Cargo.lock
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/loader-v4/Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4795 refactor: appendvec stat
  accounts-db/src/accounts_db/stats.rs
  accounts-db/src/append_vec.rs
Labels: automerge

#4712 pack pullresponses up to packet limit and outbound data budget
  gossip/src/cluster_info.rs
  gossip/src/cluster_info_metrics.rs
  gossip/src/protocol.rs
Labels: automerge

#4809 Fix CI failure with missing blake3 feature
  runtime-transaction/Cargo.toml
Labels: automerge

#4820 Ensure correct bind address is used during bootstrap checks for RPC
  net-utils/src/ip_echo_client.rs
  net-utils/src/lib.rs
  validator/src/bootstrap.rs
Labels: automerge

#4688 GreedyScheduler
  CHANGELOG.md
  core/src/banking_stage.rs
  core/src/banking_stage/transaction_scheduler/greedy_scheduler.rs
  core/src/banking_stage/transaction_scheduler/mod.rs
  core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
  core/src/banking_stage/transaction_scheduler/scheduler.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
  core/src/validator.rs
Labels: v2.1

#4829 Fix forwarding metric accumulation
  core/src/forwarding_stage.rs
Labels: automerge

#4837 Fixes log when snapshots are disabled
  validator/src/main.rs
Labels: automerge

#4825 fix: typos in documentation files
  ledger/src/shred/merkle.rs
  sdk/secp256r1-program/src/lib.rs
  zk-token-sdk/src/sigma_proofs/pubkey_proof.rs
Labels: community, need:merge-assist

#4847 ci: remove golang from the ci image
  ci/docker/Dockerfile
  ci/docker/build.sh
  ci/docker/env.sh
Labels: automerge

#4862 sdk: Patch solana-decode-error
  sdk/Cargo.lock
  sdk/Cargo.toml
Labels: automerge

#4865 Scheduler: earlier fee check on receive
  core/src/banking_stage/transaction_scheduler/receive_and_buffer.rs
Labels: v2.1

#4872 ci: private pipeline use default queue
  ci/buildkite-solana-private.sh
Labels: automerge

#4924 Fix - loader-v4 deployment buffer funds retrieval
  programs/loader-v4/src/lib.rs
Labels: v2.2

#4926 refactor: `PohRecorder::leader_first_tick_height`
  poh/src/poh_recorder.rs
Labels: automerge

#4944 ci: use ssl 3.4.1 for Windows
  .github/scripts/install-openssl.sh
  .github/workflows/cargo.yml
Labels: v2.1, v2.2

#4934 ci: use ubuntu-22.04 github runner
  .github/workflows/client-targets.yml
  .github/workflows/crate-check.yml
  .github/workflows/docs.yml
  .github/workflows/error-reporting.yml
  .github/workflows/release-artifacts.yml
Labels: v2.1, v2.2

#3134 Updated validator docs
  docs/src/operations/best-practices/general.md
  docs/src/operations/best-practices/security.md
  docs/src/operations/prerequisites.md
  docs/src/operations/requirements.md
Labels: community, need:merge-assist

#4969 sdk: Bump all SDK crates for relaxed dependencies
  Cargo.lock
  Cargo.toml
  programs/bpf_loader/src/lib.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  svm/examples/Cargo.lock
  svm/examples/Cargo.toml
  transaction-status/src/parse_bpf_loader.rs
Labels: automerge, v2.2

#4974 chore: update solana-feature-set to v2.2.4
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  svm/examples/Cargo.lock
Labels: automerge

#4975 chore: update solana-vote-interface to v2.2.2
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge

#4968 refactor: PohRecorderMetrics
  poh/src/poh_recorder.rs
Labels: automerge

#4992 Feature - Adds `UpgradeableLoaderInstruction::Migrate` (#4661)
  Cargo.lock
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/lib.rs
  runtime/Cargo.toml
  runtime/src/bank/tests.rs
  transaction-status/src/parse_bpf_loader.rs
Labels: v2.2

#5009 add rust-version 1.83 to net-utils
  net-utils/Cargo.toml
Labels: automerge, need:merge-assist

#4483 Cli: withdraw available stake with keyword
  clap-utils/src/input_validators.rs
  cli/src/cli.rs
  cli/src/spend_utils.rs
  cli/src/stake.rs
  cli/tests/stake.rs
Labels: community, need:merge-assist

#5005 remove solana-sdk from genesis
  Cargo.lock
  genesis/Cargo.toml
  genesis/src/address_generator.rs
  genesis/src/genesis_accounts.rs
  genesis/src/main.rs
  genesis/src/stakes.rs
  genesis/src/unlocks.rs
Labels: automerge, need:merge-assist

#4986 remove solana-sdk from gossip
  Cargo.lock
  gossip/Cargo.toml
  gossip/benches/crds_gossip_pull.rs
  gossip/benches/crds_shards.rs
  gossip/src/cluster_info.rs
  gossip/src/cluster_info_metrics.rs
  gossip/src/contact_info.rs
  gossip/src/crds.rs
  gossip/src/crds_data.rs
  gossip/src/crds_entry.rs
  gossip/src/crds_gossip.rs
  gossip/src/crds_gossip_pull.rs
  gossip/src/crds_gossip_push.rs
  gossip/src/crds_shards.rs
  gossip/src/crds_value.rs
  gossip/src/deprecated.rs
  gossip/src/duplicate_shred.rs
  gossip/src/duplicate_shred_handler.rs
  gossip/src/duplicate_shred_listener.rs
  gossip/src/epoch_slots.rs
  gossip/src/epoch_specs.rs
  gossip/src/gossip_service.rs
  gossip/src/ping_pong.rs
  gossip/src/protocol.rs
  gossip/src/push_active_set.rs
  gossip/src/restart_crds_values.rs
  gossip/src/weighted_shuffle.rs
  gossip/tests/crds_gossip.rs
  gossip/tests/gossip.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#5102 changelog: Geyser account notifications at startup
  CHANGELOG.md
Labels: automerge
