Repository anza-xyz/agave, pull requests merged in 2025-05, with the labels that each got.

#6070 Revert "Enables experimental accumulator hash by default (#6058)"
  ledger-tool/src/args.rs
  validator/src/commands/run/execute.rs
Labels: automerge

#6078 Refactors usage for CleaningInfo
  accounts-db/src/accounts_db.rs
Labels: automerge

#6039 remove solana-sdk from accounts-cluster-bench
  Cargo.lock
  accounts-cluster-bench/Cargo.toml
  accounts-cluster-bench/src/main.rs
Labels: need:merge-assist

#5969 Fix typos in documentation comments
  geyser-plugin-manager/src/geyser_plugin_service.rs
  zk-token-sdk/src/zk_token_proof_instruction.rs
Labels: community, need:merge-assist

#6104 Removes --accounts-db-squash-storages-method
  ledger-tool/src/args.rs
  validator/src/commands/run/args.rs
  validator/src/commands/run/execute.rs
Labels: automerge

#6117 rename udp socket for forwarding transactions
  core/src/tpu.rs
  core/src/validator.rs
  gossip/src/cluster_info.rs
Labels: automerge

#6106 Fix - Loader-v3 to v4 migration of closed programs
  feature-set/src/lib.rs
  programs/bpf_loader/src/lib.rs
  programs/loader-v4/src/lib.rs
Labels: feature-gate, v2.2

#5757 `feat` : allow rpc mock to insert multiple duplicate requests
  rpc-client/src/mock_sender.rs
  rpc-client/src/nonblocking/rpc_client.rs
  rpc-client/src/rpc_client.rs
Labels: community, need:merge-assist

#5731 blockstore: update tests that are using legacy shreds
  ledger/src/blockstore.rs
Labels: help wanted

#6158 include existing zero lamport in duplicates
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
Labels: v2.2

#6142 docs: fix docker link
  docker-solana/README.md
  docs/src/operations/requirements.md
Labels: v2.2

#6166 blockstore: Adjust rocksdb threadpool config
  ledger/src/blockstore_db.rs
Labels: v2.2

#6180 docs: fix docker link
  docker-solana/README.md
  docs/src/operations/requirements.md
Labels: v2.2

#5202 geyser: add parent to dead slot status
  core/src/replay_stage.rs
  geyser-plugin-manager/src/slot_status_notifier.rs
  rpc/src/slot_status_notifier.rs
Labels: need:merge-assist

#6178 chore: fixed typo 'gesyer' to 'geyser'
  validator/src/commands/plugin/mod.rs
Labels: community, need:merge-assist

#6195 switch to rpc-client-types in pubsub-client
  Cargo.lock
  programs/sbf/Cargo.lock
  pubsub-client/Cargo.toml
  pubsub-client/src/nonblocking/pubsub_client.rs
  pubsub-client/src/pubsub_client.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#6133 Removing unnecessary mutex in the bank client code
  runtime/src/bank_client.rs
Labels: need:merge-assist

#6226 remove references to solana_sdk::net::DEFAULT_TPU_COALESCE
  Cargo.lock
  core/src/tpu.rs
  streamer/Cargo.toml
  streamer/src/quic.rs
  validator/src/commands/run/execute.rs
  vortexor/Cargo.toml
  vortexor/src/cli.rs
  vortexor/tests/vortexor.rs
Labels: automerge

#6198 ci: fix release pipeline
  scripts/increment-cargo-version.sh
Labels: v2.1, v2.2

#6240 deps: bump solana-feature-gate-interface
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  genesis/Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, v2.2

#4988 cli: fix sol parsing
  clap-utils/src/input_parsers.rs
Labels: need:merge-assist

#6247 chore: update quinn-proto in Cargo.toml
  Cargo.toml
Labels: automerge

#6254 transaction-context: enhance instruction index writing safety
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  transaction-context/Cargo.toml
  transaction-context/src/lib.rs
Labels: automerge

#6252 Bump platform tools to v1.48
  platform-tools-sdk/cargo-build-sbf/src/main.rs
  platform-tools-sdk/cargo-build-sbf/tests/crates/package-metadata/Cargo.toml
  platform-tools-sdk/cargo-build-sbf/tests/crates/workspace-metadata/Cargo.toml
  platform-tools-sdk/sbf/scripts/install.sh
  programs/sbf/Cargo.toml
  programs/sbf/Makefile
  programs/sbf/rust/invoke/Cargo.toml
  programs/sbf/rust/invoke/src/lib.rs
Labels: v2.2

#6294 reduce refresh interval on solana catchup
  cli/src/cluster_query.rs
Labels: community, need:merge-assist

#6284 [docs] Fix link in zk-elgamal-proof.md
  docs/src/runtime/zk-elgamal-proof.md
Labels: community, need:merge-assist

#6346 docs: fix typos
  wen-restart/src/wen_restart.rs
  zk-sdk/src/encryption/elgamal.rs
  zk-sdk/src/zk_elgamal_proof_program/instruction.rs
Labels: community, need:merge-assist

#6364 Remove unused `solana-package-metadata*` crates from root `Cargo.toml`
  Cargo.toml
Labels: automerge
