Repository anza-xyz/agave, pull requests merged in 2025-04, with the labels that each got.

#5611 Move EvictingSender into the streamer crate for reuse
  gossip/src/cluster_info.rs
  gossip/src/gossip_service.rs
  streamer/src/evicting_sender.rs
  streamer/src/lib.rs
Labels: automerge

#5604 refactor: rm unnecessary vote_needs_store field
  runtime/src/bank.rs
  runtime/src/bank/partitioned_epoch_rewards/calculation.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
  runtime/src/bank/tests.rs
Labels: automerge

#5618 remove solana-program from transaction-status deps
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  transaction-status/Cargo.toml
  transaction-status/src/parse_address_lookup_table.rs
  transaction-status/src/parse_bpf_loader.rs
  transaction-status/src/parse_stake.rs
  transaction-status/src/parse_vote.rs
Labels: need:merge-assist

#5625 Renames AccountsIndexIterator::items
  accounts-db/src/accounts_index/iter.rs
Labels: automerge

#5627 Adds AtomicRefCount alias
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/account_map_entry.rs
Labels: automerge

#5624 Renames bin_start_and_len()
  accounts-db/src/accounts_index.rs
Labels: automerge

#5628 spl: Update to newest token-2022 binary on mainnet
  fetch-spl.sh
  program-test/src/programs.rs
  program-test/src/programs/spl_token_2022-5.0.2.so
  program-test/src/programs/spl_token_2022-8.0.0.so
Labels: v2.2

#5623 Refactor - program-v4 CLI usability
  cli/src/program_v4.rs
  cli/tests/program.rs
Labels: v2.2

#5406 Recover from cost/PoH errs by task/session renewal
  Cargo.lock
  programs/sbf/Cargo.lock
  runtime/Cargo.toml
  runtime/src/bank.rs
  runtime/src/installed_scheduler_pool.rs
  svm/examples/Cargo.lock
  unified-scheduler-logic/src/lib.rs
  unified-scheduler-pool/Cargo.toml
  unified-scheduler-pool/src/lib.rs
Labels: community, need:merge-assist

#5653 bump openssl to 0.10.72 and openssl-sys to 0.9.107
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge

#5669 clippy: doc_overindented_list_items
  accounts-db/src/accounts_db.rs
  clap-utils/src/keypair.rs
  clap-v3-utils/src/keypair.rs
  geyser-plugin-manager/src/geyser_plugin_service.rs
Labels: automerge

#5670 Add --tvu-retransmit-threads argument
  gossip/src/cluster_info.rs
  turbine/src/retransmit_stage.rs
  validator/src/cli/thread_args.rs
  validator/src/commands/run/execute.rs
Labels: v2.2

#5495 feat: conditionally expose sysvar_cache field in TransactionBatchProcessor
  svm/src/transaction_processor.rs
Labels: automerge, community, need:merge-assist

#5696 Make BP sessions race-free with poh by (un)pausing
  core/tests/unified_scheduler.rs
  programs/sbf/Cargo.lock
  runtime/Cargo.toml
  runtime/src/installed_scheduler_pool.rs
  svm/examples/Cargo.lock
  unified-scheduler-pool/src/lib.rs
Labels: need:merge-assist

#5707 Configure number of BV and BP threads separately
  core/src/banking_stage/unified_scheduler.rs
  core/tests/unified_scheduler.rs
  unified-scheduler-pool/src/lib.rs
Labels: automerge, need:merge-assist

#5698 Refactor - `TransactionContext` guards `AccountSharedData`
  Cargo.lock
  program-runtime/src/serialization.rs
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  svm/src/message_processor.rs
  transaction-context/Cargo.toml
  transaction-context/src/lib.rs
Labels: v2.2

#5619 remove solana-program from account-decoder
  Cargo.lock
  account-decoder/Cargo.toml
  account-decoder/src/parse_account_data.rs
  account-decoder/src/parse_address_lookup_table.rs
  account-decoder/src/parse_bpf_loader.rs
  account-decoder/src/parse_config.rs
  account-decoder/src/parse_stake.rs
  account-decoder/src/parse_vote.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#5723 rekey verify_retransmitter_signature and drop_unchained_merkle_shreds
  feature-set/src/lib.rs
Labels: v2.1, v2.2

#5722 fix release reverting to draft during asset push
  .github/workflows/publish-windows-tarball.yml
Labels: v2.1, v2.2

#5735 rolls out chained Merkle shreds to 100% of mainnet slots
  turbine/src/broadcast_stage/standard_broadcast_run.rs
Labels: v2.2

#5736 turbine: removes chained merkle shreds activation logic
  turbine/src/broadcast_stage/standard_broadcast_run.rs
Labels: automerge

#5759 Refactor - Marks `TransactionAccounts::get()` as private.
  programs/sbf/Cargo.toml
  programs/sbf/tests/programs.rs
  transaction-context/src/lib.rs
Labels: v2.2

#5765 Remove Precompile Alignment check/requirement
  precompiles/Cargo.toml
  precompiles/src/ed25519.rs
  precompiles/src/lib.rs
  precompiles/src/secp256k1.rs
  precompiles/src/secp256r1.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, v2.2

#5781 fix: in banking stage, enforce max num checks in clean_queue
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: community, need:merge-assist, v2.1, v2.2

#5800 Remove feature mask_out_rent_epoch_in_vm_serialization lookup in ledger-tool
  ledger-tool/src/program.rs
Labels: automerge

#5809 Add solana-transaction-context to workspace members list
  Cargo.toml
Labels: v2.2

#5830 RPC/STS: use client UdpSocket created in client_info
  Cargo.lock
  core/src/validator.rs
  gossip/src/cluster_info.rs
  rpc/src/rpc_service.rs
  send-transaction-service/Cargo.toml
  send-transaction-service/src/test_utils.rs
  send-transaction-service/src/transaction_client.rs
Labels: automerge

#5856 Revert "make test-validator bind to localhost by default (#5802)"
  gossip/src/cluster_info.rs
  test-validator/src/lib.rs
  validator/src/bin/solana-test-validator.rs
  validator/src/cli.rs
Labels: automerge

#5873 docs: remove consecutive duplicate words
  storage-bigtable/proto/google.bigtable.v2.rs
  svm/tests/integration_test.rs
Labels: community, need:merge-assist

#5674 Set build target to minimum supported cpu
  Cargo.toml
Labels: community, need:merge-assist

#5883 ZK Fix - hash the scalar proof components into the transcript
  zk-sdk/src/range_proof/mod.rs
  zk-sdk/src/sigma_proofs/ciphertext_ciphertext_equality.rs
  zk-sdk/src/sigma_proofs/ciphertext_commitment_equality.rs
  zk-sdk/src/sigma_proofs/grouped_ciphertext_validity/handles_2.rs
  zk-sdk/src/sigma_proofs/grouped_ciphertext_validity/handles_3.rs
  zk-sdk/src/sigma_proofs/percentage_with_cap.rs
  zk-sdk/src/sigma_proofs/zero_ciphertext.rs
Labels: v2.1, v2.2

#5846 Clean unified scheduler code after bp wiring
  Cargo.lock
  ledger/src/blockstore_processor.rs
  programs/sbf/Cargo.lock
  runtime/src/bank_forks.rs
  runtime/src/installed_scheduler_pool.rs
  svm/examples/Cargo.lock
  unified-scheduler-pool/Cargo.toml
  unified-scheduler-pool/src/lib.rs
Labels: automerge, need:merge-assist

#5896 Bugfix: scheduling_details report
  core/src/banking_stage/transaction_scheduler/scheduler_metrics.rs
Labels: bug

#5851 agave-install: align style across help messages
  install/src/lib.rs
Labels: community, need:merge-assist

#5695 adds benchmarks for recovering (chained) Merkle shreds from erasure codes
  ledger/benches/make_shreds_from_entries.rs
  ledger/src/shred.rs
Labels: community, need:merge-assist

#5917 Report leader blocks cost-tracker-stats to metrics w tag
  core/src/cost_update_service.rs
  core/src/replay_stage.rs
  cost-model/src/cost_tracker.rs
Labels: v2.2

#5907 deprecate discover_cluster which automatically uses shred_version 0
  gossip/src/gossip_service.rs
  local-cluster/src/cluster_tests.rs
  local-cluster/src/integration_tests.rs
  local-cluster/src/local_cluster.rs
  local-cluster/tests/local_cluster.rs
  test-validator/src/lib.rs
Labels: automerge

#5899 ci: add more selection rules for filtering Cargo.lock
  scripts/increment-cargo-version.sh
Labels: v2.1, v2.2

#5946 Update Readme.md
  vortexor/Readme.md
Labels: community, need:merge-assist

#5976 Fix unused import warning: move import to test module
  streamer/src/recvmmsg.rs
Labels: automerge

#5974 When Mergify warns people to update the JS RPC client, it now calls it `@solana/kit` instead of `@solana/web3.js`
  .mergify.yml
Labels: automerge

#5704 deps: Relax spl dependencies
  .github/workflows/downstream-project-spl.yml
  Cargo.toml
  bench-tps/Cargo.toml
  cli/Cargo.toml
  faucet/Cargo.toml
  svm/examples/Cargo.toml
  tokens/Cargo.toml
Labels: v2.2

#5986 gossip: Inherit all dependencies from the workspace
  gossip/Cargo.toml
Labels: automerge

#5968 Feature - Remove loader v4 instruction deploy from source
  Cargo.lock
  cli/src/program_v4.rs
  feature-set/src/lib.rs
  programs/loader-v4/src/lib.rs
  programs/sbf/Cargo.lock
  programs/sbf/tests/programs.rs
  runtime/Cargo.toml
  runtime/src/loader_utils.rs
  svm/examples/Cargo.lock
Labels: feature-gate, v2.2

#5985 update to shredder bench to merkle shreds
  core/benches/shredder.rs
Labels: automerge

#6003 rpc: remove intermediate allocations in getInflationReward
  rpc/src/rpc.rs
Labels: need:merge-assist

#5850 agave-install: swap lazy_static import with std::sync::LazyLock
  Cargo.lock
  install/Cargo.toml
  install/src/defaults.rs
  install/src/lib.rs
Labels: community, need:merge-assist
