Repository anza-xyz/agave, pull requests merged in 2025-06, with the labels that each got.

#6125 genesis: create EpochRewards at epoch 0
  programs/stake/src/config.rs
  programs/stake/src/epoch_rewards.rs
  programs/stake/src/lib.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
Labels: v2.2

#6376 Imports std:: types in AccountsBackgroundService
  runtime/src/accounts_background_service.rs
Labels: automerge

#6371 add methods to deconstruct RuntimeTransaction, ResolvedTransactionView, TransactionView
  runtime-transaction/src/runtime_transaction.rs
  transaction-view/src/resolved_transaction_view.rs
  transaction-view/src/transaction_view.rs
Labels: community, need:merge-assist

#6063 SIMD-0186: Loaded Transaction Data Sizes
  feature-set/src/lib.rs
  runtime/src/bank/tests.rs
  svm-feature-set/src/lib.rs
  svm/src/account_loader.rs
  svm/src/transaction_processor.rs
  svm/tests/integration_test.rs
Labels: feature-gate

#6414 fix leaders_fanout.connect configuration for sts
  send-transaction-service/src/transaction_client.rs
Labels: automerge

#6419 Revert "Add optional FeatureSet arg to `Bank::new_from_fields()` (#6399)"
  runtime/src/bank.rs
  runtime/src/serde_snapshot.rs
Labels: automerge

#5867 chore: wipe deprecated functions from net-utils
  net-utils/src/lib.rs
Labels: 3.0

#6447 feature-set: Inherit package version from workspace
  feature-set/Cargo.toml
Labels: v2.3

#6479 rpc: Ensure TransactionStatusService receives frozen banks
  core/src/replay_stage.rs
  rpc/src/transaction_status_service.rs
Labels: v2.3

#6440 Add feature to svm deps
  svm/Cargo.toml
Labels: v2.3

#6523 [zk-sdk] Add `c_max_proof` to the sigma proof transcript and add features to disable and reenable zk elgamal proof program
  Cargo.lock
  feature-set/src/lib.rs
  programs/sbf/Cargo.lock
  programs/zk-elgamal-proof/Cargo.toml
  programs/zk-elgamal-proof/src/lib.rs
  svm-feature-set/src/lib.rs
  svm/examples/Cargo.lock
  zk-sdk/src/sigma_proofs/percentage_with_cap.rs
Labels: v2.2, v2.3

#6544 Revert "[zk-sdk] Add `c_max_proof` to the sigma proof transcript and …
  Cargo.lock
  feature-set/src/lib.rs
  programs/sbf/Cargo.lock
  programs/zk-elgamal-proof/Cargo.toml
  programs/zk-elgamal-proof/src/lib.rs
  svm-feature-set/src/lib.rs
  svm/examples/Cargo.lock
  zk-sdk/src/sigma_proofs/percentage_with_cap.rs
Labels: automerge

#6395 add change to CHANGELOG for #6023
  CHANGELOG.md
Labels: v2.3

#6545 [zk-sdk] Add feature gates to disable and reenable zk elgamal proof program
  Cargo.lock
  feature-set/src/lib.rs
  programs/sbf/Cargo.lock
  programs/zk-elgamal-proof/Cargo.toml
  programs/zk-elgamal-proof/src/lib.rs
  svm-feature-set/src/lib.rs
  svm/examples/Cargo.lock
Labels: v2.2, v2.3

#6444 Fix - `test_cpi_account_ownership_writability()`
  programs/sbf/rust/invoke/src/lib.rs
  programs/sbf/tests/programs.rs
Labels: v2.3

#6566 ledger, tests: move test_multi_fec_block_coding to merkle variant
  ledger/tests/shred.rs
Labels: community, need:merge-assist

#6569 CI: keyword required for correct crate ordering
  ci/order-crates-for-publishing.py
Labels: v2.2

#6513 refactor: simplify release-with-lto profile
  Cargo.toml
Labels: community, need:merge-assist

#6594 chore: typo fixes
  local-cluster/tests/local_cluster.rs
  storage-bigtable/proto/google.api.rs
Labels: community, need:merge-assist

#6577 Remove conditional feature as it is not supported
  svm/Cargo.toml
Labels: v2.2, v2.3

#6608 fix: update SOL/lamports doc link to point directly to lamports section
  docs/src/operations/guides/validator-start.md
Labels: community, need:merge-assist

#6562 `ProgramCacheForTxBatch::find`: only find in `entries` if not found in `modified_entries`
  program-runtime/src/loaded_programs.rs
Labels: community, need:merge-assist

#6470 Apply minor code reformatting to cleaner_main_loop
  unified-scheduler-pool/src/lib.rs
Labels: automerge, need:merge-assist

#6640 `BankingStage::new_num_threads`: rm useless match
  core/src/banking_stage.rs
Labels: community, need:merge-assist

#6713 ledger, tests: remove remaining parts of legacy shreds in shred tests
  ledger/tests/shred.rs
Labels: community, need:merge-assist

#6691 fix logic in version bump script
  scripts/increment-cargo-version.sh
Labels: v2.2, v2.3

#6682 dont call epoch info always
  tpu-client/src/nonblocking/tpu_client.rs
Labels: community, need:merge-assist, v2.3

#4728 Deprecate blockstore-processor for --block-verification-method
  CHANGELOG.md
  validator/src/commands/run/execute.rs
Labels: v2.3

#6732 core, bench: move bench_deserialize_hdr to merkle variant
  core/benches/shredder.rs
Labels: community, need:merge-assist

#6729 turbine, bench: move cluster_info::broadcast_shreds_bench to merkle shreds
  turbine/benches/cluster_info.rs
Labels: community, need:merge-assist

#6764 Update Solana staking economics link to current official URL
  docs/src/operations/guides/vote-accounts.md
Labels: community, need:merge-assist
