Repository anza-xyz/agave, pull requests merged in 2025-01, with the labels that each got.

#4175 remove solana-sdk from runtime-transaction
  Cargo.lock
  programs/sbf/Cargo.lock
  runtime-transaction/Cargo.toml
  runtime-transaction/benches/get_signature_details.rs
  runtime-transaction/src/runtime_transaction.rs
  runtime-transaction/src/runtime_transaction/sdk_transactions.rs
  runtime-transaction/src/runtime_transaction/transaction_view.rs
  runtime-transaction/src/signature_details.rs
  runtime-transaction/src/transaction_meta.rs
  runtime-transaction/src/transaction_with_meta.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4176 remove solana-sdk from cost-model
  Cargo.lock
  cost-model/Cargo.toml
  cost-model/benches/cost_model.rs
  cost-model/benches/cost_tracker.rs
  cost-model/src/cost_model.rs
  cost-model/src/cost_tracker.rs
  cost-model/src/transaction_cost.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4178 minimize solana-sdk usage in account-decoder
  Cargo.lock
  account-decoder/Cargo.toml
  account-decoder/src/lib.rs
  account-decoder/src/parse_account_data.rs
  account-decoder/src/parse_address_lookup_table.rs
  account-decoder/src/parse_bpf_loader.rs
  account-decoder/src/parse_config.rs
  account-decoder/src/parse_nonce.rs
  account-decoder/src/parse_stake.rs
  account-decoder/src/parse_sysvar.rs
  account-decoder/src/parse_token.rs
  account-decoder/src/parse_token_extension.rs
  account-decoder/src/parse_vote.rs
  account-decoder/src/validator_info.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4180 Reduce usage of solana-sdk in accounts-db
  Cargo.lock
  accounts-db/Cargo.toml
  accounts-db/benches/accounts.rs
  accounts-db/src/account_storage.rs
  accounts-db/src/accounts.rs
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_db/geyser_plugin_utils.rs
  accounts-db/src/accounts_db/scan_account_storage.rs
  accounts-db/src/accounts_db/tests.rs
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
  accounts-db/src/accounts_partition.rs
  accounts-db/src/ancestors.rs
  accounts-db/src/ancient_append_vecs.rs
  accounts-db/src/append_vec.rs
  accounts-db/src/cache_hash_data.rs
  accounts-db/src/epoch_accounts_hash.rs
  accounts-db/src/epoch_accounts_hash/manager.rs
  accounts-db/src/pubkey_bins.rs
  accounts-db/src/rolling_bit_field.rs
  accounts-db/src/sorted_storages.rs
  accounts-db/src/stake_rewards.rs
  accounts-db/src/tiered_storage/footer.rs
  accounts-db/src/tiered_storage/index.rs
  accounts-db/src/tiered_storage/meta.rs
  accounts-db/src/tiered_storage/owners.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4181 replace solana_sdk::pubkey with solana_pubkey in solana-runtime
  Cargo.lock
  programs/sbf/Cargo.lock
  runtime/Cargo.toml
  runtime/benches/accounts.rs
  runtime/benches/prioritization_fee_cache.rs
  runtime/src/account_saver.rs
  runtime/src/bank/tests.rs
  runtime/src/bank_client.rs
  runtime/src/epoch_stakes.rs
  runtime/src/genesis_utils.rs
  runtime/src/installed_scheduler_pool.rs
  runtime/src/non_circulating_supply.rs
  runtime/src/prioritization_fee.rs
  runtime/src/prioritization_fee_cache.rs
  runtime/src/root_bank_cache.rs
  runtime/src/serde_snapshot/tests.rs
  runtime/src/snapshot_minimizer.rs
  runtime/src/stake_weighted_timestamp.rs
  runtime/src/stakes.rs
  runtime/src/stakes/serde_stakes.rs
  runtime/src/static_ids.rs
  runtime/src/transaction_batch.rs
  runtime/tests/accounts.rs
  runtime/tests/stake.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4182 replace solana_sdk::pubkey with solana_pubkey in solana-core
  Cargo.lock
  core/Cargo.toml
  core/benches/forwarder.rs
  core/src/banking_stage.rs
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/decision_maker.rs
  core/src/banking_stage/forward_packet_batches_by_accounts.rs
  core/src/banking_stage/forwarder.rs
  core/src/banking_stage/immutable_deserialized_packet.rs
  core/src/banking_stage/leader_slot_metrics.rs
  core/src/banking_stage/qos_service.rs
  core/src/banking_stage/read_write_account_set.rs
  core/src/banking_stage/transaction_scheduler/thread_aware_account_locks.rs
  core/src/banking_stage/transaction_scheduler/transaction_state.rs
  core/src/banking_stage/transaction_scheduler/transaction_state_container.rs
  core/src/banking_stage/unprocessed_packet_batches.rs
  core/src/banking_stage/unprocessed_transaction_storage.rs
  core/src/cluster_info_vote_listener.rs
  core/src/cluster_slots_service/cluster_slots.rs
  core/src/commitment_service.rs
  core/src/consensus.rs
  core/src/consensus/progress_map.rs
  core/src/consensus/vote_stake_tracker.rs
  core/src/gen_keys.rs
  core/src/optimistic_confirmation_verifier.rs
  core/src/repair/serve_repair.rs
  core/src/replay_stage.rs
  core/src/staked_nodes_updater_service.rs
  core/src/warm_quic_cache_service.rs
  core/tests/snapshots.rs
  core/tests/unified_scheduler.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4198 Add `writable` permission description for some ubpfl instructions
  sdk/program/src/loader_upgradeable_instruction.rs
Labels: community, need:merge-assist

#4183 replace solana_sdk::pubkey with solana_pubkey in solana-cli
  Cargo.lock
  cli/Cargo.toml
  cli/src/checks.rs
  cli/src/cli.rs
  cli/src/nonce.rs
  cli/src/stake.rs
  cli/src/validator_info.rs
  cli/src/vote.rs
  cli/tests/nonce.rs
  cli/tests/vote.rs
Labels: automerge, need:merge-assist

#4237 replace solana_sdk::pubkey with solana_pubkey in rpc
  Cargo.lock
  programs/sbf/Cargo.lock
  rpc/Cargo.toml
  rpc/src/optimistically_confirmed_bank_tracker.rs
  rpc/src/rpc.rs
  rpc/src/rpc_pubsub.rs
  rpc/src/rpc_subscriptions.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4236 replace solana_sdk::pubkey with solana_pubkey in transaction-status
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  transaction-status/Cargo.toml
  transaction-status/src/extract_memos.rs
  transaction-status/src/parse_associated_token.rs
  transaction-status/src/parse_token.rs
  transaction-status/src/parse_token/extension/cpi_guard.rs
  transaction-status/src/parse_token/extension/default_account_state.rs
  transaction-status/src/parse_token/extension/group_member_pointer.rs
  transaction-status/src/parse_token/extension/group_pointer.rs
  transaction-status/src/parse_token/extension/memo_transfer.rs
  transaction-status/src/parse_token/extension/metadata_pointer.rs
  transaction-status/src/parse_token/extension/mint_close_authority.rs
  transaction-status/src/parse_token/extension/permanent_delegate.rs
  transaction-status/src/parse_token/extension/reallocate.rs
  transaction-status/src/parse_token/extension/token_group.rs
  transaction-status/src/parse_token/extension/token_metadata.rs
  transaction-status/src/parse_token/extension/transfer_fee.rs
  transaction-status/src/parse_token/extension/transfer_hook.rs
Labels: automerge, need:merge-assist

#4245 remove solana-sdk from geyser-plugin-interface
  Cargo.lock
  geyser-plugin-interface/Cargo.toml
  geyser-plugin-interface/src/geyser_plugin_interface.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4243 remove solana-sdk from rpc-test
  Cargo.lock
  rpc-test/Cargo.toml
  rpc-test/tests/nonblocking.rs
  rpc-test/tests/rpc.rs
Labels: automerge, need:merge-assist

#3477 feature gate metrics usage in program-runtime
  core/Cargo.toml
  ledger-tool/Cargo.toml
  ledger/Cargo.toml
  program-runtime/Cargo.toml
  program-runtime/src/lib.rs
  program-runtime/src/loaded_programs.rs
  programs/bpf_loader/Cargo.toml
  runtime/Cargo.toml
  svm/Cargo.toml
Labels: automerge, need:merge-assist

#4284 remove solana-sdk from solana-fee
  Cargo.lock
  fee/Cargo.toml
  fee/src/lib.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4248 remove solana-sdk from geyser-plugin-manager
  Cargo.lock
  geyser-plugin-manager/Cargo.toml
  geyser-plugin-manager/src/accounts_update_notifier.rs
  geyser-plugin-manager/src/block_metadata_notifier.rs
  geyser-plugin-manager/src/block_metadata_notifier_interface.rs
  geyser-plugin-manager/src/entry_notifier.rs
  geyser-plugin-manager/src/slot_status_notifier.rs
  geyser-plugin-manager/src/transaction_notifier.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4235 replace solana_sdk::pubkey with solana_pubkey in ledger
  Cargo.lock
  ledger/Cargo.toml
  ledger/benches/protobuf.rs
  ledger/src/blockstore.rs
  ledger/src/blockstore_processor.rs
  ledger/src/leader_schedule.rs
  ledger/src/leader_schedule_cache.rs
  ledger/src/leader_schedule_utils.rs
  ledger/src/staking_utils.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4240 remove solana-sdk from poh
  Cargo.lock
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/leader_slot_timing_metrics.rs
  poh/Cargo.toml
  poh/benches/poh.rs
  poh/benches/poh_verify.rs
  poh/src/leader_bank_notifier.rs
  poh/src/poh_recorder.rs
  poh/src/poh_service.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4234 replace solana_sdk::pubkey with solana_pubkey in gossip
  Cargo.lock
  gossip/Cargo.toml
  gossip/benches/crds.rs
  gossip/src/cluster_info.rs
  gossip/src/contact_info.rs
  gossip/src/crds.rs
  gossip/src/crds_entry.rs
  gossip/src/crds_gossip_pull.rs
  gossip/src/crds_gossip_push.rs
  gossip/src/epoch_slots.rs
  gossip/src/gossip_service.rs
  gossip/src/legacy_contact_info.rs
  gossip/src/main.rs
  gossip/src/protocol.rs
  gossip/src/received_cache.rs
  gossip/src/restart_crds_values.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4158 docs: change invalid link
  docs/src/implemented-proposals/staking-rewards.md
  docs/src/operations/guides/validator-start.md
Labels: community, need:merge-assist

#4230 move Signable trait to solana-keypair
  sdk/keypair/Cargo.toml
  sdk/keypair/src/lib.rs
  sdk/keypair/src/signable.rs
  sdk/src/signature.rs
Labels: need:merge-assist

#4288 fix typos
  docs/src/consensus/fork-generation.md
  docs/src/implemented-proposals/instruction_introspection.md
  docs/src/implemented-proposals/repair-service.md
  docs/src/proposals/ledger-replication-to-implement.md
  docs/src/proposals/optimistic-transaction-propagation-signal.md
Labels: community, need:merge-assist

#4283 fix: typos in documentation files
  docs/src/proposals/accounts-db-replication.md
Labels: community, need:merge-assist

#4238 remove solana-sdk from unified-scheduler-pool
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  unified-scheduler-pool/Cargo.toml
  unified-scheduler-pool/src/lib.rs
Labels: automerge, need:merge-assist

#4285 remove solana-sdk from address-lookup-table-program
  Cargo.lock
  programs/address-lookup-table/Cargo.toml
  programs/address-lookup-table/src/processor.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4309 chore: remove obsolete comments
  accounts-db/src/accounts_db.rs
Labels: automerge

#4301 Fix missing dependency in solana-curve25519's Cargo.toml
  Cargo.lock
  curves/curve25519/Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: community, need:merge-assist

#4239 remove solana-sdk from solana-install
  Cargo.lock
  install/Cargo.toml
  install/src/command.rs
  install/src/config.rs
  install/src/update_manifest.rs
Labels: need:merge-assist

#4322 remove solana-sdk from bpf-loader-program
  Cargo.lock
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/benches/serialization.rs
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/src/serialization.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4328 remove solana-sdk from loader-v4-program
  Cargo.lock
  programs/loader-v4/Cargo.toml
  programs/loader-v4/src/lib.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4334 remove solana-sdk from storage-proto
  Cargo.lock
  programs/sbf/Cargo.lock
  storage-proto/Cargo.toml
  storage-proto/src/convert.rs
  storage-proto/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4250 Revert "send-transactions: optimize retry pool"
  send-transaction-service/src/send_transaction_service.rs
Labels: automerge

#4351 fix: typos in documentation files
  docs/src/cli/install.md
Labels: community, need:merge-assist

#4281 remove solana-sdk from cargo-registry
  Cargo.lock
  cargo-registry/Cargo.toml
  cargo-registry/src/client.rs
  cargo-registry/src/crate_handler.rs
Labels: need:merge-assist

#4333 replace solana-sdk with solana-program in account-decoder
  Cargo.lock
  account-decoder/Cargo.toml
  account-decoder/src/parse_account_data.rs
  account-decoder/src/parse_bpf_loader.rs
  account-decoder/src/parse_config.rs
  account-decoder/src/parse_stake.rs
  account-decoder/src/parse_vote.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4345 remove solana-sdk from unified-scheduler-logic
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  unified-scheduler-logic/Cargo.toml
  unified-scheduler-logic/src/lib.rs
Labels: automerge, need:merge-assist

#4346 remove solana-sdk from wen-restart
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  wen-restart/Cargo.toml
  wen-restart/src/heaviest_fork_aggregate.rs
  wen-restart/src/last_voted_fork_slots_aggregate.rs
  wen-restart/src/wen_restart.rs
Labels: automerge, need:merge-assist

#4332 use solana-message in transaction-status
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  transaction-status/Cargo.toml
  transaction-status/benches/extract_memos.rs
  transaction-status/src/extract_memos.rs
  transaction-status/src/lib.rs
  transaction-status/src/parse_accounts.rs
  transaction-status/src/parse_address_lookup_table.rs
  transaction-status/src/parse_associated_token.rs
  transaction-status/src/parse_bpf_loader.rs
  transaction-status/src/parse_instruction.rs
  transaction-status/src/parse_stake.rs
  transaction-status/src/parse_system.rs
  transaction-status/src/parse_token.rs
  transaction-status/src/parse_vote.rs
Labels: need:merge-assist

#4331 remove solana-sdk from vote-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/vote/Cargo.toml
  programs/vote/benches/process_vote.rs
  programs/vote/src/lib.rs
  programs/vote/src/vote_processor.rs
  programs/vote/src/vote_state/mod.rs
  programs/vote/src/vote_transaction.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4344 remove solana-sdk from storage-bigtable
  Cargo.lock
  programs/sbf/Cargo.lock
  storage-bigtable/Cargo.toml
  storage-bigtable/src/bigtable.rs
  storage-bigtable/src/lib.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4358 remove solana-sdk from solana-vote
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  vote/Cargo.toml
  vote/benches/vote_account.rs
  vote/src/vote_account.rs
  vote/src/vote_parser.rs
  vote/src/vote_transaction.rs
Labels: automerge, need:merge-assist

#3659 Benchmarks for upgradeable loader instructions
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/benches/bpf_loader_upgradeable.rs
Labels: automerge

#4360 make solana-metrics optional in solana-bpf-loader-program
  programs/bpf_loader/Cargo.toml
Labels: automerge, need:merge-assist

#4327 use solana-pubkey instead of solana-sdk in stake-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/stake/Cargo.toml
  programs/stake/benches/stake.rs
  programs/stake/src/points.rs
  programs/stake/src/rewards.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4154 move inner_instruction.rs to solana-message
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/Cargo.toml
  sdk/message/src/inner_instruction.rs
  sdk/message/src/lib.rs
  sdk/src/lib.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4364 remove solana-program from clap-v3-utils
  Cargo.lock
  clap-v3-utils/Cargo.toml
  clap-v3-utils/src/keypair.rs
Labels: need:merge-assist

#4363 remove solana-program from clap-utils
  Cargo.lock
  clap-utils/Cargo.toml
  clap-utils/src/keypair.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4362 remove solana-sdk from cli-output
  Cargo.lock
  cli-output/Cargo.toml
  cli-output/src/cli_output.rs
  cli-output/src/display.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4396 clippy: type_complexity
  ledger/src/blockstore.rs
Labels: automerge

#4398 clippy: large_enum_variant
  rpc-client-api/src/request.rs
Labels: automerge

#4371 CI: Update downstream SPL to program-specific repos
  .github/scripts/downstream-project-spl-common.sh
  .github/scripts/downstream-project-spl-install-deps.sh
  .github/workflows/downstream-project-anchor.yml
  .github/workflows/downstream-project-spl.yml
Labels: automerge

#4395 chore: fix comments
  accounts-db/src/accounts_db.rs
Labels: automerge

#4397 clippy: empty_line_after_outer_attr
  zk-sdk/src/sigma_proofs/pod.rs
Labels: automerge

#4392 clippy: unnecessary_map_or
  accounts-db/src/account_locks.rs
  bench-tps/src/log_transaction_service.rs
  core/src/replay_stage.rs
  core/src/warm_quic_cache_service.rs
  poh/src/poh_recorder.rs
  programs/vote/src/vote_state/mod.rs
  runtime/src/snapshot_archive_info.rs
  runtime/src/snapshot_utils.rs
  sdk/program/src/vote/state/mod.rs
  validator/src/bootstrap.rs
  wen-restart/src/wen_restart.rs
Labels: automerge

#4374 use solana-account instead of solana-sdk in solana-stake-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/stake/Cargo.toml
  programs/stake/benches/stake.rs
  programs/stake/src/config.rs
  programs/stake/src/rewards.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4390 make bank_client optional in tps-client
  bench-tps/Cargo.toml
  tps-client/Cargo.toml
  tps-client/src/lib.rs
Labels: automerge, need:merge-assist

#4425 make solana-metrics optional in vote and stake programs
  Cargo.toml
  programs/stake/Cargo.toml
  programs/vote/Cargo.toml
  programs/vote/src/lib.rs
  programs/vote/src/vote_state/mod.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4432 use solana-instruction instead of solana-sdk in solana-stake-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/stake/Cargo.toml
  programs/stake/benches/stake.rs
  programs/stake/src/points.rs
  programs/stake/src/rewards.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4437 LocalCluster - rename, refactor consts, verify initial transfers
  accounts-cluster-bench/src/main.rs
  bench-tps/tests/bench_tps.rs
  dos/src/main.rs
  local-cluster/src/integration_tests.rs
  local-cluster/src/local_cluster.rs
  local-cluster/tests/local_cluster.rs
  transaction-dos/src/main.rs
Labels: automerge

#4373 remove solana-sdk from transaction-status
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  transaction-status/Cargo.toml
  transaction-status/benches/extract_memos.rs
  transaction-status/src/extract_memos.rs
  transaction-status/src/lib.rs
  transaction-status/src/parse_accounts.rs
  transaction-status/src/parse_address_lookup_table.rs
  transaction-status/src/parse_associated_token.rs
  transaction-status/src/parse_bpf_loader.rs
  transaction-status/src/parse_instruction.rs
  transaction-status/src/parse_stake.rs
  transaction-status/src/parse_system.rs
  transaction-status/src/parse_token.rs
  transaction-status/src/parse_token/extension/confidential_mint_burn.rs
  transaction-status/src/parse_token/extension/confidential_transfer.rs
  transaction-status/src/parse_token/extension/confidential_transfer_fee.rs
  transaction-status/src/parse_token/extension/reallocate.rs
  transaction-status/src/parse_vote.rs
Labels: need:merge-assist

#4414 Update metrics & ema before breaking the connection loop
  streamer/src/nonblocking/quic.rs
Labels: v2.1

#4448 remove unused solana-sdk dep from compute-budget-program
  Cargo.lock
  programs/compute-budget/Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4426 extract process_message and remove MessageProcessor struct
  svm/src/message_processor.rs
  svm/src/transaction_processor.rs
Labels: need:merge-assist

#4447 remove almost all solana-sdk usage from solana-stake-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/stake/Cargo.toml
  programs/stake/benches/stake.rs
  programs/stake/src/config.rs
  programs/stake/src/lib.rs
  programs/stake/src/points.rs
  programs/stake/src/rewards.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4466 remove "internal use only" from solana-define-syscall definition
  sdk/define-syscall/Cargo.toml
Labels: need:merge-assist

#4375 use solana-commitment-config instead of solana-sdk in solana-cli
  Cargo.lock
  cli/Cargo.toml
  cli/src/address_lookup_table.rs
  cli/src/checks.rs
  cli/src/cli.rs
  cli/src/cluster_query.rs
  cli/src/program.rs
  cli/src/spend_utils.rs
  cli/src/stake.rs
  cli/src/test_utils.rs
  cli/src/vote.rs
  cli/src/wallet.rs
  cli/tests/cluster_query.rs
  cli/tests/nonce.rs
  cli/tests/program.rs
  cli/tests/request_airdrop.rs
  cli/tests/stake.rs
  cli/tests/transfer.rs
  cli/tests/validator_info.rs
  cli/tests/vote.rs
Labels: need:merge-assist

#4465 Update ledger-tool --deactivate-feature-gate to deactivate feature gate in child bank
  ledger-tool/src/main.rs
Labels: v2.1

#4461 ci: add --no-tests=warn
  ci/stable/run-local-cluster-partially.sh
  ci/stable/run-partition.sh
Labels: automerge

#4495 CI: Re-enable downstream jobs
  .github/workflows/downstream-project-spl.yml
Labels: automerge

#4454 tpu-client-next: return receiver in scheduler::run
  tls-utils/src/quic_client_certificate.rs
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/quic_networking.rs
  tpu-client-next/tests/connection_workers_scheduler_test.rs
Labels: v2.1

#4522 Add send_transactions_to_address method to workers_cache
  tpu-client-next/src/workers_cache.rs
Labels: automerge

#4476 Extract address-lookup-table-interface
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/address-lookup-table-interface/Cargo.toml
  sdk/address-lookup-table-interface/src/error.rs
  sdk/address-lookup-table-interface/src/instruction.rs
  sdk/address-lookup-table-interface/src/lib.rs
  sdk/address-lookup-table-interface/src/state.rs
  sdk/program/Cargo.toml
  sdk/program/src/address_lookup_table.rs
  sdk/program/src/address_lookup_table/error.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4491 extract big-mod-exp crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/big-mod-exp/Cargo.toml
  sdk/big-mod-exp/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4482 extract vote-interface crate
  Cargo.lock
  Cargo.toml
  core/src/consensus.rs
  core/src/consensus/tower1_14_11.rs
  core/src/consensus/tower1_7_14.rs
  programs/sbf/Cargo.lock
  programs/vote/src/vote_state/mod.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/vote/error.rs
  sdk/vote-interface/Cargo.toml
  sdk/vote-interface/src/authorized_voters.rs
  sdk/vote-interface/src/error.rs
  sdk/vote-interface/src/instruction.rs
  sdk/vote-interface/src/lib.rs
  sdk/vote-interface/src/state/mod.rs
  sdk/vote-interface/src/state/vote_state_0_23_5.rs
  sdk/vote-interface/src/state/vote_state_1_14_11.rs
  sdk/vote-interface/src/state/vote_state_deserialize.rs
  sdk/vote-interface/src/state/vote_state_versions.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4539 remove solana-program from clap-utils
  Cargo.lock
  clap-utils/Cargo.toml
  clap-utils/src/keypair.rs
  keygen/Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4496 remove solana-sdk from some cli modules
  Cargo.lock
  cli/Cargo.toml
  cli/src/address_lookup_table.rs
  cli/src/checks.rs
  cli/src/cli.rs
Labels: need:merge-assist

#4537 remove solana-program from solana-vote
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  vote/Cargo.toml
  vote/benches/vote_account.rs
  vote/src/vote_account.rs
  vote/src/vote_parser.rs
  vote/src/vote_transaction.rs
Labels: automerge, need:merge-assist

#4550 replace most sdk usage in cli/src
  Cargo.lock
  cli/Cargo.toml
  cli/src/cluster_query.rs
  cli/src/compute_budget.rs
  cli/src/feature.rs
  cli/src/inflation.rs
  cli/src/memo.rs
  cli/src/nonce.rs
  cli/src/program.rs
  cli/src/program_v4.rs
  cli/src/spend_utils.rs
  cli/src/stake.rs
  cli/src/test_utils.rs
  cli/src/validator_info.rs
  cli/src/vote.rs
  cli/src/wallet.rs
Labels: need:merge-assist

#4536 remove solana-program from solana-vote-program
  Cargo.lock
  programs/sbf/Cargo.lock
  programs/vote/Cargo.toml
  programs/vote/src/lib.rs
  programs/vote/src/vote_processor.rs
  programs/vote/src/vote_state/mod.rs
  programs/vote/src/vote_transaction.rs
  sdk/vote-interface/Cargo.toml
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4538 remove solana-program from address-lookup-table-program
  Cargo.lock
  programs/address-lookup-table/Cargo.toml
  programs/address-lookup-table/src/processor.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4552 remove solana-sdk from store-tool
  Cargo.lock
  accounts-db/store-tool/Cargo.toml
  accounts-db/store-tool/src/main.rs
Labels: automerge, need:merge-assist

#4534 use explicit path for impl_sysvar_id in declare_sysvar_id
  sdk/sysvar-id/src/lib.rs
Labels: need:merge-assist

#4498 move sdk::feature utils into feature-gate-interface
  Cargo.lock
  programs/sbf/Cargo.lock
  sdk/feature-gate-interface/Cargo.toml
  sdk/feature-gate-interface/src/lib.rs
  sdk/src/feature.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4532 :pencil2: Fix ssh typo in setup validator doc
  docs/src/operations/setup-a-validator.md
Labels: community, need:merge-assist

#3608 Convert the StableVec class to use virtual addressing
  program-runtime/src/invoke_context.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  sdk/stable-layout/src/stable_vec.rs
Labels: community, need:merge-assist

#4484 extract loader-v3-interface crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/loader-v3-interface/Cargo.toml
  sdk/loader-v3-interface/src/instruction.rs
  sdk/loader-v3-interface/src/lib.rs
  sdk/loader-v3-interface/src/state.rs
  sdk/program/Cargo.toml
  sdk/program/src/bpf_loader_upgradeable.rs
  sdk/program/src/lib.rs
  sdk/program/src/loader_upgradeable_instruction.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4487 Extract loader-v2-interface crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/loader-v2-interface/Cargo.toml
  sdk/loader-v2-interface/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  svm/examples/Cargo.lock
  transaction-status/Cargo.toml
  transaction-status/src/parse_bpf_loader.rs
Labels: need:merge-assist

#4545 Scheduler Frequency Fixes
  core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs
  core/src/banking_stage/transaction_scheduler/receive_and_buffer.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: v2.0, v2.1

#4490 extract blake3-hasher crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/blake3-hasher/Cargo.toml
  sdk/blake3-hasher/src/lib.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4586 quic: disable send fairness
  quic-client/src/nonblocking/quic_client.rs
  sdk/quic-definitions/src/lib.rs
  streamer/src/nonblocking/testing_utilities.rs
  tpu-client-next/src/quic_networking.rs
Labels: community, need:merge-assist, v2.1

#4357 use solana-pubkey in accounts-db
  Cargo.lock
  accounts-db/accounts-hash-cache-tool/Cargo.toml
  accounts-db/accounts-hash-cache-tool/src/main.rs
  accounts-db/benches/accounts.rs
  accounts-db/benches/accounts_index.rs
  accounts-db/benches/bench_accounts_file.rs
  accounts-db/benches/bench_hashing.rs
  accounts-db/benches/bench_lock_accounts.rs
  accounts-db/benches/bench_serde.rs
  accounts-db/benches/utils.rs
  accounts-db/src/account_locks.rs
  accounts-db/src/account_storage/meta.rs
  accounts-db/src/accounts.rs
  accounts-db/src/accounts_cache.rs
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_db/geyser_plugin_utils.rs
  accounts-db/src/accounts_db/scan_account_storage.rs
  accounts-db/src/accounts_db/tests.rs
  accounts-db/src/accounts_file.rs
  accounts-db/src/accounts_hash.rs
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
  accounts-db/src/accounts_partition.rs
  accounts-db/src/accounts_update_notifier_interface.rs
  accounts-db/src/ancient_append_vecs.rs
  accounts-db/src/append_vec.rs
  accounts-db/src/append_vec/test_utils.rs
  accounts-db/src/read_only_accounts_cache.rs
  accounts-db/src/stake_rewards.rs
  accounts-db/src/storable_accounts.rs
  accounts-db/src/tiered_storage.rs
  accounts-db/src/tiered_storage/footer.rs
  accounts-db/src/tiered_storage/hot.rs
  accounts-db/src/tiered_storage/readable.rs
  accounts-db/src/tiered_storage/test_utils.rs
Labels: need:merge-assist

#3686 Fix ALT_BN128_MULTIPLICATION_INPUT_LEN constant
  curves/bn254/src/lib.rs
  programs/bpf_loader/src/syscalls/mod.rs
  sdk/feature-set/src/lib.rs
Labels: community, need:merge-assist

#4596 fix: use atomic to check if leader bank changed
  core/src/banking_stage/consume_worker.rs
  poh/src/leader_bank_notifier.rs
Labels: v2.0, v2.1

#4486 extract loader-v4-interface crate
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  sdk/loader-v4-interface/Cargo.toml
  sdk/loader-v4-interface/src/instruction.rs
  sdk/loader-v4-interface/src/lib.rs
  sdk/loader-v4-interface/src/state.rs
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/loader_v4.rs
  sdk/program/src/loader_v4_instruction.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#4614 remove solana-program from solana-loader-v4-program
  Cargo.lock
  programs/loader-v4/Cargo.toml
  programs/loader-v4/src/lib.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist

#4585 quic: increase timeout and keep alive
  sdk/quic-definitions/src/lib.rs
Labels: community, need:merge-assist

#3846 docs: Link to the doc of `$SOLANA_METRICS_CONFIG` from `monitoring.md`
  docs/src/operations/best-practices/monitoring.md
Labels: community, need:merge-assist

#4497 Remove unnecessary input to transaction_accounts_lamports_sum
  svm/src/transaction_processor.rs
Labels: community, need:merge-assist

#4592 Docs: fix typos
  docs/src/proposals/blockstore-rocksdb-compaction.md
  docs/src/proposals/fee_transaction_priority.md
  svm/examples/json-rpc/README.md
  svm/examples/paytube/README.md
Labels: community, need:merge-assist

#4257 Reapply changes from reverted PR 3423
  Cargo.lock
  programs/sbf/Cargo.lock
  send-transaction-service/Cargo.toml
  send-transaction-service/src/send_transaction_service.rs
  svm/examples/Cargo.lock
Labels: automerge, v2.1

#4681 cli: demote solana-sdk to dev deps
  cli/Cargo.toml
  cli/src/cluster_query.rs
  cli/src/feature.rs
Labels: need:merge-assist

#4691 docs(consensus): fix minor math comment in Turbine description.
  docs/src/consensus/turbine-block-propagation.md
Labels: automerge, community, need:merge-assist

#4667 Revert "Report ConsumeWorkerMetrics at slot transitions (#3212)"
  core/src/banking_stage/consume_worker.rs
  core/src/banking_stage/transaction_scheduler/scheduler_controller.rs
Labels: v2.1

#4436 tpu-client-next: add mechanism to implement custom scheduler
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/lib.rs
  tpu-client-next/src/workers_cache.rs
Labels: automerge

#3607 Add a VmSlice class for slices stored within the interpreter's virtual memory
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/bpf_loader/src/syscalls/logging.rs
  programs/bpf_loader/src/syscalls/mod.rs
Labels: community, need:merge-assist

#4692 publish thread manager crate
  thread-manager/Cargo.toml
Labels: automerge

#4694 Revert "Reduce public visibile APIs in solana-fee (#4588)"
  Cargo.lock
  fee/Cargo.toml
  fee/src/lib.rs
  programs/sbf/Cargo.lock
  svm/Cargo.toml
  svm/examples/Cargo.lock
Labels: automerge

#4698 ci: remove default args from the ci dockerfile
  ci/docker/Dockerfile
  ci/docker/README.md
Labels: automerge

#4659 refactor: introduce SnapshotMode enum as a replacement for SnapshotCo…
  runtime/src/lib.rs
  runtime/src/snapshot_mode.rs
Labels: community, need:merge-assist

#4664 Replace solana_program::stake with solana_stake_interface
  Cargo.lock
  Cargo.toml
  platform-tools-sdk/cargo-build-sbf/tests/crates/fail/Cargo.toml
  platform-tools-sdk/cargo-build-sbf/tests/crates/fail/src/lib.rs
  platform-tools-sdk/cargo-build-sbf/tests/crates/noop/Cargo.toml
  platform-tools-sdk/cargo-build-sbf/tests/crates/noop/src/lib.rs
  platform-tools-sdk/cargo-build-sbf/tests/crates/package-metadata/Cargo.toml
  platform-tools-sdk/cargo-build-sbf/tests/crates/package-metadata/src/lib.rs
  platform-tools-sdk/cargo-build-sbf/tests/crates/workspace-metadata/Cargo.toml
  platform-tools-sdk/cargo-build-sbf/tests/crates/workspace-metadata/src/lib.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  runtime/src/bank/serde_snapshot.rs
  scripts/patch-crates.sh
  sdk/program/Cargo.toml
  sdk/program/src/lib.rs
  sdk/program/src/stake.rs
  sdk/program/src/stake/config.rs
  sdk/program/src/stake/instruction.rs
  sdk/program/src/stake/mod.rs
  sdk/program/src/stake/stake_flags.rs
  sdk/program/src/stake/state.rs
  sdk/program/src/stake/tools.rs
  sdk/sysvar/Cargo.toml
  sdk/sysvar/src/stake_history.rs
  svm/examples/Cargo.lock
  svm/examples/Cargo.toml
Labels: automerge, need:merge-assist

#4708 Report ConsumeWorkerMetrics on 20ms interval
  core/src/banking_stage/consume_worker.rs
Labels: v2.1

#4462 demote solana-vote-program to dev deps of solana-stake-program
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/stake/Cargo.toml
  programs/stake/benches/stake.rs
  programs/stake/src/points.rs
  programs/stake/src/rewards.rs
  programs/stake/src/stake_instruction.rs
  programs/stake/src/stake_state.rs
  svm/examples/Cargo.lock
Labels: automerge, need:merge-assist
