Repository anza-xyz/agave, pull requests merged in 2025-08, with the labels that each got.

#7254 chore: Typo fixes
  unified-scheduler-logic/src/lib.rs
Labels: community, need:merge-assist

#6487 SIMD-0296: Raise CPI Nesting Limit to 8
  cli/src/program.rs
  cli/src/program_v4.rs
  compute-budget/Cargo.toml
  compute-budget/src/compute_budget.rs
  compute-budget/src/compute_budget_limits.rs
  feature-set/src/lib.rs
  program-runtime/src/execution_budget.rs
  program-runtime/src/invoke_context.rs
  program-test/src/lib.rs
  programs/sbf/benches/bpf_loader.rs
  programs/sbf/c/src/invoke/invoke.c
  programs/sbf/c/src/invoked/invoked.c
  programs/sbf/rust/invoke/src/lib.rs
  programs/sbf/rust/invoke_dep/src/lib.rs
  programs/sbf/rust/invoked/src/lib.rs
  programs/sbf/tests/programs.rs
  runtime/src/bank.rs
  runtime/src/bank/builtins/core_bpf_migration/mod.rs
  runtime/src/bank/check_transactions.rs
  runtime/src/bank/tests.rs
  svm-feature-set/src/lib.rs
  svm/Cargo.toml
  svm/examples/json-rpc/server/src/svm_bridge.rs
  svm/examples/paytube/src/processor.rs
  svm/tests/integration_test.rs
  test-validator/src/lib.rs
Labels: feature-gate

#7284 xdp: fix draining at exit when zerocopy is enabled
  xdp/src/tx_loop.rs
Labels: v2.3

#7285 xdp: tx_loop: allow overriding MACs and IP
  turbine/src/xdp.rs
  xdp/src/device.rs
  xdp/src/tx_loop.rs
Labels: automerge

#7178 local-cluster: move to non-overlapping ports
  local-cluster/src/local_cluster.rs
Labels: community, need:merge-assist

#7228 gossip: refactor cluster_info #5824
  core/src/banking_simulation.rs
  core/src/cluster_slots_service.rs
  core/src/repair/ancestor_hashes_service.rs
  core/src/repair/repair_service.rs
  core/src/replay_stage.rs
  core/src/tvu.rs
  core/src/validator.rs
  gossip/src/cluster_info.rs
  gossip/src/duplicate_shred_listener.rs
  gossip/src/gossip_service.rs
  gossip/src/lib.rs
  gossip/src/node.rs
  gossip/tests/gossip.rs
  local-cluster/src/cluster.rs
  local-cluster/src/local_cluster.rs
  test-validator/src/lib.rs
  turbine/benches/cluster_info.rs
  turbine/src/broadcast_stage.rs
  turbine/src/broadcast_stage/standard_broadcast_run.rs
  validator/src/admin_rpc_service.rs
  validator/src/bootstrap.rs
  validator/src/commands/run/execute.rs
Labels: community, need:merge-assist

#7342 fix: various importance typos
  accounts-db/benches/read_only_accounts_cache.rs
  accounts-db/src/accounts_db/tests.rs
  accounts-db/src/io_uring/memory.rs
  accounts-db/src/tiered_storage/byte_block.rs
Labels: community, need:merge-assist

#7338 docs: link correction
  docs/src/operations/prerequisites.md
Labels: community, need:merge-assist

#7053 tpu-client-next: implement log/tracing library switching feature
  Cargo.lock
  Cargo.toml
  tpu-client-next/Cargo.toml
  tpu-client-next/src/connection_worker.rs
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/leader_updater.rs
  tpu-client-next/src/lib.rs
  tpu-client-next/src/logging.rs
  tpu-client-next/src/workers_cache.rs
Labels: community, need:merge-assist

#7402 fix: update broken documentation redirects in publish-docs.sh
  docs/publish-docs.sh
Labels: community, need:merge-assist

#7401 fix: correct typos and improve comments in accounts-db module
  accounts-db/benches/bench_lock_accounts.rs
  accounts-db/src/io_uring/file_creator.rs
  accounts-db/src/tiered_storage/hot.rs
  accounts-db/src/tiered_storage/meta.rs
Labels: community, need:merge-assist

#7424 Remove unnecessary functions from `BorrowedAccount`
  program-runtime/src/invoke_context.rs
  program-runtime/src/serialization.rs
  runtime/src/bank/tests.rs
  svm/src/message_processor.rs
  transaction-context/src/lib.rs
Labels: automerge

#7443 chore(ci): fix typos in audit and sanity scripts
  ci/do-audit.sh
  ci/run-sanity.sh
Labels: community, need:merge-assist

#6847 Cleanup - Feature gate of `remove_accounts_executable_flag_checks`
  feature-set/src/lib.rs
  program-runtime/src/invoke_context.rs
  programs/bpf_loader/src/lib.rs
  runtime/src/bank/tests.rs
  svm-feature-set/src/lib.rs
  svm/src/account_loader.rs
  svm/src/transaction_processor.rs
  svm/tests/integration_test.rs
  transaction-context/src/lib.rs
Labels: feature-gate

#7532 dont use Arc with Receiver
  rpc/src/transaction_status_service.rs
Labels: automerge

#7580 --block-production-num-workers cli arg
  CHANGELOG.md
  banking-bench/src/main.rs
  core/benches/banking_stage.rs
  core/src/banking_simulation.rs
  core/src/banking_stage.rs
  core/src/banking_stage/unified_scheduler.rs
  core/src/tpu.rs
  core/src/validator.rs
  core/tests/unified_scheduler.rs
  local-cluster/src/validator_configs.rs
  validator/src/cli/thread_args.rs
  validator/src/commands/run/execute.rs
Labels: changelog

#7570 ledger: Remove stale comment about legacy data shreds
  ledger/src/shred/wire.rs
Labels: community, need:merge-assist

#7567 turbine: introduce drop channel capacity constant for xdp retransmitter
  turbine/src/xdp.rs
Labels: community, need:merge-assist

#7648 Add some docs for troubleshooting PoH hashes/second rate
  docs/src/operations/setup-a-validator.md
Labels: community, need:merge-assist

#7203 remove stake program builtin
  Cargo.lock
  Cargo.toml
  builtins-default-costs/Cargo.toml
  builtins-default-costs/src/lib.rs
  builtins/src/lib.rs
  compute-budget-instruction/src/builtin_programs_filter.rs
  compute-budget-instruction/src/compute_budget_instruction_details.rs
  core/Cargo.toml
  core/tests/scheduler_cost_adjustment.rs
  fetch-core-bpf.sh
  ledger/src/staking_utils.rs
  local-cluster/Cargo.toml
  local-cluster/src/local_cluster.rs
  program-binaries/Cargo.toml
  program-binaries/src/lib.rs
  program-binaries/src/programs/core_bpf_address_lookup_table-3.0.0.so
  program-binaries/src/programs/core_bpf_config-3.0.0.so
  program-binaries/src/programs/core_bpf_feature_gate-0.0.1.so
  program-binaries/src/programs/core_bpf_stake-1.0.0.so
  program-binaries/src/programs/spl_associated_token_account-1.1.1.so
  program-binaries/src/programs/spl_memo-1.0.0.so
  program-binaries/src/programs/spl_memo-3.0.0.so
  program-binaries/src/programs/spl_token-3.5.0.so
  program-binaries/src/programs/spl_token_2022-8.0.0.so
  program-test/Cargo.toml
  program-test/src/lib.rs
  program-test/tests/core_bpf.rs
  program-test/tests/spl.rs
  programs/sbf/Cargo.lock
  programs/sbf/tests/programs.rs
  programs/stake-tests/Cargo.toml
  programs/stake-tests/tests/test_move_stake_and_lamports.rs
  rpc/src/rpc_pubsub.rs
  runtime/Cargo.toml
  runtime/src/bank/builtin_programs.rs
  runtime/src/bank/builtins/core_bpf_migration/target_builtin.rs
  runtime/src/bank/partitioned_epoch_rewards/mod.rs
  runtime/src/bank/tests.rs
  runtime/src/genesis_utils.rs
  runtime/tests/stake.rs
  stake-accounts/Cargo.toml
  stake-accounts/src/stake_accounts.rs
  svm/Cargo.toml
  svm/tests/integration_test.rs
  test-validator/Cargo.toml
  test-validator/src/lib.rs
Labels: automerge

#7708 remove gossip ping gate
  gossip/src/cluster_info.rs
  gossip/src/crds_filter.rs
Labels: automerge

#7143 tpu-client-next: improve logging by adding information about the peer
  tpu-client-next/src/connection_worker.rs
Labels: community, need:merge-assist

#7724 Fix - Initializes R1 in the ledger-tool program subcommand
  ledger-tool/src/program.rs
Labels: v3.0

#7711 axe SignedData enum (ledger/ shred)
  ledger/src/shred.rs
  ledger/src/shred/merkle.rs
  ledger/src/shred/shred_code.rs
  ledger/src/shred/shred_data.rs
  ledger/src/shred/wire.rs
  ledger/src/sigverify_shreds.rs
Labels: community, need:merge-assist

#7737 rpc-client-types: re-export types used in public API and switch to solana-address
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  rpc-client-types/Cargo.toml
  rpc-client-types/src/config.rs
  rpc-client-types/src/request.rs
  rpc-client-types/src/response.rs
Labels: need:merge-assist
