Repository anza-xyz/agave, pull requests merged in 2025-03, with the labels that each got.

#5106 docs: Increases disk requirements
  docs/src/operations/requirements.md
Labels: automerge

#5109 remove duplicates from fanout leaders
  tpu-client-next/src/connection_workers_scheduler.rs
Labels: v2.2

#5111 Reapply 3515: use `SendTransactionService::new_with_client` in rpc
  banks-server/src/banks_server.rs
  rpc/src/rpc.rs
  rpc/src/rpc_service.rs
  send-transaction-service/src/send_transaction_service.rs
Labels: v2.2

#5160 Fix flaky banking stage tests
  core/src/banking_stage.rs
Labels: v2.2

#5193 Reduce timeout on spl CI jobs
  .github/workflows/downstream-project-spl.yml
Labels: community, need:merge-assist

#5113 Reapply PR#31: optimize retry pool
  send-transaction-service/src/send_transaction_service.rs
Labels: v2.2

#4689 Update validator-failover.md
  docs/src/operations/guides/validator-failover.md
Labels: community, need:merge-assist

#5180 ReceiveAndBuffer - fix panic on expired blockhashes for view
  core/src/banking_stage/transaction_scheduler/receive_and_buffer.rs
Labels: v2.2

#5212 remove UB from append vec tests
  accounts-db/src/append_vec.rs
Labels: automerge

#4572 feat: disable partitioned rent collection (SIMD-0175)
  ledger/src/blockstore_processor.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
Labels: feature-gate

#5229 ci: add the Dockerfile as part of the hash seed
  ci/docker/env.sh
Labels: automerge

#5228 ci: use exec in ci/docker-run-default-image.sh
  ci/docker-run-default-image.sh
Labels: automerge

#5266 fix spelling error readable.rs
  accounts-db/src/tiered_storage/readable.rs
Labels: community, need:merge-assist

#4888 define is_nonverlapping function in solana-bpf-loader-program
  Cargo.lock
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/syscalls/mem_ops.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: need:merge-assist

#5293 Moves RootsTracker to submodule
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/roots_tracker.rs
Labels: automerge

#5298 Removes unused ScanSlotTracker
  accounts-db/src/accounts_index.rs
Labels: automerge

#5299 Removes InMemMap type alias
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
Labels: automerge

#5301 Removes the K type alias in in-mem accounts index
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
Labels: automerge

#5294 Moves AccountMapEntry types to submodule
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/account_map_entry.rs
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
Labels: automerge

#5302 Removes CacheRangesHeld type alias
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
Labels: automerge

#5296 Moves AccountSecondaryIndexes types to submodule
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/secondary.rs
Labels: automerge

#5305 Clean up rpc filter verification
  rpc/src/rpc.rs
  rpc/src/rpc_pubsub.rs
  rpc/src/rpc_pubsub_service.rs
Labels: automerge, v2.1, v2.2

#5312 cp fetch-programs.sh
  docker-solana/build.sh
Labels: automerge

#4660 extract rpc-client-types without reqwest dep
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  rpc-client-api/Cargo.toml
  rpc-client-api/src/lib.rs
  rpc-client-api/src/response.rs
  rpc-client-types/Cargo.toml
  rpc-client-types/src/config.rs
  rpc-client-types/src/error_object.rs
  rpc-client-types/src/filter.rs
  rpc-client-types/src/lib.rs
  rpc-client-types/src/request.rs
  rpc-client-types/src/response.rs
  svm/examples/Cargo.lock
Labels: need:merge-assist

#5328 cleanup some script work
  docker-solana/build.sh
  net/net.sh
Labels: automerge

#5201 tpu-client-next: add client selection to validator
  Cargo.lock
  core/src/validator.rs
  local-cluster/src/validator_configs.rs
  programs/sbf/Cargo.lock
  rpc/Cargo.toml
  rpc/src/rpc_service.rs
  svm/examples/Cargo.lock
Labels: v2.2

#4597 feat: new leader schedule by vote delegation (SIMD-0180)
  ledger/Cargo.toml
  ledger/src/leader_schedule.rs
  ledger/src/leader_schedule/vote_keyed.rs
  ledger/src/leader_schedule_utils.rs
  runtime/src/bank.rs
  runtime/src/bank/tests.rs
Labels: feature-gate

#5332 clean: load failure fees feature
  runtime/src/bank/tests.rs
  svm/src/transaction_processor.rs
  svm/tests/integration_test.rs
Labels: automerge

#5369 Fixes log when snapshots are disabled
  validator/src/commands/run/execute.rs
Labels: automerge

#5194 add receive_and_buffer bench
  Cargo.lock
  core/Cargo.toml
  core/benches/receive_and_buffer.rs
  core/src/banking_stage.rs
  core/src/banking_stage/transaction_scheduler/mod.rs
  core/src/banking_stage/transaction_scheduler/receive_and_buffer.rs
  core/src/banking_stage/transaction_scheduler/scheduler.rs
  core/src/banking_stage/transaction_scheduler/transaction_priority_id.rs
  core/src/banking_stage/transaction_scheduler/transaction_state.rs
  core/src/banking_stage/transaction_scheduler/transaction_state_container.rs
Labels: automerge

#4748 Support multiple RPC URLs in watchtower
  watchtower/README.md
  watchtower/src/main.rs
Labels: community, need:merge-assist

#5392 Moves AccountsIndexIterator to submodule
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/iter.rs
Labels: automerge

#5323 Fix support for nightly builds in `solana-unified-scheduler-pool`
  unified-scheduler-pool/src/lib.rs
Labels: community, need:merge-assist

#5405 default to BlockProductionMethod::CentralSchedulerGreedy
  CHANGELOG.md
  core/src/validator.rs
Labels: v2.2

#5402 nit: fix links in delegate-stake.md
  docs/src/cli/examples/delegate-stake.md
Labels: community, need:merge-assist

#5413 Removes SlotSlice type alias
  accounts-db/src/accounts_index.rs
Labels: automerge

#5416 Bump `solana-bn254` version to 2.2.2
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  svm/examples/Cargo.lock
Labels: v2.2

#5421 bump stable rust from 1.84.1 to 1.85.1
  rust-toolchain.toml
Labels: automerge

#5410 Fix - program-v4 CLI bugs
  cli/src/program_v4.rs
  cli/tests/program.rs
Labels: v2.2

#5338 Metrics reporting for tpu-client-next
  Cargo.lock
  programs/sbf/Cargo.lock
  rpc/src/rpc.rs
  send-transaction-service/Cargo.toml
  send-transaction-service/src/send_transaction_service.rs
  send-transaction-service/src/test_utils.rs
  send-transaction-service/src/transaction_client.rs
  svm/examples/Cargo.lock
  tpu-client-next/Cargo.toml
  tpu-client-next/src/connection_workers_scheduler.rs
  tpu-client-next/src/lib.rs
  tpu-client-next/src/metrics.rs
  tpu-client-next/src/send_transaction_stats.rs
  tpu-client-next/tests/connection_workers_scheduler_test.rs
Labels: automerge

#5443 refactor: Add snapshot usage "disabled" variant
  core/src/validator.rs
  core/tests/epoch_accounts_hash.rs
  core/tests/snapshots.rs
  ledger-tool/src/ledger_utils.rs
  ledger/src/bank_forks_utils.rs
  ledger/src/blockstore_processor.rs
  local-cluster/tests/local_cluster.rs
  program-test/src/lib.rs
  runtime/src/bank_forks.rs
  runtime/src/snapshot_config.rs
  runtime/src/snapshot_controller.rs
Labels: automerge

#5455 Revert "Directly storing and propagating target_lamports_per_signature"
  core/src/banking_stage/consumer.rs
  runtime/src/bank.rs
  runtime/src/bank/fee_distribution.rs
  runtime/src/bank/tests.rs
Labels: automerge

#5473 refactor get supply rpc method
  rpc/src/rpc_service.rs
Labels: automerge

#5489 add crate description for agave-feature-set
  feature-set/Cargo.toml
Labels: v2.2

#5512 Removes unused started_from_validator field in AccountsIndexConfig
  accounts-db/src/accounts_index.rs
  test-validator/src/lib.rs
  validator/src/commands/run/execute.rs
Labels: automerge

#5514 Moves IsZeroLamport trait to submodule
  accounts-db/src/account_info.rs
  accounts-db/src/accounts_db.rs
  accounts-db/src/accounts_index.rs
  accounts-db/src/accounts_index/account_map_entry.rs
  accounts-db/src/accounts_index/in_mem_accounts_index.rs
  accounts-db/src/append_vec.rs
  accounts-db/src/is_zero_lamport.rs
  accounts-db/src/lib.rs
  accounts-db/src/stake_rewards.rs
  accounts-db/src/storable_accounts.rs
Labels: automerge

#5513 Add agave-reserved-account-keys crate
  Cargo.lock
  Cargo.toml
  cli-output/Cargo.toml
  cli-output/src/display.rs
  core/Cargo.toml
  core/src/banking_stage/consumer.rs
  core/src/banking_stage/unprocessed_packet_batches.rs
  cost-model/Cargo.toml
  cost-model/src/transaction_cost.rs
  entry/Cargo.toml
  entry/benches/entry_sigverify.rs
  entry/src/entry.rs
  ledger-tool/Cargo.toml
  ledger-tool/src/main.rs
  ledger/Cargo.toml
  ledger/src/transaction_address_lookup_table_scanner.rs
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/tests/programs.rs
  reserved-account-keys/Cargo.toml
  reserved-account-keys/src/lib.rs
  rpc/Cargo.toml
  rpc/src/rpc.rs
  rpc/src/transaction_status_service.rs
  runtime-transaction/Cargo.toml
  runtime-transaction/src/runtime_transaction/sdk_transactions.rs
  runtime-transaction/src/runtime_transaction/transaction_view.rs
  runtime/Cargo.toml
  runtime/src/bank.rs
  runtime/src/snapshot_minimizer.rs
  storage-bigtable/Cargo.toml
  storage-bigtable/src/lib.rs
  svm/Cargo.toml
  svm/examples/Cargo.lock
  svm/examples/Cargo.toml
  svm/examples/json-rpc/server/Cargo.toml
  svm/examples/json-rpc/server/src/rpc_process.rs
  svm/src/account_loader.rs
  svm/src/message_processor.rs
  svm/src/transaction_account_state_info.rs
  svm/src/transaction_processor.rs
  svm/tests/transaction_builder.rs
  transaction-status/Cargo.toml
  transaction-status/src/lib.rs
  transaction-status/src/parse_accounts.rs
Labels: v2.2

#5509 Add agave-precompiles crate
  Cargo.lock
  Cargo.toml
  precompiles/Cargo.toml
  precompiles/src/ed25519.rs
  precompiles/src/lib.rs
  precompiles/src/secp256k1.rs
  precompiles/src/secp256r1.rs
  program-runtime/Cargo.toml
  program-runtime/src/invoke_context.rs
  programs/bpf_loader/Cargo.toml
  programs/bpf_loader/src/syscalls/mod.rs
  programs/sbf/Cargo.lock
  runtime/Cargo.toml
  runtime/src/bank.rs
  runtime/src/verify_precompiles.rs
  svm/Cargo.toml
  svm/examples/Cargo.lock
  svm/src/message_processor.rs
Labels: v2.2

#5539 clean: remove unused verify_precompiles runtime mod
  runtime/src/lib.rs
  runtime/src/verify_precompiles.rs
Labels: automerge

#5540 Speed up manual ticking tests
  core/src/banking_stage/consumer.rs
Labels: automerge, v2.2

#5561 Formats accounts_background_service.rs
  runtime/src/accounts_background_service.rs
Labels: automerge

#5576 clean: deplete_cu_meter_on_vm_failure feature
  programs/bpf_loader/src/lib.rs
  programs/sbf/tests/programs.rs
Labels: automerge

#5581 Bump timeout for test_kill_heaviest_partition
  local-cluster/tests/local_cluster.rs
  nextest.toml
Labels: automerge

#5579 Bump solana-vote-interface to v2.2.3
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: automerge, v2.2
