Repository anza-xyz/agave, pull requests merged in 2025-07, with the labels that each got.

#6798 clippy: ptr_eq
  core/src/cluster_slots_service/slot_supporters.rs
Labels: automerge

#6804 ci: install openssl 3.4.2 for windows clippy build
  .github/scripts/install-openssl.sh
Labels: v2.2, v2.3

#6824 ci(windows): use vcpkg to install openssl 3.4.1
  .github/scripts/install-openssl.sh
Labels: v2.2, v2.3

#6826 xdp: set ring sizes based on configured ethtool values
  xdp/src/device.rs
  xdp/src/tx_loop.rs
Labels: v2.3

#6776 gossip: prepare crate for edition 2024
  gossip/src/cluster_info.rs
  gossip/src/crds.rs
  gossip/src/duplicate_shred_handler.rs
  gossip/src/lib.rs
  gossip/src/weighted_shuffle.rs
Labels: community, need:merge-assist

#6800 Upgrades rust to 1.87.0
  ci/rust-version.sh
  rust-toolchain.toml
Labels: automerge

#6686 Trash overgrown bp unified scheduler
  core/src/banking_stage/unified_scheduler.rs
  unified-scheduler-logic/src/lib.rs
  unified-scheduler-pool/src/lib.rs
Labels: automerge, need:merge-assist

#6863 fix: typo in "occurred"
  runtime/src/bank_hash_cache.rs
Labels: community, need:merge-assist

#6748 remove calls to get EpochInfo from LeaderTpuCacheUpdater
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  tpu-client/Cargo.toml
  tpu-client/src/nonblocking/tpu_client.rs
Labels: v2.3

#6661 Allow setting custom fixed inflation rate to solana-test-validator
  Cargo.lock
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
  test-validator/Cargo.toml
  test-validator/src/lib.rs
  validator/Cargo.toml
  validator/src/bin/solana-test-validator.rs
  validator/src/cli.rs
Labels: community, need:merge-assist

#6873 bump indicatif from 0.17.12 to 0.18.0
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  svm/examples/Cargo.lock
Labels: community, need:merge-assist

#6849 Fix toolchain path check on Windows
  platform-tools-sdk/cargo-build-sbf/src/main.rs
Labels: community, need:merge-assist

#6769 SBPF v0.11.2 + Platform Tools v1.50
  Cargo.lock
  Cargo.toml
  feature-set/src/lib.rs
  platform-tools-sdk/cargo-build-sbf/src/main.rs
  platform-tools-sdk/cargo-build-sbf/tests/crates/package-metadata/Cargo.toml
  platform-tools-sdk/cargo-build-sbf/tests/crates/workspace-metadata/Cargo.toml
  platform-tools-sdk/sbf/scripts/install.sh
  programs/bpf_loader/src/lib.rs
  programs/bpf_loader/test_elfs/out/noop_aligned.so
  programs/bpf_loader/test_elfs/out/noop_unaligned.so
  programs/bpf_loader/test_elfs/out/sbpfv3_return_err.so
  programs/bpf_loader/test_elfs/out/sbpfv3_return_ok.so
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
  programs/sbf/tests/programs.rs
  svm/examples/Cargo.lock
Labels: feature-gate

#6937 TPU: optimize rate limits
  streamer/src/nonblocking/quic.rs
  tpu-client-next/tests/connection_workers_scheduler_test.rs
Labels: v2.2, v2.3

#6974 Update broken Solana server program and stake pool links
  docs/src/operations/validator-initiatives.md
Labels: community, need:merge-assist

#6090 vote: move benchmarks to bencher 0.1.5
  Cargo.lock
  Cargo.toml
  vote/Cargo.toml
  vote/benches/vote_account.rs
Labels: community, need:merge-assist

#6958 increase max ingest
  streamer/src/nonblocking/stream_throttle.rs
  streamer/src/quic.rs
Labels: v2.3

#7018 ci: fix docs publishing for beta tag
  docs/build.sh
Labels: v2.2, v2.3

#6995 turbine: move benchmarks to bencher 0.1.5
  Cargo.lock
  turbine/Cargo.toml
  turbine/benches/cluster_info.rs
  turbine/benches/cluster_nodes.rs
Labels: community, need:merge-assist

#7011 metrics: move benchmarks to bencher 0.1.5
  Cargo.lock
  metrics/Cargo.toml
  metrics/benches/metrics.rs
Labels: community, need:merge-assist

#6962 Add `slot` to the error context of `EpochRewardsPeriodActiveErrorData` and `SlotNotEpochBoundaryErrorData`
  CHANGELOG.md
  Cargo.lock
  rpc-client-api/Cargo.toml
  rpc-client-api/src/custom_error.rs
Labels: automerge

#7013 fix: typos
  zk-sdk/src/sigma_proofs/grouped_ciphertext_validity/handles_3.rs
  zk-token-sdk/src/sigma_proofs/ciphertext_ciphertext_equality_proof.rs
  zk-token-sdk/src/sigma_proofs/grouped_ciphertext_validity_proof/handles_3.rs
Labels: community, need:merge-assist

#7041 perf: move benchmarks to bencher 0.1.5
  Cargo.lock
  perf/Cargo.toml
  perf/benches/dedup.rs
  perf/benches/discard.rs
  perf/benches/recycler.rs
  perf/benches/reset.rs
  perf/benches/shrink.rs
  perf/benches/sigverify.rs
Labels: community, need:merge-assist

#7055 net-utils: introduce new helper functions
  net-utils/src/sockets.rs
Labels: community, need:merge-assist

#7149 Use vector instead of slice in `InstructionContext::configure`
  ledger-tool/src/program.rs
  program-runtime/src/invoke_context.rs
  program-runtime/src/serialization.rs
  programs/bpf_loader/benches/serialization.rs
  programs/bpf_loader/src/syscalls/cpi.rs
  programs/bpf_loader/src/syscalls/mod.rs
  programs/sbf/benches/bpf_loader.rs
  programs/system/src/system_instruction.rs
  programs/vote/src/vote_state/mod.rs
  svm/src/transaction_processor.rs
  transaction-context/src/lib.rs
Labels: automerge

#7227 Fixed minor spelling errors in code comments and documentation across multiple files.
  ledger/src/sigverify_shreds.rs
  program-runtime/src/loaded_programs.rs
  svm/examples/json-rpc/README.md
Labels: community, need:merge-assist

#7244 Fix Typos in Comments Across Multiple Modules
  core/src/banking_simulation.rs
  ledger/src/blockstore_metrics.rs
  vortexor/src/sender.rs
Labels: community, need:merge-assist
