Repository anza-xyz/agave, pull requests merged in 2025-10, with the labels that each got.

#8223 ci: remove cargo.lock filtering logic from version bump script
  scripts/increment-cargo-version.sh
Labels: v3.0

#8281 vendor quinn
  Cargo.lock
  Cargo.toml
  programs/sbf/Cargo.lock
  programs/sbf/Cargo.toml
Labels: v2.3, v3.0

#8288 Alpenglow mockup: add pacing to TX thread
  core/src/mock_alpenglow_consensus.rs
Labels: automerge

#8303 Expose the ClientId publicly from the gossip Version message
  version/src/lib.rs
Labels: need:merge-assist

#8329 ReceiveAndBuffer: earlier lock count validation
  core/src/banking_stage/transaction_scheduler/receive_and_buffer.rs
Labels: v3.0

#7253 pubsub-client: allow construction with `Request` object with custom headers
  CHANGELOG.md
  client-test/tests/client.rs
  local-cluster/tests/local_cluster.rs
  pubsub-client/src/nonblocking/pubsub_client.rs
  pubsub-client/src/pubsub_client.rs
Labels: automerge, community, need:merge-assist

#8353 Fix UDP client binding to localhost breaking vote propagation
  udp-client/Cargo.toml
  udp-client/src/lib.rs
Labels: community, need:merge-assist

#8185 Return signature verification errors through the RPC as `TransactionError` rather than JSON RPC API errors
  CHANGELOG.md
  rpc/src/rpc.rs
  runtime/src/bank.rs
Labels: automerge

#7811 Modify buildscripts to work with offline builds (e.g. nix builds)
  cargo
  fetch-perf-libs.sh
  net/net.sh
  scripts/cargo-install-all.sh
Labels: community, need:merge-assist
